#!/usr/bin/env python3
"""Build a migration that replaces grammar exercises with topic-aligned cloze items."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "supabase/migrations/20260803150000_topic_aligned_grammar_cloze_exercises.sql"
TOPICS_JSON = Path("/tmp/grammar_topics.json")

COUNTS = {"A1": 5, "A2": 6, "B1": 8, "B2": 10}
OPTS = {"A1": 3, "A2": 3, "B1": 4, "B2": 4}


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def load_banks() -> dict[str, list[tuple]]:
    banks: dict[str, list[tuple]] = {}
    for mod_name in (
        "grammar_cloze_banks_en",
        "grammar_cloze_banks_es",
        "grammar_cloze_banks_fr",
        "grammar_cloze_banks_it",
    ):
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        mod = __import__(mod_name)
        banks.update(mod.get_banks())
    return banks


def validate(topics: list[dict], banks: dict[str, list[tuple]]) -> None:
    missing = [t["id"] for t in topics if t["id"] not in banks]
    if missing:
        raise SystemExit(f"Missing banks for {len(missing)} topics: {missing[:8]}")

    for topic in topics:
        items = banks[topic["id"]]
        need = COUNTS[topic["level"]]
        opt_need = OPTS[topic["level"]]
        if len(items) < need:
            raise SystemExit(f"{topic['id']}: need {need} exercises, got {len(items)}")
        for i, item in enumerate(items[:need]):
            question, options, answer_index, explanation, example = item
            if "___" not in question:
                raise SystemExit(f"{topic['id']}#{i}: question missing ___")
            if len(options) != opt_need:
                raise SystemExit(
                    f"{topic['id']}#{i}: expected {opt_need} options, got {len(options)}"
                )
            if not (0 <= answer_index < len(options)):
                raise SystemExit(f"{topic['id']}#{i}: bad answer_index")
            if not explanation.strip() or not example.strip():
                raise SystemExit(f"{topic['id']}#{i}: empty explanation/example")
            if "Choose the correct" in question or "Elige la frase" in question:
                raise SystemExit(f"{topic['id']}#{i}: generic stem forbidden")


def build_sql(topics: list[dict], banks: dict[str, list[tuple]]) -> str:
    topic_by_id = {t["id"]: t for t in topics}
    rows: list[str] = []
    sort_base: dict[str, int] = {}
    for idx, topic in enumerate(topics):
        sort_base[topic["id"]] = (idx + 1) * 100

    for topic in topics:
        need = COUNTS[topic["level"]]
        items = banks[topic["id"]][:need]
        for n, item in enumerate(items, start=1):
            question, options, answer_index, explanation, example = item
            exercise_id = f"{topic['id']}-cloze-{n}"
            title = f"{topic['title']} · completar {n}"
            if len(title) > 160:
                title = title[:157] + "..."
            options_json = json.dumps(options, ensure_ascii=False)
            rows.append(
                "  ("
                f"'{sql_escape(exercise_id)}', "
                f"'{sql_escape(topic['id'])}', "
                f"'{topic['lang']}', "
                f"'{topic['level']}', "
                f"'{sql_escape(title)}', "
                f"'{sql_escape(explanation)}', "
                f"'{sql_escape(example)}', "
                f"'{sql_escape(question)}', "
                f"'{sql_escape(options_json)}'::jsonb, "
                f"{answer_index}, "
                f"{sort_base[topic['id']] + n}, "
                "true)"
            )

    body = ",\n".join(rows)
    return f"""-- Topic-aligned cloze grammar exercises.
-- Generated by scripts/build_topic_aligned_grammar_exercises.py
-- Counts by level: A1=5, A2=6, B1=8, B2=10. Blank marker: ___.

delete from public.grammar_exercises;

insert into public.grammar_exercises (
  id, topic_id, language, level, title, explanation, example,
  question, options, answer_index, sort_order, is_published
) values
{body};
"""


def main() -> None:
    topics = json.loads(TOPICS_JSON.read_text())
    banks = load_banks()
    validate(topics, banks)
    sql = build_sql(topics, banks)
    OUT.write_text(sql)
    total = sum(COUNTS[t["level"]] for t in topics)
    cloze_ok = len(re.findall(r"___", sql))
    print(f"Wrote {OUT}")
    print(f"topics={len(topics)} exercises={total} cloze_markers={cloze_ok}")


if __name__ == "__main__":
    main()
