"""English grammar cloze exercise banks keyed by topic_id."""

BANKS = {
    "en-grammar-A1-1": [
        (
            "Complete: She ___ a teacher.",
            ["is", "are", "am"],
            0,
            "Usamos 'is' com he, she e it no presente.",
            "She is a teacher.",
        ),
        (
            "Complete: I ___ from Brazil.",
            ["is", "am", "are"],
            1,
            "Com 'I' usamos sempre 'am'.",
            "I am from Brazil.",
        ),
        (
            "Complete: They ___ my friends.",
            ["is", "am", "are"],
            2,
            "Com they, we e you usamos 'are'.",
            "They are my friends.",
        ),
        (
            "Complete: ___ you happy?",
            ["Is", "Am", "Are"],
            2,
            "Perguntas com you usam 'Are' no início.",
            "Are you happy?",
        ),
        (
            "Complete: He ___ not at home.",
            ["is", "are", "am"],
            0,
            "A negativa de he/she/it é 'is not' (isn't).",
            "He is not at home.",
        ),
    ],
    "en-grammar-A1-2": [
        (
            "Complete: I have ___ apple.",
            ["a", "an", "the"],
            1,
            "Usamos 'an' antes de vogal (apple).",
            "I have an apple.",
        ),
        (
            "Complete: She has two ___.",
            ["cat", "cats", "cates"],
            1,
            "O plural regular de cat é cats.",
            "She has two cats.",
        ),
        (
            "Complete: ___ sun is bright today.",
            ["A", "An", "The"],
            2,
            "Usamos 'the' com coisas únicas, como the sun.",
            "The sun is bright today.",
        ),
        (
            "Complete: There are three ___.",
            ["box", "boxs", "boxes"],
            2,
            "Palavras em -x formam o plural com -es.",
            "There are three boxes.",
        ),
        (
            "Complete: He is ___ doctor.",
            ["a", "an", "the"],
            0,
            "Usamos 'a' antes de consoante para profissões.",
            "He is a doctor.",
        ),
    ],
    "en-grammar-A2-3": [
        (
            "Complete: She ___ to school every day.",
            ["go", "goes", "going"],
            1,
            "Na 3ª pessoa do singular, o verbo ganha -s/-es.",
            "She goes to school every day.",
        ),
        (
            "Complete: They ___ football on Sundays.",
            ["play", "plays", "playing"],
            0,
            "Com they usamos a forma base do verbo.",
            "They play football on Sundays.",
        ),
        (
            "Complete: He ___ like coffee.",
            ["don't", "doesn't", "isn't"],
            1,
            "A negativa de he/she/it no present simple é doesn't.",
            "He doesn't like coffee.",
        ),
        (
            "Complete: ___ you speak English?",
            ["Do", "Does", "Are"],
            0,
            "Perguntas com you usam Do + verbo base.",
            "Do you speak English?",
        ),
        (
            "Complete: The train ___ at 8 o'clock.",
            ["leave", "leaves", "leaving"],
            1,
            "Horários e rotinas usam present simple; the train = he/she/it.",
            "The train leaves at 8 o'clock.",
        ),
        (
            "Complete: We ___ TV in the evening.",
            ["watch", "watches", "watching"],
            0,
            "Com we usamos a forma base no present simple.",
            "We watch TV in the evening.",
        ),
    ],
    "en-grammar-A2-4": [
        (
            "Complete: Yesterday I ___ to the park.",
            ["go", "went", "gone"],
            1,
            "O passado irregular de go é went.",
            "Yesterday I went to the park.",
        ),
        (
            "Complete: She ___ a great film last night.",
            ["watch", "watches", "watched"],
            2,
            "Verbos regulares no past simple terminam em -ed.",
            "She watched a great film last night.",
        ),
        (
            "Complete: They ___ not come to the party.",
            ["do", "did", "does"],
            1,
            "A negativa no passado usa did not + verbo base.",
            "They did not come to the party.",
        ),
        (
            "Complete: ___ you see Maria yesterday?",
            ["Do", "Did", "Does"],
            1,
            "Perguntas no past simple usam Did + sujeito + verbo base.",
            "Did you see Maria yesterday?",
        ),
        (
            "Complete: He ___ his keys on the table.",
            ["leave", "left", "leaved"],
            1,
            "Leave é irregular: leave → left.",
            "He left his keys on the table.",
        ),
        (
            "Complete: We ___ dinner at 7 pm.",
            ["have", "had", "has"],
            1,
            "O passado de have é had para todas as pessoas.",
            "We had dinner at 7 pm.",
        ),
    ],
    "en-grammar-A2-5": [
        (
            "Complete: I ___ visit my grandparents tomorrow.",
            ["am going to", "goes to", "going"],
            0,
            "Be going to expressa planos futuros já decididos.",
            "I am going to visit my grandparents tomorrow.",
        ),
        (
            "Complete: She ___ fly to London next week.",
            ["will", "is", "does"],
            0,
            "Will + verbo base expressa decisões ou previsões futuras.",
            "She will fly to London next week.",
        ),
        (
            "Complete: They ___ meeting us at 6.",
            ["are", "is", "will"],
            0,
            "Present continuous também marca planos combinados.",
            "They are meeting us at 6.",
        ),
        (
            "Complete: We ___ going to stay home tonight.",
            ["am", "is", "are"],
            2,
            "Com we, a forma de be é are (are going to).",
            "We are going to stay home tonight.",
        ),
        (
            "Complete: ___ you going to study this weekend?",
            ["Is", "Are", "Do"],
            1,
            "Perguntas com going to: Are/Is + sujeito + going to + verbo.",
            "Are you going to study this weekend?",
        ),
        (
            "Complete: He ___ not going to buy a car.",
            ["is", "are", "am"],
            0,
            "Negativa: he/she/it + is not going to.",
            "He is not going to buy a car.",
        ),
    ],
    "en-grammar-B1-6": [
        (
            "Complete: I ___ never been to Japan.",
            ["have", "has", "had", "am"],
            0,
            "Present perfect: have/has + past participle para experiências.",
            "I have never been to Japan.",
        ),
        (
            "Complete: She ___ just finished her homework.",
            ["have", "has", "had", "is"],
            1,
            "Com she usamos has + past participle.",
            "She has just finished her homework.",
        ),
        (
            "Complete: ___ you ever eaten sushi?",
            ["Have", "Has", "Did", "Do"],
            0,
            "Perguntas de experiência usam Have/Has + ever + particípio.",
            "Have you ever eaten sushi?",
        ),
        (
            "Complete: They ___ lived here since 2019.",
            ["have", "has", "are", "did"],
            0,
            "Since marca o ponto de início com present perfect.",
            "They have lived here since 2019.",
        ),
        (
            "Complete: He hasn't ___ his keys yet.",
            ["find", "found", "finding", "finds"],
            1,
            "Yet aparece em negativas; o verbo fica no particípio.",
            "He hasn't found his keys yet.",
        ),
        (
            "Complete: We have known each other ___ ten years.",
            ["since", "for", "from", "during"],
            1,
            "For + período de tempo; since + ponto de início.",
            "We have known each other for ten years.",
        ),
        (
            "Complete: Look! Someone ___ broken the window.",
            ["have", "has", "had", "is"],
            1,
            "Resultado recente no presente: has + past participle.",
            "Look! Someone has broken the window.",
        ),
        (
            "Complete: How long ___ she worked here?",
            ["have", "has", "did", "does"],
            1,
            "How long + present perfect pergunta duração até agora.",
            "How long has she worked here?",
        ),
    ],
    "en-grammar-B1-7": [
        (
            "Complete: The woman ___ lives next door is a doctor.",
            ["who", "which", "where", "whose"],
            0,
            "Who refere-se a pessoas como sujeito da oração relativa.",
            "The woman who lives next door is a doctor.",
        ),
        (
            "Complete: This is the book ___ I bought yesterday.",
            ["who", "which", "where", "whose"],
            1,
            "Which (ou that) refere-se a coisas.",
            "This is the book which I bought yesterday.",
        ),
        (
            "Complete: That's the café ___ we first met.",
            ["who", "which", "where", "whose"],
            2,
            "Where introduz lugar em orações relativas.",
            "That's the café where we first met.",
        ),
        (
            "Complete: The man ___ car was stolen called the police.",
            ["who", "which", "where", "whose"],
            3,
            "Whose indica posse em relative clauses.",
            "The man whose car was stolen called the police.",
        ),
        (
            "Complete: Students ___ study hard usually pass.",
            ["which", "who", "where", "whom"],
            1,
            "Who + verbo: a pessoa é o sujeito da cláusula.",
            "Students who study hard usually pass.",
        ),
        (
            "Complete: The film ___ we watched was amazing.",
            ["who", "that", "where", "whose"],
            1,
            "That pode substituir which em defining clauses.",
            "The film that we watched was amazing.",
        ),
        (
            "Complete: Do you remember the day ___ we arrived?",
            ["who", "which", "when", "whose"],
            2,
            "When refere-se a tempo em orações relativas.",
            "Do you remember the day when we arrived?",
        ),
        (
            "Complete: The people ___ I invited didn't come.",
            ["which", "where", "whose", "whom"],
            3,
            "Whom (ou who/that) é objeto da cláusula relativa.",
            "The people whom I invited didn't come.",
        ),
    ],
    "en-grammar-B1-8": [
        (
            "Complete: You ___ see a doctor about that cough.",
            ["should", "shouldn't", "mustn't", "wouldn't"],
            0,
            "Should expressa conselho ou recomendação.",
            "You should see a doctor about that cough.",
        ),
        (
            "Complete: You ___ smoke in this building.",
            ["should", "mustn't", "might", "could"],
            1,
            "Mustn't indica proibição forte.",
            "You mustn't smoke in this building.",
        ),
        (
            "Complete: It ___ rain later, so take an umbrella.",
            ["must", "might", "should", "have to"],
            1,
            "Might expressa possibilidade, não certeza.",
            "It might rain later, so take an umbrella.",
        ),
        (
            "Complete: You ___ wear a seatbelt — it's the law.",
            ["might", "could", "have to", "shouldn't"],
            2,
            "Have to marca obrigação externa (lei, regra).",
            "You have to wear a seatbelt — it's the law.",
        ),
        (
            "Complete: If I were you, I ___ apologise.",
            ["will", "would", "must", "can"],
            1,
            "Conselho hipotético: If I were you, I would...",
            "If I were you, I would apologise.",
        ),
        (
            "Complete: You ___ eat so much sugar; it's unhealthy.",
            ["should", "shouldn't", "must", "can"],
            1,
            "Shouldn't aconselha a não fazer algo.",
            "You shouldn't eat so much sugar; it's unhealthy.",
        ),
        (
            "Complete: We ___ leave now or we'll miss the train.",
            ["ought to", "mustn't", "mightn't", "needn't"],
            0,
            "Ought to é semelhante a should (conselho/necessidade).",
            "We ought to leave now or we'll miss the train.",
        ),
        (
            "Complete: You ___ bring food; there will be plenty.",
            ["must", "have to", "needn't", "should"],
            2,
            "Needn't = não é necessário (ausência de obrigação).",
            "You needn't bring food; there will be plenty.",
        ),
    ],
    "en-grammar-B2-9": [
        (
            "Complete: If it rains tomorrow, we ___ stay indoors.",
            ["will", "would", "would have", "had"],
            0,
            "1ª condicional: if + present, will + verbo (situação real).",
            "If it rains tomorrow, we will stay indoors.",
        ),
        (
            "Complete: If I ___ more time, I would learn Italian.",
            ["have", "had", "will have", "would have"],
            1,
            "2ª condicional: if + past, would + verbo (hipótese presente).",
            "If I had more time, I would learn Italian.",
        ),
        (
            "Complete: If she had studied, she ___ passed the exam.",
            ["will have", "would", "would have", "had"],
            2,
            "3ª condicional: if + past perfect, would have + particípio.",
            "If she had studied, she would have passed the exam.",
        ),
        (
            "Complete: Unless you hurry, you ___ miss the bus.",
            ["will", "would", "would have", "had"],
            0,
            "Unless = if not; combina com will no resultado real.",
            "Unless you hurry, you will miss the bus.",
        ),
        (
            "Complete: If I ___ you, I would take the job.",
            ["am", "was", "were", "been"],
            2,
            "Em 2ª condicional formal, usamos were para todas as pessoas.",
            "If I were you, I would take the job.",
        ),
        (
            "Complete: Had I known earlier, I ___ helped you.",
            ["will have", "would", "would have", "had"],
            2,
            "Inversão Had I known = If I had known (3ª condicional).",
            "Had I known earlier, I would have helped you.",
        ),
        (
            "Complete: If he ___ harder, he might get promoted.",
            ["works", "worked", "had worked", "would work"],
            0,
            "1ª condicional pode usar might no resultado (possibilidade).",
            "If he works harder, he might get promoted.",
        ),
        (
            "Complete: She wouldn't be tired if she ___ earlier.",
            ["goes", "went", "had gone", "would go"],
            2,
            "Mixed: resultado presente + causa no passado (had gone).",
            "She wouldn't be tired if she had gone earlier.",
        ),
        (
            "Complete: ___ it rain, the match will be cancelled.",
            ["If", "Should", "Were", "Had"],
            1,
            "Should it rain = If it rains (inversão formal 1ª condicional).",
            "Should it rain, the match will be cancelled.",
        ),
        (
            "Complete: I wish I ___ spoken to her before she left.",
            ["have", "had", "would", "will"],
            1,
            "I wish + past perfect expressa arrependimento sobre o passado.",
            "I wish I had spoken to her before she left.",
        ),
    ],
    "en-grammar-B2-10": [
        (
            "Complete: She said she ___ tired.",
            ["is", "was", "were", "be"],
            1,
            "No reported speech, present simple costuma virar past simple.",
            "She said she was tired.",
        ),
        (
            "Complete: He told me he ___ finish the report by Friday.",
            ["will", "would", "can", "may"],
            1,
            "Will no discurso direto vira would no indireto.",
            "He told me he would finish the report by Friday.",
        ),
        (
            "Complete: They asked where I ___.",
            ["live", "lived", "am living", "lives"],
            1,
            "Perguntas indiretas: ordem afirmativa e tempo recuado.",
            "They asked where I lived.",
        ),
        (
            "Complete: She said she ___ already eaten.",
            ["has", "have", "had", "was"],
            2,
            "Present perfect no direto vira past perfect no indireto.",
            "She said she had already eaten.",
        ),
        (
            "Complete: He asked me ___ I could help him.",
            ["that", "if", "what", "how"],
            1,
            "Yes/no questions no indireto usam if/whether.",
            "He asked me if I could help him.",
        ),
        (
            "Complete: \"I may be late,\" she said. → She said she ___ be late.",
            ["may", "might", "can", "must"],
            1,
            "May frequentemente vira might no reported speech.",
            "She said she might be late.",
        ),
        (
            "Complete: The manager insisted that we ___ on time.",
            ["are", "be", "were", "been"],
            1,
            "Após insist/suggest/demand, usa-se subjuntivo (base form).",
            "The manager insisted that we be on time.",
        ),
        (
            "Complete: She claimed to ___ nothing about the mistake.",
            ["know", "knowing", "have known", "knew"],
            0,
            "Claim + to-infinitive reporta afirmação de forma compacta.",
            "She claimed to know nothing about the mistake.",
        ),
        (
            "Complete: He denied ___ the money.",
            ["to take", "taking", "take", "took"],
            1,
            "Deny + gerund (não to-infinitive) no discurso indireto.",
            "He denied taking the money.",
        ),
        (
            "Complete: \"Don't touch that,\" she warned. → She warned me ___ touch that.",
            ["to not", "not to", "don't", "to don't"],
            1,
            "Ordens negativas no indireto: warn/tell + not to + verbo.",
            "She warned me not to touch that.",
        ),
    ],
    "en-grammar-extra-01": [
        (
            "Complete: The book is ___ the table.",
            ["in", "on", "at"],
            1,
            "On indica superfície (em cima de).",
            "The book is on the table.",
        ),
        (
            "Complete: She lives ___ London.",
            ["in", "on", "at"],
            0,
            "In é usado com cidades e países.",
            "She lives in London.",
        ),
        (
            "Complete: Meet me ___ the bus stop.",
            ["in", "on", "at"],
            2,
            "At marca ponto específico (ponto de encontro).",
            "Meet me at the bus stop.",
        ),
        (
            "Complete: We go ___ school by bus.",
            ["in", "to", "at"],
            1,
            "To indica movimento em direção a um lugar.",
            "We go to school by bus.",
        ),
        (
            "Complete: He arrives ___ 9 o'clock.",
            ["in", "on", "at"],
            2,
            "At é usado com horas exatas.",
            "He arrives at 9 o'clock.",
        ),
    ],
    "en-grammar-extra-02": [
        (
            "Complete: I stayed home ___ I was sick.",
            ["because", "although", "so"],
            0,
            "Because introduz a razão ou causa.",
            "I stayed home because I was sick.",
        ),
        (
            "Complete: ___ it was raining, we went for a walk.",
            ["Because", "Although", "So"],
            1,
            "Although introduz contraste (apesar de).",
            "Although it was raining, we went for a walk.",
        ),
        (
            "Complete: It was late, ___ we took a taxi.",
            ["because", "although", "so"],
            2,
            "So introduz o resultado ou consequência.",
            "It was late, so we took a taxi.",
        ),
        (
            "Complete: Call me ___ you arrive.",
            ["because", "so", "when"],
            2,
            "When marca o momento em que algo acontece.",
            "Call me when you arrive.",
        ),
        (
            "Complete: She smiled ___ she was nervous.",
            ["because", "although", "so"],
            1,
            "Although liga ideias contrastantes.",
            "She smiled although she was nervous.",
        ),
        (
            "Complete: He left early ___ he had a meeting.",
            ["so", "because", "although"],
            1,
            "Because explica o motivo da ação.",
            "He left early because he had a meeting.",
        ),
    ],
    "en-grammar-extra-03": [
        (
            "Complete: Please ___ your shoes before entering.",
            ["take off", "take on", "take up"],
            0,
            "Take off = tirar (roupa, sapatos).",
            "Please take off your shoes before entering.",
        ),
        (
            "Complete: I need to ___ early tomorrow.",
            ["get up", "get on", "get off"],
            0,
            "Get up = levantar-se da cama.",
            "I need to get up early tomorrow.",
        ),
        (
            "Complete: Can you ___ the lights? It's dark.",
            ["turn on", "turn up", "turn off"],
            0,
            "Turn on = ligar (luz, aparelho).",
            "Can you turn on the lights? It's dark.",
        ),
        (
            "Complete: She ___ smoking last year.",
            ["gave in", "gave up", "gave out"],
            1,
            "Give up = parar / desistir de um hábito.",
            "She gave up smoking last year.",
        ),
        (
            "Complete: I can't find my keys — can you help me ___ them?",
            ["look after", "look for", "look up"],
            1,
            "Look for = procurar algo.",
            "I can't find my keys — can you help me look for them?",
        ),
        (
            "Complete: Who will ___ the children while we're out?",
            ["look after", "look for", "look into"],
            0,
            "Look after = cuidar de alguém.",
            "Who will look after the children while we're out?",
        ),
    ],
    "en-grammar-extra-04": [
        (
            "Complete: The plan seemed perfect; ___, it failed.",
            ["however", "therefore", "moreover", "likewise"],
            0,
            "However introduz contraste entre ideias.",
            "The plan seemed perfect; however, it failed.",
        ),
        (
            "Complete: Sales fell sharply; ___, we cut costs.",
            ["however", "therefore", "moreover", "meanwhile"],
            1,
            "Therefore marca consequência lógica.",
            "Sales fell sharply; therefore, we cut costs.",
        ),
        (
            "Complete: The hotel is cheap; ___, it is very clean.",
            ["however", "therefore", "moreover", "otherwise"],
            2,
            "Moreover adiciona informação reforçando o argumento.",
            "The hotel is cheap; moreover, it is very clean.",
        ),
        (
            "Complete: She studied hard; ___, she passed easily.",
            ["nevertheless", "as a result", "on the other hand", "in contrast"],
            1,
            "As a result expressa o desfecho de uma causa.",
            "She studied hard; as a result, she passed easily.",
        ),
        (
            "Complete: The evidence is weak; ___, the jury convicted him.",
            ["therefore", "moreover", "nevertheless", "furthermore"],
            2,
            "Nevertheless = apesar disso (contraste forte).",
            "The evidence is weak; nevertheless, the jury convicted him.",
        ),
        (
            "Complete: We must raise funding; ___, the project will stop.",
            ["otherwise", "furthermore", "meanwhile", "likewise"],
            0,
            "Otherwise = caso contrário (consequência negativa).",
            "We must raise funding; otherwise, the project will stop.",
        ),
        (
            "Complete: The data is incomplete; ___, the method is flawed.",
            ["therefore", "furthermore", "however", "thus"],
            1,
            "Furthermore adiciona outro ponto na mesma direção.",
            "The data is incomplete; furthermore, the method is flawed.",
        ),
        (
            "Complete: Demand rose; ___, prices increased.",
            ["however", "conversely", "thus", "whereas"],
            2,
            "Thus é conector formal de conclusão/resultado.",
            "Demand rose; thus, prices increased.",
        ),
    ],
    "en-grammar-extra-05": [
        (
            "Complete: I enjoy ___ in the morning.",
            ["to run", "running", "run", "ran"],
            1,
            "Enjoy é seguido de gerúndio (-ing).",
            "I enjoy running in the morning.",
        ),
        (
            "Complete: She decided ___ abroad.",
            ["studying", "to study", "study", "studied"],
            1,
            "Decide é seguido de to-infinitive.",
            "She decided to study abroad.",
        ),
        (
            "Complete: He suggested ___ a break.",
            ["to take", "taking", "take", "took"],
            1,
            "Suggest + gerúndio (não to-infinitive).",
            "He suggested taking a break.",
        ),
        (
            "Complete: They hope ___ the project soon.",
            ["finishing", "to finish", "finish", "finished"],
            1,
            "Hope + to-infinitive.",
            "They hope to finish the project soon.",
        ),
        (
            "Complete: I'm looking forward to ___ you.",
            ["see", "seeing", "to see", "saw"],
            1,
            "Look forward to + gerúndio (to é preposição).",
            "I'm looking forward to seeing you.",
        ),
        (
            "Complete: Don't forget ___ the door.",
            ["locking", "to lock", "lock", "locked"],
            1,
            "Forget + to-infinitive = não se esquecer de fazer algo.",
            "Don't forget to lock the door.",
        ),
        (
            "Complete: She stopped ___ when the phone rang.",
            ["to talk", "talking", "talk", "talked"],
            1,
            "Stop + gerúndio = interromper a ação em curso.",
            "She stopped talking when the phone rang.",
        ),
        (
            "Complete: It's worth ___ the museum.",
            ["to visit", "visiting", "visit", "visited"],
            1,
            "Worth + gerúndio.",
            "It's worth visiting the museum.",
        ),
    ],
    "en-grammar-extra-06": [
        (
            "Complete: Please ___ attention to the instructions.",
            ["make", "pay", "do", "give"],
            1,
            "Collocation: pay attention (não make/do).",
            "Please pay attention to the instructions.",
        ),
        (
            "Complete: She ___ a decision after long thought.",
            ["did", "made", "took", "had"],
            1,
            "Collocation: make a decision.",
            "She made a decision after long thought.",
        ),
        (
            "Complete: He ___ a mistake on the form.",
            ["did", "made", "took", "had"],
            1,
            "Collocation: make a mistake.",
            "He made a mistake on the form.",
        ),
        (
            "Complete: They ___ a meeting for Monday.",
            ["did", "made", "held", "put"],
            2,
            "Collocation: hold a meeting.",
            "They held a meeting for Monday.",
        ),
        (
            "Complete: I need to ___ an appointment with the dentist.",
            ["do", "make", "take", "have"],
            1,
            "Collocation: make an appointment.",
            "I need to make an appointment with the dentist.",
        ),
        (
            "Complete: She ___ progress in English this year.",
            ["did", "made", "took", "got"],
            1,
            "Collocation: make progress.",
            "She made progress in English this year.",
        ),
        (
            "Complete: Can you ___ me a favour?",
            ["make", "do", "give", "take"],
            1,
            "Collocation: do someone a favour.",
            "Can you do me a favour?",
        ),
        (
            "Complete: We ___ a risk launching the product early.",
            ["did", "made", "took", "gave"],
            2,
            "Collocation: take a risk.",
            "We took a risk launching the product early.",
        ),
    ],
    "en-grammar-extra-07": [
        (
            "Complete: The deal ___ at the last minute.",
            ["fell out", "fell through", "fell apart", "fell behind"],
            1,
            "Fall through = um plano ou acordo fracassa.",
            "The deal fell through at the last minute.",
        ),
        (
            "Complete: She finally ___ to her brother's point of view.",
            ["came across", "came up", "came round", "came into"],
            2,
            "Come round (to) = mudar de opinião e concordar.",
            "She finally came round to her brother's point of view.",
        ),
        (
            "Complete: He ___ a large fortune from his aunt.",
            ["came across", "came into", "came up with", "came round"],
            1,
            "Come into = herdar dinheiro ou propriedade.",
            "He came into a large fortune from his aunt.",
        ),
        (
            "Complete: We need to ___ the problem before it grows.",
            ["look after", "look up to", "look into", "look down on"],
            2,
            "Look into = investigar.",
            "We need to look into the problem before it grows.",
        ),
        (
            "Complete: The company had to ___ dozens of workers.",
            ["lay down", "lay out", "lay on", "lay off"],
            3,
            "Lay off = demitir por redução de quadro.",
            "The company had to lay off dozens of workers.",
        ),
        (
            "Complete: She ___ her resignation yesterday.",
            ["handed out", "handed in", "handed over", "handed down"],
            1,
            "Hand in = entregar formalmente (pedido, renúncia).",
            "She handed in her resignation yesterday.",
        ),
        (
            "Complete: I can't ___ what he means.",
            ["make up", "make for", "make off", "make out"],
            3,
            "Make out = compreender / decifrar.",
            "I can't make out what he means.",
        ),
        (
            "Complete: They ___ the rumour that she was leaving.",
            ["put off", "put about", "put up", "put through"],
            1,
            "Put about = espalhar um boato.",
            "They put about the rumour that she was leaving.",
        ),
        (
            "Complete: He ___ the offer without hesitation.",
            ["turned up", "turned in", "turned down", "turned over"],
            2,
            "Turn down = recusar uma oferta.",
            "He turned down the offer without hesitation.",
        ),
        (
            "Complete: Let's ___ our differences and cooperate.",
            ["set off", "set out", "set up", "set aside"],
            3,
            "Set aside = deixar de lado temporariamente.",
            "Let's set aside our differences and cooperate.",
        ),
    ],
    "en-grammar-extra-08": [
        (
            "Complete: After the long meeting, I was completely ___.",
            ["worn out", "worn off", "worn in", "worn away"],
            0,
            "Worn out = exausto (idiom comum).",
            "After the long meeting, I was completely worn out.",
        ),
        (
            "Complete: The news came ___ — nobody expected it.",
            ["out of the blue", "out of order", "out of date", "out of hand"],
            0,
            "Out of the blue = de surpresa, inesperadamente.",
            "The news came out of the blue — nobody expected it.",
        ),
        (
            "Complete: Don't ___ — we still have time.",
            ["jump the gun", "hit the roof", "spill the beans", "bite the bullet"],
            0,
            "Jump the gun = agir cedo demais.",
            "Don't jump the gun — we still have time.",
        ),
        (
            "Complete: She finally ___ and told us the secret.",
            ["spilled the beans", "hit the nail", "broke the ice", "cut corners"],
            0,
            "Spill the beans = revelar um segredo.",
            "She finally spilled the beans and told us the secret.",
        ),
        (
            "Complete: He decided to ___ and accept the criticism.",
            ["bite the bullet", "beat around the bush", "cry over spilt milk", "let the cat out"],
            0,
            "Bite the bullet = enfrentar algo difícil com coragem.",
            "He decided to bite the bullet and accept the criticism.",
        ),
        (
            "Complete: Their relationship is ___; they barely speak.",
            ["on the rocks", "on the house", "on thin ice", "on cloud nine"],
            0,
            "On the rocks = em crise (relacionamento).",
            "Their relationship is on the rocks; they barely speak.",
        ),
        (
            "Complete: Stop ___ and tell me what you want.",
            ["beating around the bush", "hitting the roof", "breaking the ice", "cutting corners"],
            0,
            "Beat around the bush = evitar ir direto ao ponto.",
            "Stop beating around the bush and tell me what you want.",
        ),
        (
            "Complete: When he heard the news, he ___.",
            ["hit the roof", "hit the books", "hit the sack", "hit the nail"],
            0,
            "Hit the roof = ficar furioso.",
            "When he heard the news, he hit the roof.",
        ),
        (
            "Complete: The project succeeded against ___.",
            ["all odds", "the clock", "the grain", "the tide"],
            0,
            "Against all odds = apesar de todas as probabilidades.",
            "The project succeeded against all odds.",
        ),
        (
            "Complete: Let's ___ and get this done today.",
            ["roll up our sleeves", "keep our chin up", "call it a day", "pull strings"],
            0,
            "Roll up one's sleeves = preparar-se para trabalhar duro.",
            "Let's roll up our sleeves and get this done today.",
        ),
    ],
    "en-grammar-complete-a1-01": [
        (
            "Complete: ___ am a student.",
            ["I", "Me", "My"],
            0,
            "I é pronome sujeito; me é objeto.",
            "I am a student.",
        ),
        (
            "Complete: She helps ___.",
            ["I", "me", "my"],
            1,
            "Após o verbo usamos pronome objeto (me).",
            "She helps me.",
        ),
        (
            "Complete: ___ are my parents.",
            ["Them", "They", "Their"],
            1,
            "They é o sujeito; them seria objeto.",
            "They are my parents.",
        ),
        (
            "Complete: Can you call ___ later?",
            ["she", "her", "hers"],
            1,
            "Her é o pronome objeto de she.",
            "Can you call her later?",
        ),
        (
            "Complete: We saw ___ at the cinema.",
            ["they", "them", "their"],
            1,
            "Them é objeto de they.",
            "We saw them at the cinema.",
        ),
    ],
    "en-grammar-complete-a1-02": [
        (
            "Complete: This is ___ book.",
            ["I", "my", "me"],
            1,
            "My é adjetivo possessivo antes do substantivo.",
            "This is my book.",
        ),
        (
            "Complete: ___ car is red.",
            ["She", "Her", "Hers"],
            1,
            "Her + substantivo = possessivo.",
            "Her car is red.",
        ),
        (
            "Complete: ___ are my keys on the table.",
            ["This", "These", "That"],
            1,
            "These = estes/estas (plural, perto).",
            "These are my keys on the table.",
        ),
        (
            "Complete: ___ house over there is old.",
            ["This", "These", "That"],
            2,
            "That = aquele/aquela (singular, longe).",
            "That house over there is old.",
        ),
        (
            "Complete: The bag is ___.",
            ["she", "her", "hers"],
            2,
            "Hers é pronome possessivo (sem substantivo depois).",
            "The bag is hers.",
        ),
    ],
    "en-grammar-complete-a1-03": [
        (
            "Complete: I ___ a car.",
            ["have", "has", "having"],
            0,
            "Com I usamos have para posse.",
            "I have a car.",
        ),
        (
            "Complete: She ___ got two brothers.",
            ["have", "has", "is"],
            1,
            "Have got: he/she/it usa has got.",
            "She has got two brothers.",
        ),
        (
            "Complete: ___ you got a pen?",
            ["Have", "Has", "Do"],
            0,
            "Pergunta com have got: Have + sujeito + got...?",
            "Have you got a pen?",
        ),
        (
            "Complete: They ___ any pets.",
            ["haven't got", "hasn't got", "isn't got"],
            0,
            "Negativa plural: haven't got.",
            "They haven't got any pets.",
        ),
        (
            "Complete: He ___ a new phone.",
            ["have", "has", "having"],
            1,
            "Com he/she/it usamos has.",
            "He has a new phone.",
        ),
    ],
    "en-grammar-complete-a1-04": [
        (
            "Complete: I ___ breakfast at 7.",
            ["eat", "eats", "eating"],
            0,
            "Com I usamos a forma base no present simple.",
            "I eat breakfast at 7.",
        ),
        (
            "Complete: She ___ English very well.",
            ["speak", "speaks", "speaking"],
            1,
            "3ª pessoa singular: verbo + -s.",
            "She speaks English very well.",
        ),
        (
            "Complete: He ___ work at 9.",
            ["start", "starts", "starting"],
            1,
            "Rotinas: he/she/it + verbo com -s.",
            "He starts work at 9.",
        ),
        (
            "Complete: We ___ to music every day.",
            ["listen", "listens", "listening"],
            0,
            "Com we usamos a forma base.",
            "We listen to music every day.",
        ),
        (
            "Complete: My brother ___ football.",
            ["like", "likes", "liking"],
            1,
            "My brother = he → likes.",
            "My brother likes football.",
        ),
    ],
    "en-grammar-complete-a1-05": [
        (
            "Complete: I ___ swim.",
            ["can", "cans", "am can"],
            0,
            "Can expressa habilidade; forma igual para todas as pessoas.",
            "I can swim.",
        ),
        (
            "Complete: She ___ drive yet.",
            ["can", "can't", "cans"],
            1,
            "Can't = cannot (não consegue / não sabe).",
            "She can't drive yet.",
        ),
        (
            "Complete: ___ you open the window?",
            ["Can", "Do", "Are"],
            0,
            "Can também pede permissão ou faz pedido.",
            "Can you open the window?",
        ),
        (
            "Complete: He can ___ very fast.",
            ["run", "runs", "running"],
            0,
            "Após can usamos o verbo na forma base.",
            "He can run very fast.",
        ),
        (
            "Complete: They ___ speak Japanese.",
            ["can", "cans", "are can"],
            0,
            "Can não muda com they; não se adiciona -s.",
            "They can speak Japanese.",
        ),
    ],
    "en-grammar-complete-a1-06": [
        (
            "Complete: ___ is your name?",
            ["What", "Where", "Who"],
            0,
            "What pergunta por informação / coisa / nome.",
            "What is your name?",
        ),
        (
            "Complete: ___ do you live?",
            ["What", "Where", "Who"],
            1,
            "Where pergunta por lugar.",
            "Where do you live?",
        ),
        (
            "Complete: ___ is that man?",
            ["What", "Where", "Who"],
            2,
            "Who pergunta por pessoa.",
            "Who is that man?",
        ),
        (
            "Complete: ___ old are you?",
            ["What", "How", "When"],
            1,
            "How old pergunta idade.",
            "How old are you?",
        ),
        (
            "Complete: ___ is your birthday?",
            ["What", "Where", "When"],
            2,
            "When pergunta por tempo / data.",
            "When is your birthday?",
        ),
    ],
    "en-grammar-complete-a1-07": [
        (
            "Complete: ___ the door, please.",
            ["Open", "Opens", "Opening"],
            0,
            "Imperativo usa a forma base do verbo.",
            "Open the door, please.",
        ),
        (
            "Complete: ___ be late for class.",
            ["Don't", "Doesn't", "Not"],
            0,
            "Imperativo negativo: Don't + verbo base.",
            "Don't be late for class.",
        ),
        (
            "Complete: ___ go to the park.",
            ["Let's", "Let", "Lets"],
            0,
            "Let's + verbo = sugestão inclusiva (nós).",
            "Let's go to the park.",
        ),
        (
            "Complete: ___ me help you with that bag.",
            ["Let", "Let's", "Lets"],
            0,
            "Let + objeto + verbo = permitir / oferecer ajuda.",
            "Let me help you with that bag.",
        ),
        (
            "Complete: ___ quiet, please!",
            ["Be", "Are", "Is"],
            0,
            "Imperativo de be: Be + adjetivo.",
            "Be quiet, please!",
        ),
    ],
    "en-grammar-complete-a2-01": [
        (
            "Complete: She ___ reading a book now.",
            ["is", "are", "am"],
            0,
            "Present continuous: am/is/are + -ing.",
            "She is reading a book now.",
        ),
        (
            "Complete: Look! They ___ playing football.",
            ["is", "are", "am"],
            1,
            "Com they usamos are + -ing.",
            "Look! They are playing football.",
        ),
        (
            "Complete: I ___ working at the moment.",
            ["am", "is", "are"],
            0,
            "Com I: am + -ing.",
            "I am working at the moment.",
        ),
        (
            "Complete: ___ it raining outside?",
            ["Is", "Are", "Do"],
            0,
            "Pergunta: Is/Are + sujeito + -ing?",
            "Is it raining outside?",
        ),
        (
            "Complete: We ___ not watching TV right now.",
            ["am", "is", "are"],
            2,
            "Negativa: are not (aren't) + -ing.",
            "We are not watching TV right now.",
        ),
        (
            "Complete: He ___ cooking dinner at the moment.",
            ["is", "are", "am"],
            0,
            "Ação em progresso agora: is + -ing.",
            "He is cooking dinner at the moment.",
        ),
    ],
    "en-grammar-complete-a2-02": [
        (
            "Complete: She ___ a letter to her friend.",
            ["write", "wrote", "written"],
            1,
            "Write é irregular: write → wrote → written.",
            "She wrote a letter to her friend.",
        ),
        (
            "Complete: We ___ the film last weekend.",
            ["see", "saw", "seen"],
            1,
            "See → saw no past simple.",
            "We saw the film last weekend.",
        ),
        (
            "Complete: He ___ home late yesterday.",
            ["come", "came", "comed"],
            1,
            "Come → came (irregular).",
            "He came home late yesterday.",
        ),
        (
            "Complete: I ___ my wallet on the bus.",
            ["lose", "lost", "losen"],
            1,
            "Lose → lost.",
            "I lost my wallet on the bus.",
        ),
        (
            "Complete: They ___ all the cake.",
            ["eat", "ate", "eaten"],
            1,
            "Eat → ate no passado.",
            "They ate all the cake.",
        ),
        (
            "Complete: She ___ the truth about the accident.",
            ["know", "knew", "known"],
            1,
            "Know → knew.",
            "She knew the truth about the accident.",
        ),
    ],
    "en-grammar-complete-a2-03": [
        (
            "Complete: This book is ___ than that one.",
            ["interesting", "more interesting", "most interesting"],
            1,
            "Comparativo de adjetivos longos: more + adjective.",
            "This book is more interesting than that one.",
        ),
        (
            "Complete: She is ___ than her brother.",
            ["tall", "taller", "tallest"],
            1,
            "Adjetivos curtos: -er no comparativo.",
            "She is taller than her brother.",
        ),
        (
            "Complete: This is the ___ restaurant in town.",
            ["good", "better", "best"],
            2,
            "Good → better → best (irregular).",
            "This is the best restaurant in town.",
        ),
        (
            "Complete: My car is ___ than yours.",
            ["fast", "faster", "fastest"],
            1,
            "Comparativo: faster than.",
            "My car is faster than yours.",
        ),
        (
            "Complete: Mount Everest is the ___ mountain in the world.",
            ["high", "higher", "highest"],
            2,
            "Superlativo: the + -est.",
            "Mount Everest is the highest mountain in the world.",
        ),
        (
            "Complete: Today is ___ than yesterday.",
            ["bad", "worse", "worst"],
            1,
            "Bad → worse → worst.",
            "Today is worse than yesterday.",
        ),
    ],
    "en-grammar-complete-a2-04": [
        (
            "Complete: She ___ arrives late.",
            ["never", "beautiful", "quick"],
            0,
            "Never é advérbio de frequência antes do verbo principal.",
            "She never arrives late.",
        ),
        (
            "Complete: He speaks English ___.",
            ["fluent", "fluently", "fluency"],
            1,
            "Advérbios de modo costumam terminar em -ly.",
            "He speaks English fluently.",
        ),
        (
            "Complete: I ___ go to the gym on Mondays.",
            ["always", "slow", "careful"],
            0,
            "Always indica frequência 100%.",
            "I always go to the gym on Mondays.",
        ),
        (
            "Complete: They drive very ___.",
            ["careful", "carefully", "care"],
            1,
            "Carefully modifica o verbo drive.",
            "They drive very carefully.",
        ),
        (
            "Complete: We ___ eat out; maybe once a month.",
            ["usually", "rarely", "always"],
            1,
            "Rarely = raramente (baixa frequência).",
            "We rarely eat out; maybe once a month.",
        ),
        (
            "Complete: She finished the test ___.",
            ["quick", "quickly", "quicker"],
            1,
            "Quickly é o advérbio de modo de quick.",
            "She finished the test quickly.",
        ),
    ],
    "en-grammar-complete-a2-05": [
        (
            "Complete: You ___ drink more water.",
            ["should", "shouldn't", "mustn't"],
            0,
            "Should dá conselho.",
            "You should drink more water.",
        ),
        (
            "Complete: You ___ park here — it's forbidden.",
            ["must", "mustn't", "should"],
            1,
            "Mustn't = proibição.",
            "You mustn't park here — it's forbidden.",
        ),
        (
            "Complete: I ___ wear a uniform at work.",
            ["have to", "shouldn't", "mustn't"],
            0,
            "Have to = obrigação externa (regra do trabalho).",
            "I have to wear a uniform at work.",
        ),
        (
            "Complete: You ___ touch that wire; it's dangerous.",
            ["should", "must", "mustn't"],
            2,
            "Mustn't alerta para algo perigoso/proibido.",
            "You mustn't touch that wire; it's dangerous.",
        ),
        (
            "Complete: She ___ study harder for the exam.",
            ["should", "mustn't", "haven't to"],
            0,
            "Should recomenda uma ação melhor.",
            "She should study harder for the exam.",
        ),
        (
            "Complete: Do I ___ bring my passport?",
            ["should", "have to", "mustn't"],
            1,
            "Have to em perguntas pergunta se há obrigação.",
            "Do I have to bring my passport?",
        ),
    ],
    "en-grammar-complete-b1-01": [
        (
            "Complete: I ___ visited Paris twice.",
            ["have", "has", "had", "am"],
            0,
            "Experiências de vida: have + past participle.",
            "I have visited Paris twice.",
        ),
        (
            "Complete: ___ she ever tried skydiving?",
            ["Have", "Has", "Did", "Does"],
            1,
            "Has + ever para perguntar experiência com she/he/it.",
            "Has she ever tried skydiving?",
        ),
        (
            "Complete: We haven't seen him ___ last summer.",
            ["for", "since", "from", "during"],
            1,
            "Since + ponto no tempo (last summer).",
            "We haven't seen him since last summer.",
        ),
        (
            "Complete: He has ___ finished the report.",
            ["yet", "already", "ever", "never"],
            1,
            "Already = já (afirmativas, ação concluída).",
            "He has already finished the report.",
        ),
        (
            "Complete: Have you finished ___?",
            ["already", "yet", "since", "for"],
            1,
            "Yet aparece em perguntas e negativas.",
            "Have you finished yet?",
        ),
        (
            "Complete: She has lived here ___ five years.",
            ["since", "for", "from", "during"],
            1,
            "For + duração (five years).",
            "She has lived here for five years.",
        ),
        (
            "Complete: They ___ never flown before.",
            ["have", "has", "had", "are"],
            0,
            "Never + present perfect = experiência jamais vivida.",
            "They have never flown before.",
        ),
        (
            "Complete: It's the best film I ___ ever seen.",
            ["have", "has", "had", "am"],
            0,
            "Estrutura: the + superlative + present perfect.",
            "It's the best film I have ever seen.",
        ),
    ],
    "en-grammar-complete-b1-02": [
        (
            "Complete: The teacher ___ taught us is retiring.",
            ["who", "which", "where", "whose"],
            0,
            "Who refere-se à pessoa (teacher).",
            "The teacher who taught us is retiring.",
        ),
        (
            "Complete: Here's the email ___ I mentioned.",
            ["who", "that", "where", "whose"],
            1,
            "That/which refere-se a coisas.",
            "Here's the email that I mentioned.",
        ),
        (
            "Complete: Is there a shop ___ I can buy stamps?",
            ["who", "which", "where", "whose"],
            2,
            "Where = lugar na relative clause.",
            "Is there a shop where I can buy stamps?",
        ),
        (
            "Complete: The artist ___ paintings sold out is famous.",
            ["who", "which", "where", "whose"],
            3,
            "Whose marca posse.",
            "The artist whose paintings sold out is famous.",
        ),
        (
            "Complete: People ___ exercise regularly feel better.",
            ["which", "who", "where", "whom"],
            1,
            "Who + verbo: pessoa como sujeito.",
            "People who exercise regularly feel better.",
        ),
        (
            "Complete: The reason ___ she left is unclear.",
            ["who", "which", "why", "whose"],
            2,
            "Why pode introduzir relative clause de motivo.",
            "The reason why she left is unclear.",
        ),
        (
            "Complete: The hotel ___ we stayed was excellent.",
            ["who", "which", "where", "whose"],
            2,
            "Where para lugares (hotel).",
            "The hotel where we stayed was excellent.",
        ),
        (
            "Complete: She's the colleague with ___ I share an office.",
            ["who", "which", "whom", "whose"],
            2,
            "Após preposição, whom é a forma formal de objeto.",
            "She's the colleague with whom I share an office.",
        ),
    ],
    "en-grammar-complete-b1-03": [
        (
            "Complete: English ___ in many countries.",
            ["speaks", "is spoken", "spoke", "is speaking"],
            1,
            "Voz passiva: be + past participle.",
            "English is spoken in many countries.",
        ),
        (
            "Complete: The window ___ by the storm.",
            ["broke", "was broken", "is breaking", "has broke"],
            1,
            "Passiva no passado: was/were + past participle.",
            "The window was broken by the storm.",
        ),
        (
            "Complete: The results ___ tomorrow.",
            ["will announce", "will be announced", "are announcing", "announce"],
            1,
            "Passiva futura: will be + past participle.",
            "The results will be announced tomorrow.",
        ),
        (
            "Complete: A new bridge ___ in our city.",
            ["is building", "is being built", "builds", "has build"],
            1,
            "Passiva contínua: is being + past participle.",
            "A new bridge is being built in our city.",
        ),
        (
            "Complete: The letters ___ already been sent.",
            ["have", "has", "are", "were"],
            0,
            "Present perfect passive: have/has been + particípio.",
            "The letters have already been sent.",
        ),
        (
            "Complete: This room ___ cleaned every day.",
            ["is", "was", "has", "will"],
            0,
            "Rotina passiva: is + past participle.",
            "This room is cleaned every day.",
        ),
        (
            "Complete: The thief ___ by the police last night.",
            ["caught", "was caught", "is caught", "has catch"],
            1,
            "Ação passada completa na passiva: was caught.",
            "The thief was caught by the police last night.",
        ),
        (
            "Complete: Dinner ___ when we arrived.",
            ["is serving", "was being served", "served", "has served"],
            1,
            "Passiva contínua no passado: was being + particípio.",
            "Dinner was being served when we arrived.",
        ),
    ],
    "en-grammar-complete-b1-04": [
        (
            "Complete: Tom said he ___ busy.",
            ["is", "was", "were", "be"],
            1,
            "Present → past no reported speech.",
            "Tom said he was busy.",
        ),
        (
            "Complete: Anna told us she ___ call later.",
            ["will", "would", "can", "may"],
            1,
            "Will → would no discurso indireto.",
            "Anna told us she would call later.",
        ),
        (
            "Complete: They asked what time the train ___.",
            ["leaves", "left", "leave", "leaving"],
            1,
            "Pergunta indireta: backshift do tempo verbal.",
            "They asked what time the train left.",
        ),
        (
            "Complete: She said she ___ finished her work.",
            ["has", "have", "had", "was"],
            2,
            "Present perfect → past perfect.",
            "She said she had finished her work.",
        ),
        (
            "Complete: He asked ___ I liked coffee.",
            ["that", "if", "what", "how"],
            1,
            "Yes/no question indireta: if/whether.",
            "He asked if I liked coffee.",
        ),
        (
            "Complete: \"Stay here,\" she said. → She told me ___ there.",
            ["stay", "to stay", "staying", "stayed"],
            1,
            "Ordens: tell + objeto + to-infinitive.",
            "She told me to stay there.",
        ),
        (
            "Complete: He said he ___ go to the party.",
            ["can", "could", "may", "must"],
            1,
            "Can → could no reported speech.",
            "He said he could go to the party.",
        ),
        (
            "Complete: She asked me where I ___.",
            ["live", "lived", "living", "lives"],
            1,
            "Wh-question indireta: ordem SVO + backshift.",
            "She asked me where I lived.",
        ),
    ],
    "en-grammar-complete-b2-01": [
        (
            "Complete: You ___ have told me earlier!",
            ["should", "must", "can't", "might"],
            0,
            "Should have + particípio = crítica / arrependimento.",
            "You should have told me earlier!",
        ),
        (
            "Complete: She ___ have arrived by now — her flight landed an hour ago.",
            ["can't", "must", "shouldn't", "needn't"],
            1,
            "Must have = conclusão lógica sobre o passado.",
            "She must have arrived by now — her flight landed an hour ago.",
        ),
        (
            "Complete: He ___ have stolen the money; he was with me all day.",
            ["must", "can't", "should", "ought to"],
            1,
            "Can't have = impossibilidade lógica no passado.",
            "He can't have stolen the money; he was with me all day.",
        ),
        (
            "Complete: They ___ have forgotten the meeting; they're usually punctual.",
            ["must", "might", "can't", "should"],
            1,
            "Might have = possibilidade no passado.",
            "They might have forgotten the meeting; they're usually punctual.",
        ),
        (
            "Complete: You ___ have bought more food; there's plenty left.",
            ["needn't", "must", "can't", "should"],
            0,
            "Needn't have = fez algo desnecessário.",
            "You needn't have bought more food; there's plenty left.",
        ),
        (
            "Complete: She ___ have left already — her coat is gone.",
            ["can't", "must", "shouldn't", "needn't"],
            1,
            "Must have + evidência presente sobre ação passada.",
            "She must have left already — her coat is gone.",
        ),
        (
            "Complete: I ___ have studied harder for that exam.",
            ["should", "must", "can't", "may"],
            0,
            "Should have expressa arrependimento.",
            "I should have studied harder for that exam.",
        ),
        (
            "Complete: He ___ have taken a different route; that's why he's late.",
            ["can't", "could", "mustn't", "needn't"],
            1,
            "Could have = possibilidade alternativa no passado.",
            "He could have taken a different route; that's why he's late.",
        ),
        (
            "Complete: You ___ have seen her somewhere before.",
            ["may", "mustn't", "needn't", "shouldn't"],
            0,
            "May have = possibilidade incerta no passado.",
            "You may have seen her somewhere before.",
        ),
        (
            "Complete: They ___ have known about the changes; nobody told them.",
            ["must", "can't", "should", "ought"],
            1,
            "Can't have = certeza de que algo não aconteceu.",
            "They can't have known about the changes; nobody told them.",
        ),
    ],
    "en-grammar-complete-b2-02": [
        (
            "Complete: If I had saved more money, I ___ be so worried now.",
            ["won't", "wouldn't", "hadn't", "didn't"],
            1,
            "Mixed: passado hipotético → resultado presente (wouldn't).",
            "If I had saved more money, I wouldn't be so worried now.",
        ),
        (
            "Complete: If she ___ more confident, she would have applied for the job.",
            ["is", "was", "were", "had been"],
            2,
            "Mixed: condição presente irreal + resultado passado.",
            "If she were more confident, she would have applied for the job.",
        ),
        (
            "Complete: If he hadn't missed the train, he ___ here by now.",
            ["is", "would be", "will be", "was"],
            1,
            "Causa passada → estado presente: would be.",
            "If he hadn't missed the train, he would be here by now.",
        ),
        (
            "Complete: If I ___ speak French, I would have taken that role.",
            ["can", "could", "will", "would"],
            1,
            "Habilidade presente hipotética + resultado passado.",
            "If I could speak French, I would have taken that role.",
        ),
        (
            "Complete: She wouldn't be fluent if she ___ abroad as a child.",
            ["didn't live", "hadn't lived", "hasn't lived", "wouldn't live"],
            1,
            "Resultado presente + condição no passado (hadn't lived).",
            "She wouldn't be fluent if she hadn't lived abroad as a child.",
        ),
        (
            "Complete: If they were more organised, they ___ finished on time.",
            ["will have", "would have", "had", "have"],
            1,
            "Condição presente irreal + resultado passado: would have.",
            "If they were more organised, they would have finished on time.",
        ),
        (
            "Complete: If you ___ listened, you wouldn't be confused now.",
            ["have", "had", "would have", "did"],
            1,
            "If + past perfect → wouldn't + infinitive (mixed).",
            "If you had listened, you wouldn't be confused now.",
        ),
        (
            "Complete: He would still have his job if he ___ so rude.",
            ["isn't", "weren't", "hadn't been", "hasn't been"],
            2,
            "Estado presente + causa passada: hadn't been.",
            "He would still have his job if he hadn't been so rude.",
        ),
        (
            "Complete: If I ___ you earlier, you wouldn't be in this mess.",
            ["warn", "warned", "had warned", "have warned"],
            2,
            "Aviso hipotético no passado → situação presente.",
            "If I had warned you earlier, you wouldn't be in this mess.",
        ),
        (
            "Complete: They ___ richer now if they had invested wisely.",
            ["are", "were", "would be", "will be"],
            2,
            "Investimento passado hipotético → riqueza presente.",
            "They would be richer now if they had invested wisely.",
        ),
    ],
    "en-grammar-complete-b2-03": [
        (
            "Complete: ___ had we left than it started to rain.",
            ["No sooner", "Hardly", "Not only", "Seldom"],
            0,
            "No sooner ... than: inversão após advérbio negativo.",
            "No sooner had we left than it started to rain.",
        ),
        (
            "Complete: ___ did she realise her mistake.",
            ["Only then", "Only when", "Not until later", "Only after"],
            0,
            "Only then + auxiliar + sujeito (inversão).",
            "Only then did she realise her mistake.",
        ),
        (
            "Complete: ___ have I seen such courage.",
            ["Rarely", "Always", "Often", "Sometimes"],
            0,
            "Rarely no início exige inversão auxiliar-sujeito.",
            "Rarely have I seen such courage.",
        ),
        (
            "Complete: Not only ___ late, but he also forgot the documents.",
            ["he was", "was he", "he is", "is he"],
            1,
            "Not only + inversão no primeiro elemento.",
            "Not only was he late, but he also forgot the documents.",
        ),
        (
            "Complete: Under no circumstances ___ you open that door.",
            ["should", "you should", "you must", "must you"],
            0,
            "Under no circumstances + modal + sujeito (inversão).",
            "Under no circumstances should you open that door.",
        ),
        (
            "Complete: Little ___ they know about the consequences.",
            ["do", "did", "have", "are"],
            1,
            "Little + did + sujeito + verbo base.",
            "Little did they know about the consequences.",
        ),
        (
            "Complete: So rare ___ the species that few have seen it.",
            ["is", "are", "was", "were"],
            0,
            "So + adjective + be + sujeito (inversão).",
            "So rare is the species that few have seen it.",
        ),
        (
            "Complete: Nowhere ___ a better view of the city.",
            ["you will find", "will you find", "you find", "find you"],
            1,
            "Nowhere + will + sujeito + verbo.",
            "Nowhere will you find a better view of the city.",
        ),
        (
            "Complete: Hardly ___ the speech begun when the lights failed.",
            ["had", "has", "did", "was"],
            0,
            "Hardly + had + sujeito + past participle.",
            "Hardly had the speech begun when the lights failed.",
        ),
        (
            "Complete: Not until midnight ___ the truth.",
            ["they discovered", "did they discover", "they did discover", "discovered they"],
            1,
            "Not until + tempo + auxiliar + sujeito + verbo.",
            "Not until midnight did they discover the truth.",
        ),
    ],
    "en-grammar-complete-b2-04": [
        (
            "Complete: ___ the email, she left the office.",
            ["Sending", "Having sent", "Sent", "To send"],
            1,
            "Having + past participle = ação anterior concluída.",
            "Having sent the email, she left the office.",
        ),
        (
            "Complete: The man ___ by the window is my uncle.",
            ["standing", "stood", "stands", "to stand"],
            0,
            "Participle clause reduz relative: who is standing → standing.",
            "The man standing by the window is my uncle.",
        ),
        (
            "Complete: ___ in Italy, he speaks fluent Italian.",
            ["Born", "Bearing", "To bear", "Bore"],
            0,
            "Past participle no início = sendo/nascido (passive sense).",
            "Born in Italy, he speaks fluent Italian.",
        ),
        (
            "Complete: ___ carefully, the package arrived intact.",
            ["Packing", "Packed", "To pack", "Pack"],
            1,
            "Packed = having been packed (passiva reduzida).",
            "Packed carefully, the package arrived intact.",
        ),
        (
            "Complete: ___ the news, everyone started celebrating.",
            ["Hearing", "Heard", "To hear", "Hear"],
            0,
            "Present participle: Hearing = When they heard.",
            "Hearing the news, everyone started celebrating.",
        ),
        (
            "Complete: There were dozens of letters ___ on the desk.",
            ["lying", "lain", "lay", "lied"],
            0,
            "Lying (present participle) descreve estado/posição.",
            "There were dozens of letters lying on the desk.",
        ),
        (
            "Complete: ___ for hours, they finally found a solution.",
            ["Discussing", "Having discussed", "Discussed", "To discuss"],
            1,
            "Having discussed marca ação anterior à principal.",
            "Having discussed for hours, they finally found a solution.",
        ),
        (
            "Complete: The proposal ___ by the board was rejected.",
            ["considering", "considered", "to consider", "considers"],
            1,
            "Past participle = which was considered.",
            "The proposal considered by the board was rejected.",
        ),
        (
            "Complete: ___ exhausted, she went straight to bed.",
            ["Feeling", "Felt", "To feel", "Feels"],
            0,
            "Feeling + adj = As she felt...",
            "Feeling exhausted, she went straight to bed.",
        ),
        (
            "Complete: ___ all options, we chose the safest one.",
            ["Weighing", "Having weighed", "Weighed", "To weigh"],
            1,
            "Having weighed = After we had weighed.",
            "Having weighed all options, we chose the safest one.",
        ),
    ],
    "en-grammar-complete-b2-05": [
        (
            "Complete: The findings ___ suggest a correlation, not causation.",
            ["appear to", "definitely", "absolutely", "certainly"],
            0,
            "Appear to é hedging: suaviza a afirmação.",
            "The findings appear to suggest a correlation, not causation.",
        ),
        (
            "Complete: It ___ be argued that the sample was too small.",
            ["can", "must", "will", "shall"],
            0,
            "It can be argued that... = linguagem acadêmica cautelosa.",
            "It can be argued that the sample was too small.",
        ),
        (
            "Complete: The results ___ indicate a slight improvement.",
            ["seem to", "prove", "confirm totally", "show beyond doubt"],
            0,
            "Seem to reduz a força da afirmação (hedging).",
            "The results seem to indicate a slight improvement.",
        ),
        (
            "Complete: ___ evidence supports this hypothesis.",
            ["Limited", "Absolute", "Irrefutable", "Conclusive"],
            0,
            "Limited evidence = hedge quantificando a força da prova.",
            "Limited evidence supports this hypothesis.",
        ),
        (
            "Complete: This ___ be due to measurement error.",
            ["could", "must", "will", "shall"],
            0,
            "Could be due to = possibilidade, não certeza.",
            "This could be due to measurement error.",
        ),
        (
            "Complete: The authors ___ that further research is needed.",
            ["tend to suggest", "insist", "demand", "prove"],
            0,
            "Tend to suggest é formulação acadêmica hedged.",
            "The authors tend to suggest that further research is needed.",
        ),
        (
            "Complete: ___ speaking, the policy was only partially successful.",
            ["Broadly", "Totally", "Utterly", "Completely"],
            0,
            "Broadly speaking = generalização cautelosa.",
            "Broadly speaking, the policy was only partially successful.",
        ),
        (
            "Complete: There is ___ to believe the trend will continue.",
            ["reason", "proof", "certainty", "guarantee"],
            0,
            "There is reason to believe = hedge acadêmico clássico.",
            "There is reason to believe the trend will continue.",
        ),
        (
            "Complete: The data ___ support a strong causal claim.",
            ["do not fully", "absolutely", "undeniably", "conclusively"],
            0,
            "Do not fully = negação parcial (hedging).",
            "The data do not fully support a strong causal claim.",
        ),
        (
            "Complete: One ___ interpretation is that demand has shifted.",
            ["possible", "certain", "inevitable", "proven"],
            0,
            "One possible interpretation = apresenta leitura sem dogmatismo.",
            "One possible interpretation is that demand has shifted.",
        ),
    ],
    "en-grammar-complete-b2-06": [
        (
            "Complete: The committee will ___ a decision next week.",
            ["reach", "do", "make up", "get"],
            0,
            "Collocation formal: reach a decision.",
            "The committee will reach a decision next week.",
        ),
        (
            "Complete: We need to ___ further research on this topic.",
            ["conduct", "make", "do up", "take"],
            0,
            "Conduct research = collocation acadêmica/formal.",
            "We need to conduct further research on this topic.",
        ),
        (
            "Complete: The report ___ several key recommendations.",
            ["puts forward", "puts off", "puts up", "puts down"],
            0,
            "Put forward = apresentar formalmente (proposta/ideia).",
            "The report puts forward several key recommendations.",
        ),
        (
            "Complete: The government ___ new legislation last month.",
            ["introduced", "made", "did", "took"],
            0,
            "Introduce legislation = collocation formal.",
            "The government introduced new legislation last month.",
        ),
        (
            "Complete: Please ___ the attached document carefully.",
            ["examine", "look", "see", "watch"],
            0,
            "Examine = verbo formal para análise detalhada.",
            "Please examine the attached document carefully.",
        ),
        (
            "Complete: The two parties ___ an agreement after negotiations.",
            ["reached", "did", "made up", "got"],
            0,
            "Reach an agreement = collocation formal.",
            "The two parties reached an agreement after negotiations.",
        ),
        (
            "Complete: Scholars have ___ this issue extensively.",
            ["addressed", "talked", "said", "spoke"],
            0,
            "Address an issue = tratar de um tema (formal).",
            "Scholars have addressed this issue extensively.",
        ),
        (
            "Complete: The findings ___ previous studies in the field.",
            ["corroborate", "like", "agree", "match up"],
            0,
            "Corroborate = confirmar com evidência (registro acadêmico).",
            "The findings corroborate previous studies in the field.",
        ),
        (
            "Complete: We ___ a survey among 500 participants.",
            ["administered", "did", "made", "took"],
            0,
            "Administer a survey = linguagem de pesquisa formal.",
            "We administered a survey among 500 participants.",
        ),
        (
            "Complete: The board ___ responsibility for the oversight.",
            ["assumed", "took on up", "got", "did"],
            0,
            "Assume responsibility = collocation formal.",
            "The board assumed responsibility for the oversight.",
        ),
    ],
}


def get_banks():
    return BANKS
