"""Spanish grammar cloze exercise banks keyed by topic_id."""

BANKS = {
    "es-grammar-A1-1": [  # Ser y estar (5, 3 opts)
        (
            'Complete: Ella ___ médica.',
            ['es', 'está', 'soy'],
            0,
            "Profissão usa 'ser'.",
            'Ella es médica.',
        ),
        (
            'Complete: El café ___ frío.',
            ['es', 'está', 'somos'],
            1,
            "Estado temporário usa 'estar'.",
            'El café está frío.',
        ),
        (
            'Complete: Nosotros ___ de Brasil.',
            ['estamos', 'son', 'somos'],
            2,
            "Origem usa 'ser'.",
            'Nosotros somos de Brasil.',
        ),
        (
            'Complete: ¿Dónde ___ el baño?',
            ['está', 'es', 'soy'],
            0,
            "Localização usa 'estar'.",
            '¿Dónde está el baño?',
        ),
        (
            'Complete: Hoy yo ___ cansado.',
            ['soy', 'estoy', 'es'],
            1,
            "Estado físico/emocional usa 'estar'.",
            'Hoy yo estoy cansado.',
        ),
    ],
    "es-grammar-A1-2": [  # Género y número (5, 3 opts)
        (
            'Complete: La mesa es ___.',
            ['blanco', 'blancos', 'blanca'],
            2,
            "Adjetivo concorda em gênero com 'mesa' (feminino).",
            'La mesa es blanca.',
        ),
        (
            'Complete: Los libros son ___.',
            ['interesantes', 'interesante', 'interesanta'],
            0,
            'Plural: adjetivo termina em -s/-es.',
            'Los libros son interesantes.',
        ),
        (
            'Complete: ___ chica es alta.',
            ['El', 'La', 'Los'],
            1,
            "'Chica' é feminino singular → 'la'.",
            'La chica es alta.',
        ),
        (
            'Complete: Tengo dos ___.',
            ['amigo', 'amiga', 'amigos'],
            2,
            "Número: dois → plural 'amigos'.",
            'Tengo dos amigos.',
        ),
        (
            'Complete: Una ___ roja.',
            ['casa', 'casas', 'caso'],
            0,
            "'Una' pede substantivo feminino singular.",
            'Una casa roja.',
        ),
    ],
    "es-grammar-A2-3": [  # Presente regular (6, 3 opts)
        (
            'Complete: Yo ___ español todos los días.',
            ['estudias', 'estudia', 'estudio'],
            2,
            "Presente de 'estudiar': yo estudio.",
            'Yo estudio español todos los días.',
        ),
        (
            'Complete: Tú ___ en una oficina.',
            ['trabajas', 'trabajo', 'trabaja'],
            0,
            "Presente de 'trabajar': tú trabajas.",
            'Tú trabajas en una oficina.',
        ),
        (
            'Complete: Ella ___ mucho.',
            ['como', 'come', 'comes'],
            1,
            "Presente de 'comer': ella come.",
            'Ella come mucho.',
        ),
        (
            'Complete: Nosotros ___ la tele.',
            ['vivimos', 'viven', 'vemos'],
            2,
            "Presente de 'ver' (irregular comum): nosotros vemos. Aqui o foco é a forma de 1ª plural.",
            'Nosotros vemos la tele.',
        ),
        (
            'Complete: Vosotros ___ música.',
            ['escucháis', 'escuchan', 'escucho'],
            0,
            "Presente de 'escuchar': vosotros escucháis.",
            'Vosotros escucháis música.',
        ),
        (
            'Complete: Ellos ___ en Madrid.',
            ['vivo', 'viven', 'vives'],
            1,
            "Presente de 'vivir': ellos viven.",
            'Ellos viven en Madrid.',
        ),
    ],
    "es-grammar-A2-4": [  # Pretérito indefinido (6, 3 opts)
        (
            'Complete: Ayer yo ___ al cine.',
            ['iba', 'fui', 'voy'],
            1,
            "Pretérito indefinido de 'ir': yo fui.",
            'Ayer yo fui al cine.',
        ),
        (
            'Complete: Ella ___ una carta.',
            ['escribe', 'escribía', 'escribió'],
            2,
            'Ação pontual no passado: escribió.',
            'Ella escribió una carta.',
        ),
        (
            'Complete: Nosotros ___ pizza anoche.',
            ['comimos', 'comemos', 'comíamos'],
            0,
            "Indefinido de 'comer': nosotros comimos.",
            'Nosotros comimos pizza anoche.',
        ),
        (
            'Complete: ¿Qué ___ tú el sábado?',
            ['hacías', 'hiciste', 'haces'],
            1,
            "Indefinido de 'hacer': tú hiciste.",
            '¿Qué hiciste tú el sábado?',
        ),
        (
            'Complete: Ellos ___ a las ocho.',
            ['salen', 'salían', 'salieron'],
            2,
            "Indefinido de 'salir': ellos salieron.",
            'Ellos salieron a las ocho.',
        ),
        (
            'Complete: Yo ___ mucho en la fiesta.',
            ['bailé', 'bailo', 'bailaba'],
            0,
            'Indefinido regular -ar: yo bailé.',
            'Yo bailé mucho en la fiesta.',
        ),
    ],
    "es-grammar-A2-5": [  # Futuro y planes (6, 3 opts)
        (
            'Complete: Mañana ___ al médico.',
            ['fui', 'iba', 'voy a ir'],
            2,
            "'Ir a + infinitivo' expressa planos próximos.",
            'Mañana voy a ir al médico.',
        ),
        (
            'Complete: El tren ___ a las cinco.',
            ['llegará', 'llegó', 'llegaba'],
            0,
            'Futuro simples: llegará.',
            'El tren llegará a las cinco.',
        ),
        (
            'Complete: Nosotros ___ estudiar esta noche.',
            ['fuimos a', 'vamos a', 'íbamos a'],
            1,
            'Plano: vamos a + infinitivo.',
            'Nosotros vamos a estudiar esta noche.',
        ),
        (
            'Complete: ¿Qué ___ hacer el domingo?',
            ['fuiste a', 'ibas a', 'vas a'],
            2,
            "Pergunta sobre planos futuros com 'ir a'.",
            '¿Qué vas a hacer el domingo?',
        ),
        (
            'Complete: Ellos ___ en julio.',
            ['viajarán', 'viajaron', 'viajaban'],
            0,
            'Futuro simples: viajarán.',
            'Ellos viajarán en julio.',
        ),
        (
            'Complete: Yo ___ la cena esta noche.',
            ['preparé', 'prepararé', 'preparaba'],
            1,
            'Futuro simples: prepararé.',
            'Yo prepararé la cena esta noche.',
        ),
    ],
    "es-grammar-B1-6": [  # Pretérito perfecto (8, 4 opts)
        (
            'Complete: Hoy ___ mucho.',
            ['trabajé', 'trabajaba', 'trabajo', 'he trabajado'],
            3,
            "Perfeito com 'hoy': he + participio.",
            'Hoy he trabajado mucho.',
        ),
        (
            'Complete: ¿Ya ___ el informe?',
            ['has terminado', 'terminaste', 'terminabas', 'terminas'],
            0,
            "'Ya' costuma ir com pretérito perfecto.",
            '¿Ya has terminado el informe?',
        ),
        (
            'Complete: Nunca ___ a Japón.',
            ['viajé', 'he viajado', 'viajaba', 'viajo'],
            1,
            'Experiência de vida: nunca + perfecto.',
            'Nunca he viajado a Japón.',
        ),
        (
            'Complete: Este mes ___ tres libros.',
            ['leímos', 'leíamos', 'hemos leído', 'leemos'],
            2,
            "Período ainda aberto ('este mes') → perfecto.",
            'Este mes hemos leído tres libros.',
        ),
        (
            'Complete: Ella ___ la puerta.',
            ['abrió', 'abría', 'abre', 'ha abierto'],
            3,
            'Participio irregular: abierto.',
            'Ella ha abierto la puerta.',
        ),
        (
            'Complete: Todavía no ___.',
            ['he comido', 'comí', 'comía', 'como'],
            0,
            "'Todavía no' + perfecto: ação ainda não concluída.",
            'Todavía no he comido.',
        ),
        (
            'Complete: ¿Alguna vez ___ sushi?',
            ['probaste', 'has probado', 'probabas', 'pruebas'],
            1,
            'Experiência: alguna vez + perfecto.',
            '¿Alguna vez has probado sushi?',
        ),
        (
            'Complete: Ellos ___ la casa.',
            ['vendieron', 'vendían', 'han vendido', 'venden'],
            2,
            'Resultado recente/relevante: han vendido.',
            'Ellos han vendido la casa.',
        ),
    ],
    "es-grammar-B1-7": [  # Pronombres de objeto (8, 4 opts)
        (
            'Complete: ¿El libro? ___ leo todos los días.',
            ['Le', 'Lo', 'La', 'Les'],
            1,
            "OD masculino singular → 'lo'.",
            '¿El libro? Lo leo todos los días.',
        ),
        (
            'Complete: Voy a ___ una carta.',
            ['escribirlo', 'escribirla', 'escribirle', 'escribirles'],
            2,
            "OI: 'le' (a él/ella) → escribirle.",
            'Voy a escribirle una carta.',
        ),
        (
            'Complete: ¿Las llaves? No ___ encuentro.',
            ['los', 'les', 'la', 'las'],
            3,
            "OD feminino plural → 'las'.",
            '¿Las llaves? No las encuentro.',
        ),
        (
            'Complete: ¿El secreto? ___ dije a Ana.',
            ['Se lo', 'Le lo', 'Lo se', 'Se le'],
            0,
            "OI 'le' + OD 'lo' vira 'se lo'.",
            '¿El secreto? Se lo dije a Ana.',
        ),
        (
            'Complete: ¿A María? ___ di el regalo.',
            ['La', 'Le', 'Lo', 'Les'],
            1,
            'OI: a María → le.',
            '¿A María? Le di el regalo.',
        ),
        (
            'Complete: No ___ veo (a ellos).',
            ['les', 'las', 'los', 'lo'],
            2,
            "OD masculino plural → 'los'.",
            'No los veo.',
        ),
        (
            'Complete: ¿Puedes ___ el bolígrafo?',
            ['pasar me', 'me pasar', 'pasarlos', 'pasarme'],
            3,
            'Clítico no infinitivo: pasarme.',
            '¿Puedes pasarme el bolígrafo?',
        ),
        (
            'Complete: Se ___ dije ayer.',
            ['lo', 'le', 'la', 'les'],
            0,
            'Combinação se + lo: se lo dije.',
            'Se lo dije ayer.',
        ),
    ],
    "es-grammar-B1-8": [  # Subjuntivo presente (8, 4 opts)
        (
            'Complete: Quiero que ___ temprano.',
            ['vengas', 'vienes', 'viniste', 'vendrás'],
            0,
            "Após 'quiero que' → subjuntivo: vengas.",
            'Quiero que vengas temprano.',
        ),
        (
            'Complete: Es importante que ___ español.',
            ['estudias', 'estudies', 'estudiaste', 'estudiarás'],
            1,
            'Valoração impersonal + que → subjuntivo.',
            'Es importante que estudies español.',
        ),
        (
            'Complete: No creo que ___ razón.',
            ['tiene', 'tuvo', 'tenga', 'tendrá'],
            2,
            'Dúvida/negação de opinião → subjuntivo.',
            'No creo que tenga razón.',
        ),
        (
            'Complete: Ojalá ___ buen tiempo.',
            ['hace', 'hizo', 'hará', 'haga'],
            3,
            "'Ojalá' pede subjuntivo: haga.",
            'Ojalá haga buen tiempo.',
        ),
        (
            'Complete: Te recomiendo que ___ al médico.',
            ['vayas', 'vas', 'fuiste', 'irás'],
            0,
            'Recomendação + que → subjuntivo: vayas.',
            'Te recomiendo que vayas al médico.',
        ),
        (
            'Complete: Cuando ___ , avísame.',
            ['llegas', 'llegues', 'llegaste', 'llegarás'],
            1,
            "Futuro temporal com 'cuando' → subjuntivo.",
            'Cuando llegues, avísame.',
        ),
        (
            'Complete: Busco un piso que ___ balcón.',
            ['tiene', 'tuvo', 'tenga', 'tendrá'],
            2,
            'Antecedente indefinido → subjuntivo.',
            'Busco un piso que tenga balcón.',
        ),
        (
            'Complete: Espero que ___ bien.',
            ['estás', 'estuviste', 'estarás', 'estés'],
            3,
            "'Espero que' → subjuntivo: estés.",
            'Espero que estés bien.',
        ),
    ],
    "es-grammar-B2-9": [  # Condicionales (10, 4 opts)
        (
            'Complete: Si llueve, ___ a casa.',
            ['me quedo', 'me quedaría', 'me hubiera quedado', 'me quedé'],
            0,
            'Condicional tipo 1 (real): presente + presente/futuro.',
            'Si llueve, me quedo a casa.',
        ),
        (
            'Complete: Si tuviera tiempo, ___ más.',
            ['viajo', 'viajaría', 'viajara', 'viajé'],
            1,
            'Tipo 2 (hipótese presente): imperfecto de subjuntivo + condicional.',
            'Si tuviera tiempo, viajaría más.',
        ),
        (
            'Complete: Si lo ___ , te lo habría dicho.',
            ['sé', 'sabría', 'hubiera sabido', 'supe'],
            2,
            'Tipo 3 (passado irreal): hubiera + condicional compuesto.',
            'Si lo hubiera sabido, te lo habría dicho.',
        ),
        (
            'Complete: Te ayudaría si me lo ___.',
            ['pides', 'pedirías', 'pedirás', 'pidieras'],
            3,
            'Tipo 2: si + imperfecto de subjuntivo.',
            'Te ayudaría si me lo pidieras.',
        ),
        (
            'Complete: Si no ___ , no apruebas.',
            ['estudias', 'estudiaras', 'hubieras estudiado', 'estudiarías'],
            0,
            'Tipo 1: condição real no presente.',
            'Si no estudias, no apruebas.',
        ),
        (
            'Complete: ¿Qué ___ si ganaras la lotería?',
            ['haces', 'harías', 'hiciste', 'habrías hecho'],
            1,
            'Tipo 2: condicional simples na principal.',
            '¿Qué harías si ganaras la lotería?',
        ),
        (
            'Complete: Si hubiéramos salido antes, no ___ el tren.',
            ['perdemos', 'perderíamos', 'habríamos perdido', 'perdimos'],
            2,
            'Tipo 3: condicional composto na principal.',
            'Si hubiéramos salido antes, no habríamos perdido el tren.',
        ),
        (
            'Complete: Como si ___ un niño.',
            ['es', 'sería', 'fue', 'fuera'],
            3,
            "'Como si' → imperfecto de subjuntivo.",
            'Habla como si fuera un niño.',
        ),
        (
            'Complete: De ___ sabido, no habría venido.',
            ['haber', 'haberlo', 'habiendo', 'haberse'],
            0,
            "Estrutura 'de + infinitivo composto' = se hubiera...",
            'De haberlo sabido, no habría venido.',
        ),
        (
            'Complete: Aunque ___ rico, seguiría trabajando.',
            ['soy', 'fuera', 'sería', 'fui'],
            1,
            'Concessiva hipotética: aunque + imperfecto de subjuntivo.',
            'Aunque fuera rico, seguiría trabajando.',
        ),
    ],
    "es-grammar-B2-10": [  # Discurso referido y matiz (10, 4 opts)
        (
            'Complete: Dijo que ___ cansado.',
            ['está', 'estaba', 'esté', 'estuvo'],
            1,
            'Discurso indireto: presente → imperfecto.',
            'Dijo que estaba cansado.',
        ),
        (
            'Complete: Me preguntó si ___ ir.',
            ['quiero', 'quiera', 'quería', 'quise'],
            2,
            'Pergunta indireta: presente → imperfecto.',
            'Me preguntó si quería ir.',
        ),
        (
            'Complete: Afirmó que ___ al día siguiente.',
            ['viene', 'venga', 'vino', 'vendría'],
            3,
            'Futuro no discurso → condicional.',
            'Afirmó que vendría al día siguiente.',
        ),
        (
            'Complete: Nos dijo que ___ estudiado.',
            ['había', 'ha', 'haya', 'hubo'],
            0,
            'Pretérito perfecto → pluscuamperfecto no discurso.',
            'Nos dijo que había estudiado.',
        ),
        (
            'Complete: Ordenó que ___ inmediatamente.',
            ['salimos', 'saliéramos', 'salgamos', 'saldríamos'],
            1,
            'Ordem no passado → imperfecto de subjuntivo.',
            'Ordenó que saliéramos inmediatamente.',
        ),
        (
            'Complete: Sugirió que ___ más temprano.',
            ['llegamos', 'lleguemos', 'llegáramos', 'llegaríamos'],
            2,
            'Sugestão referida no passado → imperfecto de subjuntivo.',
            'Sugirió que llegáramos más temprano.',
        ),
        (
            'Complete: Dijo: «Vendré». → Dijo que ___.',
            ['viene', 'venga', 'vino', 'vendría'],
            3,
            'Futuro → condicional no discurso indireto.',
            'Dijo que vendría.',
        ),
        (
            'Complete: Negó ___ conocido el asunto.',
            ['haber', 'haberlo', 'habiendo', 'haberse'],
            0,
            "Após 'negar': infinitivo composto (haber conocido).",
            'Negó haber conocido el asunto.',
        ),
        (
            'Complete: Según él, el proyecto ___ un éxito.',
            ['sea', 'fue', 'sería', 'es'],
            1,
            'Matiz de atribuição: segundo ele, foi um sucesso.',
            'Según él, el proyecto fue un éxito.',
        ),
        (
            'Complete: Parece que ___ problema.',
            ['haya', 'hubo', 'hay', 'habría'],
            2,
            "Com 'parece que' afirmativo → indicativo.",
            'Parece que hay problema.',
        ),
    ],
    "es-grammar-extra-01": [  # Preposiciones a/de/en/con (A1, 5)
        (
            'Complete: Voy ___ Madrid.',
            ['de', 'en', 'a'],
            2,
            "Movimento para um lugar: 'a'.",
            'Voy a Madrid.',
        ),
        (
            'Complete: Soy ___ Argentina.',
            ['de', 'a', 'en'],
            0,
            "Origem: 'de'.",
            'Soy de Argentina.',
        ),
        (
            'Complete: Estoy ___ casa.',
            ['a', 'en', 'de'],
            1,
            "Localização: 'en'.",
            'Estoy en casa.',
        ),
        (
            'Complete: Hablo ___ mi amigo.',
            ['a', 'de', 'con'],
            2,
            "Companhia/comunicação: 'con'.",
            'Hablo con mi amigo.',
        ),
        (
            'Complete: El libro ___ María está aquí.',
            ['de', 'a', 'en'],
            0,
            "Posse/pertencimento: 'de'.",
            'El libro de María está aquí.',
        ),
    ],
    "es-grammar-extra-02": [  # Por e para (A2, 6)
        (
            'Complete: Este regalo es ___ ti.',
            ['por', 'de', 'para'],
            2,
            "Destinatário: 'para'.",
            'Este regalo es para ti.',
        ),
        (
            'Complete: Gracias ___ tu ayuda.',
            ['por', 'para', 'de'],
            0,
            "Causa/agradecimento: 'por'.",
            'Gracias por tu ayuda.',
        ),
        (
            'Complete: Estudio ___ ser médico.',
            ['por', 'para', 'a'],
            1,
            "Finalidade: 'para'.",
            'Estudio para ser médico.',
        ),
        (
            'Complete: Pagué veinte euros ___ el libro.',
            ['para', 'de', 'por'],
            2,
            "Preço/troca: 'por'.",
            'Pagué veinte euros por el libro.',
        ),
        (
            'Complete: Salgo ___ la mañana.',
            ['por', 'para', 'en'],
            0,
            "Partes do dia aproximadas: 'por'.",
            'Salgo por la mañana.',
        ),
        (
            'Complete: El tren ___ Barcelona sale a las seis.',
            ['por', 'para', 'a'],
            1,
            "Destino (direção): 'para'.",
            'El tren para Barcelona sale a las seis.',
        ),
    ],
    "es-grammar-extra-03": [  # Conjunciones (A2, 6)
        (
            'Complete: Quiero café ___ no té.',
            ['o', 'pero', 'y'],
            2,
            "Adição: 'y' (aqui contraste leve com 'no').",
            'Quiero café y no té.',
        ),
        (
            'Complete: ¿Café ___ té?',
            ['o', 'y', 'pero'],
            0,
            "Alternativa: 'o'.",
            '¿Café o té?',
        ),
        (
            'Complete: Es tarde, ___ voy.',
            ['y', 'pero', 'o'],
            1,
            "Oposição: 'pero'.",
            'Es tarde, pero voy.',
        ),
        (
            'Complete: No voy ___ estoy cansado.',
            ['aunque', 'si', 'porque'],
            2,
            "Causa: 'porque'.",
            'No voy porque estoy cansado.',
        ),
        (
            'Complete: ___ llueve, salimos.',
            ['Aunque', 'Porque', 'Si'],
            0,
            "Concessão: 'aunque'.",
            'Aunque llueve, salimos.',
        ),
        (
            'Complete: ___ estudias, apruebas.',
            ['Aunque', 'Si', 'Pero'],
            1,
            "Condição: 'si'.",
            'Si estudias, apruebas.',
        ),
    ],
    "es-grammar-extra-04": [  # Perífrasis verbales (B1, 8)
        (
            'Complete: Acabo de ___ a casa.',
            ['llegado', 'llegando', 'llegar', 'llegué'],
            2,
            "'Acabar de + infinitivo' = acabou de...",
            'Acabo de llegar a casa.',
        ),
        (
            'Complete: Estoy ___ un libro.',
            ['leer', 'leído', 'leí', 'leyendo'],
            3,
            "'Estar + gerundio' = ação em progresso.",
            'Estoy leyendo un libro.',
        ),
        (
            'Complete: Tengo que ___ mañana.',
            ['salir', 'salido', 'saliendo', 'salí'],
            0,
            "'Tener que + infinitivo' = obrigação.",
            'Tengo que salir mañana.',
        ),
        (
            'Complete: Voy a ___ español.',
            ['aprendido', 'aprender', 'aprendiendo', 'aprendí'],
            1,
            "'Ir a + infinitivo' = plano futuro.",
            'Voy a aprender español.',
        ),
        (
            'Complete: Llevo dos horas ___.',
            ['esperar', 'esperado', 'esperando', 'esperé'],
            2,
            "'Llevar + gerundio' = duração até agora.",
            'Llevo dos horas esperando.',
        ),
        (
            'Complete: Empezó a ___.',
            ['llovido', 'lloviendo', 'llovió', 'llover'],
            3,
            "'Empezar a + infinitivo'.",
            'Empezó a llover.',
        ),
        (
            'Complete: Dejó de ___.',
            ['fumar', 'fumado', 'fumando', 'fumó'],
            0,
            "'Dejar de + infinitivo' = parar de.",
            'Dejó de fumar.',
        ),
        (
            'Complete: Sigue ___ el mismo error.',
            ['cometer', 'cometiendo', 'cometido', 'cometió'],
            1,
            "'Seguir + gerundio' = continuar fazendo.",
            'Sigue cometiendo el mismo error.',
        ),
    ],
    "es-grammar-extra-05": [  # Usos de se (B1, 8)
        (
            'Complete: ___ habla español aquí.',
            ['Le', 'Lo', 'Se', 'Les'],
            2,
            "'Se' impessoal: se habla.",
            'Se habla español aquí.',
        ),
        (
            'Complete: La puerta ___ abrió sola.',
            ['le', 'lo', 'la', 'se'],
            3,
            "'Se' acidental/espontâneo.",
            'La puerta se abrió sola.',
        ),
        (
            'Complete: ___ me olvidó el libro.',
            ['Se', 'Le', 'Lo', 'Me'],
            0,
            "Construção 'se me olvidó'.",
            'Se me olvidó el libro.',
        ),
        (
            'Complete: Ellos ___ quieren mucho.',
            ['le', 'se', 'lo', 'les'],
            1,
            "'Se' reflexivo recíproco.",
            'Ellos se quieren mucho.',
        ),
        (
            'Complete: ¿Cómo ___ llama?',
            ['le', 'lo', 'se', 'te'],
            2,
            'Reflexivo: ¿cómo se llama?',
            '¿Cómo se llama?',
        ),
        (
            'Complete: ___ venden pisos.',
            ['Le', 'Los', 'Les', 'Se'],
            3,
            "'Se' passiva reflexa.",
            'Se venden pisos.',
        ),
        (
            'Complete: No ___ lo digas a nadie.',
            ['se', 'le', 'lo', 'les'],
            0,
            "'Le' + 'lo' → 'se lo'.",
            'No se lo digas a nadie.',
        ),
        (
            'Complete: ___ rompió el vaso.',
            ['Le', 'Se', 'Lo', 'Me'],
            1,
            "'Se' de ocorrência involuntária.",
            'Se rompió el vaso.',
        ),
    ],
    "es-grammar-extra-06": [  # Conectores discursivos (B1, 8)
        (
            'Complete: Estudié mucho; ___, aprobé.',
            ['por lo tanto', 'sin embargo', 'es decir', 'además'],
            0,
            'Consequência: por lo tanto.',
            'Estudié mucho; por lo tanto, aprobé.',
        ),
        (
            'Complete: Quería ir; ___, no pude.',
            ['además', 'sin embargo', 'es decir', 'por eso'],
            1,
            'Contraste: sin embargo.',
            'Quería ir; sin embargo, no pude.',
        ),
        (
            'Complete: Es barato y, ___, de calidad.',
            ['sin embargo', 'es decir', 'además', 'aunque'],
            2,
            'Adição: además.',
            'Es barato y, además, de calidad.',
        ),
        (
            'Complete: Llegó tarde; ___, perdió el tren.',
            ['además', 'es decir', 'aunque', 'por eso'],
            3,
            'Causa → efeito: por eso.',
            'Llegó tarde; por eso, perdió el tren.',
        ),
        (
            'Complete: Habla tres idiomas, ___ inglés, francés y alemán.',
            ['es decir', 'sin embargo', 'además', 'aunque'],
            0,
            'Reformulação: es decir.',
            'Habla tres idiomas, es decir, inglés, francés y alemán.',
        ),
        (
            'Complete: ___ lo dicho, aceptamos la propuesta.',
            ['Sin embargo', 'En vista de', 'Es decir', 'Además'],
            1,
            'Conector de conclusão a partir do dito.',
            'En vista de lo dicho, aceptamos la propuesta.',
        ),
        (
            'Complete: No solo es inteligente, ___ también simpático.',
            ['pero', 'o', 'sino', 'y'],
            2,
            "'No solo... sino también'.",
            'No solo es inteligente, sino también simpático.',
        ),
        (
            'Complete: ___, debemos actuar ya.',
            ['Sin embargo', 'Es decir', 'Además', 'En conclusión'],
            3,
            'Fechamento discursivo: en conclusión.',
            'En conclusión, debemos actuar ya.',
        ),
    ],
    "es-grammar-extra-07": [  # Subjuntivo particularidades (B2, 10)
        (
            'Complete: No hay quien ___ eso.',
            ['entiende', 'entendió', 'entenderá', 'entienda'],
            3,
            "Após 'no hay quien' → subjuntivo.",
            'No hay quien entienda eso.',
        ),
        (
            'Complete: Por mucho que ___, no lo convencerás.',
            ['insistas', 'insistes', 'insististe', 'insistirás'],
            0,
            "'Por mucho que' → subjuntivo.",
            'Por mucho que insistas, no lo convencerás.',
        ),
        (
            'Complete: Sea como ___, hay que decidir.',
            ['es', 'sea', 'sería', 'fue'],
            1,
            'Expressão lexicalizada: sea como sea.',
            'Sea como sea, hay que decidir.',
        ),
        (
            'Complete: Antes de que ___, avísame.',
            ['sales', 'saliste', 'salgas', 'saldrás'],
            2,
            "'Antes de que' → subjuntivo.",
            'Antes de que salgas, avísame.',
        ),
        (
            'Complete: Dudo que ___ verdad.',
            ['es', 'fue', 'será', 'sea'],
            3,
            'Dúvida → subjuntivo.',
            'Dudo que sea verdad.',
        ),
        (
            'Complete: No es que ___ mentira, pero...',
            ['sea', 'es', 'fue', 'sería'],
            0,
            "'No es que' → subjuntivo.",
            'No es que sea mentira, pero...',
        ),
        (
            'Complete: Como si no ___ nada.',
            ['pasa', 'pasara', 'pasó', 'pasará'],
            1,
            "'Como si' → imperfecto de subjuntivo.",
            'Actúa como si no pasara nada.',
        ),
        (
            'Complete: A menos que ___, cancelamos.',
            ['llamas', 'llamaste', 'llames', 'llamarás'],
            2,
            "'A menos que' → subjuntivo.",
            'A menos que llames, cancelamos.',
        ),
        (
            'Complete: Quien ___ que diga la verdad.',
            ['sabe', 'supo', 'sabrá', 'sepa'],
            3,
            'Relativo indefinido → subjuntivo.',
            'Quien sepa que diga la verdad.',
        ),
        (
            'Complete: Me alegra que ___ venido.',
            ['hayas', 'has', 'hubieras', 'habrás'],
            0,
            'Emoção + que → perfecto de subjuntivo.',
            'Me alegra que hayas venido.',
        ),
    ],
    "es-grammar-extra-08": [  # Expresiones idiomáticas (B2, 10)
        (
            'Complete: No ___ ni idea.',
            ['hago', 'doy', 'tengo', 'pongo'],
            2,
            "'No tener ni idea' = não ter a menor ideia.",
            'No tengo ni idea.',
        ),
        (
            'Complete: ___ la gota que colmó el vaso.',
            ['Hizo', 'Dio', 'Puso', 'Fue'],
            3,
            "'Ser la gota que colmó el vaso' = a gota d'água.",
            'Fue la gota que colmó el vaso.',
        ),
        (
            'Complete: Está ___ las nubes.',
            ['por', 'en', 'a', 'de'],
            0,
            "'Estar por las nubes' = preços altíssimos / euforia.",
            'El precio está por las nubes.',
        ),
        (
            'Complete: No ___ pelo en la lengua.',
            ['hace', 'tiene', 'da', 'pone'],
            1,
            "'No tener pelos en la lengua' = falar sem rodeios.",
            'No tiene pelos en la lengua.',
        ),
        (
            'Complete: Se ___ de la nada.',
            ['hizo', 'dio', 'apareció', 'puso'],
            2,
            "'Aparecerse de la nada' = surgir do nada.",
            'Se apareció de la nada.',
        ),
        (
            'Complete: Lo tomó ___ broma.',
            ['de', 'en', 'por', 'a'],
            3,
            "'Tomar a broma' = levar na brincadeira.",
            'Lo tomó a broma.',
        ),
        (
            'Complete: Metió la ___ otra vez.',
            ['pata', 'mano', 'cabeza', 'pierna'],
            0,
            "'Meter la pata' = meter os pés pelas mãos.",
            'Metió la pata otra vez.',
        ),
        (
            'Complete: Está ___ de trabajo.',
            ['por debajo', 'hasta arriba', 'a punto', 'en medio'],
            1,
            "'Estar hasta arriba' = estar saturado.",
            'Está hasta arriba de trabajo.',
        ),
        (
            'Complete: No ___ ni frío ni calor.',
            ['me hace', 'me pone', 'me da', 'me deja'],
            2,
            "'No me da ni frío ni calor' = é indiferente.",
            'No me da ni frío ni calor.',
        ),
        (
            'Complete: Tiró la ___ por la ventana.',
            ['toalla', 'pelota', 'llave', 'casa'],
            3,
            "'Tirar la casa por la ventana' = gastar sem limites.",
            'Tiró la casa por la ventana.',
        ),
    ],
    "es-grammar-complete-a1-01": [  # Pronombres personales (5)
        (
            'Complete: ___ soy Ana.',
            ['Yo', 'Tú', 'Él'],
            0,
            '1ª pessoa singular: yo.',
            'Yo soy Ana.',
        ),
        (
            'Complete: ___ eres mi amigo.',
            ['Yo', 'Tú', 'Él'],
            1,
            '2ª pessoa singular: tú.',
            'Tú eres mi amigo.',
        ),
        (
            'Complete: ___ es profesor.',
            ['Yo', 'Nosotros', 'Él'],
            2,
            '3ª pessoa singular masculino: él.',
            'Él es profesor.',
        ),
        (
            'Complete: ___ somos estudiantes.',
            ['Nosotros', 'Ellos', 'Tú'],
            0,
            '1ª pessoa plural: nosotros.',
            'Nosotros somos estudiantes.',
        ),
        (
            'Complete: ___ viven en Madrid.',
            ['Yo', 'Ellos', 'Tú'],
            1,
            '3ª pessoa plural: ellos.',
            'Ellos viven en Madrid.',
        ),
    ],
    "es-grammar-complete-a1-02": [  # Presente regular (5)
        (
            'Complete: Yo ___ español.',
            ['hablas', 'habla', 'hablo'],
            2,
            'Presente -ar: yo hablo.',
            'Yo hablo español.',
        ),
        (
            'Complete: Tú ___ agua.',
            ['bebes', 'bebo', 'bebe'],
            0,
            'Presente -er: tú bebes.',
            'Tú bebes agua.',
        ),
        (
            'Complete: Ella ___ en Barcelona.',
            ['vivo', 'vive', 'vives'],
            1,
            'Presente -ir: ella vive.',
            'Ella vive en Barcelona.',
        ),
        (
            'Complete: Nosotros ___ juntos.',
            ['trabajan', 'trabajo', 'trabajamos'],
            2,
            'Presente -ar: nosotros trabajamos.',
            'Nosotros trabajamos juntos.',
        ),
        (
            'Complete: Ellos ___ la radio.',
            ['escuchan', 'escucho', 'escuchas'],
            0,
            'Presente -ar: ellos escuchan.',
            'Ellos escuchan la radio.',
        ),
    ],
    "es-grammar-complete-a1-03": [  # Ser, estar e hay (5)
        (
            'Complete: ___ un libro en la mesa.',
            ['Hay', 'Es', 'Está'],
            0,
            'Existência: hay.',
            'Hay un libro en la mesa.',
        ),
        (
            'Complete: María ___ ingeniera.',
            ['está', 'es', 'hay'],
            1,
            'Profissão: ser.',
            'María es ingeniera.',
        ),
        (
            'Complete: El museo ___ cerrado.',
            ['es', 'hay', 'está'],
            2,
            'Estado: estar.',
            'El museo está cerrado.',
        ),
        (
            'Complete: ¿___ alguien en casa?',
            ['Hay', 'Es', 'Está'],
            0,
            'Existência em pergunta: ¿hay...?',
            '¿Hay alguien en casa?',
        ),
        (
            'Complete: Nosotros ___ felices hoy.',
            ['somos', 'estamos', 'hay'],
            1,
            'Estado emocional: estar.',
            'Nosotros estamos felices hoy.',
        ),
    ],
    "es-grammar-complete-a1-04": [  # Tener e expressões (5)
        (
            'Complete: Yo ___ veinte años.',
            ['soy', 'tengo', 'estoy'],
            1,
            'Idade: tener + años.',
            'Yo tengo veinte años.',
        ),
        (
            'Complete: ¿___ hambre?',
            ['Eres', 'Estás', 'Tienes'],
            2,
            "'Tener hambre' = estar com fome.",
            '¿Tienes hambre?',
        ),
        (
            'Complete: Ella ___ frío.',
            ['tiene', 'es', 'está'],
            0,
            "'Tener frío' = estar com frio.",
            'Ella tiene frío.',
        ),
        (
            'Complete: Nosotros ___ suerte.',
            ['somos', 'tenemos', 'estamos'],
            1,
            "'Tener suerte' = ter sorte.",
            'Nosotros tenemos suerte.',
        ),
        (
            'Complete: Ellos ___ prisa.',
            ['son', 'están', 'tienen'],
            2,
            "'Tener prisa' = ter pressa.",
            'Ellos tienen prisa.',
        ),
    ],
    "es-grammar-complete-a1-05": [  # Ir, venir, hacer e querer (5)
        (
            'Complete: Yo ___ al parque.',
            ['vengo', 'voy', 'hago'],
            1,
            "'Ir' = ir (para lá): voy.",
            'Yo voy al parque.',
        ),
        (
            'Complete: ¿De dónde ___?',
            ['vas', 'haces', 'vienes'],
            2,
            "'Venir' = vir de: vienes.",
            '¿De dónde vienes?',
        ),
        (
            'Complete: ¿Qué ___ tú?',
            ['haces', 'vas', 'vienes'],
            0,
            "'Hacer' no presente: haces.",
            '¿Qué haces tú?',
        ),
        (
            'Complete: Nosotros ___ pizza.',
            ['vamos', 'queremos', 'hacemos'],
            1,
            "'Querer' = querer: queremos.",
            'Nosotros queremos pizza.',
        ),
        (
            'Complete: Ellos ___ deporte.',
            ['van', 'vienen', 'hacen'],
            2,
            "'Hacer deporte' = praticar esporte.",
            'Ellos hacen deporte.',
        ),
    ],
    "es-grammar-complete-a1-06": [  # Interrogativos (5)
        (
            'Complete: ¿___ te llamas?',
            ['Cómo', 'Qué', 'Dónde'],
            0,
            'Nome: ¿cómo te llamas?',
            '¿Cómo te llamas?',
        ),
        (
            'Complete: ¿___ es tu hermano?',
            ['Qué', 'Quién', 'Cuándo'],
            1,
            'Pessoa: ¿quién?',
            '¿Quién es tu hermano?',
        ),
        (
            'Complete: ¿___ vives?',
            ['Qué', 'Cómo', 'Dónde'],
            2,
            'Lugar: ¿dónde?',
            '¿Dónde vives?',
        ),
        (
            'Complete: ¿___ es la fiesta?',
            ['Cuándo', 'Quién', 'Dónde'],
            0,
            'Tempo: ¿cuándo?',
            '¿Cuándo es la fiesta?',
        ),
        (
            'Complete: ¿___ quieres beber?',
            ['Quién', 'Qué', 'Cuándo'],
            1,
            'Coisa/ação: ¿qué?',
            '¿Qué quieres beber?',
        ),
    ],
    "es-grammar-complete-a1-07": [  # Gustar e verbos semelhantes (5)
        (
            'Complete: Me ___ el chocolate.',
            ['gustan', 'gusto', 'gusta'],
            2,
            'Singular (el chocolate) → gusta.',
            'Me gusta el chocolate.',
        ),
        (
            'Complete: Me ___ las películas.',
            ['gustan', 'gusta', 'gusto'],
            0,
            'Plural (las películas) → gustan.',
            'Me gustan las películas.',
        ),
        (
            'Complete: ¿Te ___ el café?',
            ['gustan', 'gusta', 'gustas'],
            1,
            'Singular → te gusta.',
            '¿Te gusta el café?',
        ),
        (
            'Complete: Nos ___ bailar.',
            ['encantan', 'encantamos', 'encanta'],
            2,
            'Infinitivo singular → nos encanta.',
            'Nos encanta bailar.',
        ),
        (
            'Complete: A ellos les ___ los deportes.',
            ['interesan', 'interesa', 'interesan a'],
            0,
            'Plural → les interesan.',
            'A ellos les interesan los deportes.',
        ),
    ],
    "es-grammar-complete-a2-01": [  # Pretérito perfecto (6)
        (
            'Complete: Esta semana ___ mucho.',
            ['estudié', 'estudiaba', 'he estudiado'],
            2,
            'Período aberto: he estudiado.',
            'Esta semana he estudiado mucho.',
        ),
        (
            'Complete: ¿Ya ___?',
            ['has comido', 'comiste', 'comías'],
            0,
            "'Ya' + perfecto.",
            '¿Ya has comido?',
        ),
        (
            'Complete: Nunca ___ París.',
            ['visité', 'he visitado', 'visitaba'],
            1,
            'Experiência: nunca he visitado.',
            'Nunca he visitado París.',
        ),
        (
            'Complete: Hoy ___ a Juan.',
            ['vi', 'veía', 'he visto'],
            2,
            'Participio irregular: visto.',
            'Hoy he visto a Juan.',
        ),
        (
            'Complete: Todavía no ___ el correo.',
            ['hemos recibido', 'recibimos', 'recibíamos'],
            0,
            "'Todavía no' + perfecto.",
            'Todavía no hemos recibido el correo.',
        ),
        (
            'Complete: Ellos ___ la puerta.',
            ['cerraron', 'han cerrado', 'cerraban'],
            1,
            'Resultado atual: han cerrado.',
            'Ellos han cerrado la puerta.',
        ),
    ],
    "es-grammar-complete-a2-02": [  # Pretérito indefinido (6)
        (
            'Complete: Ayer ___ al supermercado.',
            ['iba', 'fui', 'he ido'],
            1,
            'Ação pontual: fui.',
            'Ayer fui al supermercado.',
        ),
        (
            'Complete: Ella ___ una novela.',
            ['leía', 'ha leído', 'leyó'],
            2,
            'Indefinido: leyó.',
            'Ella leyó una novela.',
        ),
        (
            'Complete: Nosotros ___ en 2019.',
            ['llegamos', 'llegábamos', 'hemos llegado'],
            0,
            'Data fechada: llegamos.',
            'Nosotros llegamos en 2019.',
        ),
        (
            'Complete: ¿Qué ___ el domingo pasado?',
            ['hacías', 'hiciste', 'has hecho'],
            1,
            'Indefinido de hacer: hiciste.',
            '¿Qué hiciste el domingo pasado?',
        ),
        (
            'Complete: Ellos ___ la verdad.',
            ['decían', 'han dicho', 'dijeron'],
            2,
            'Indefinido irregular: dijeron.',
            'Ellos dijeron la verdad.',
        ),
        (
            'Complete: Yo ___ la ventana.',
            ['abrí', 'abría', 'he abierto'],
            0,
            'Indefinido regular -ir: abrí.',
            'Yo abrí la ventana.',
        ),
    ],
    "es-grammar-complete-a2-03": [  # Pretérito imperfecto (6)
        (
            'Complete: De niño, yo ___ en el parque.',
            ['jugué', 'jugaba', 'he jugado'],
            1,
            'Hábito no passado: imperfecto.',
            'De niño, yo jugaba en el parque.',
        ),
        (
            'Complete: Mientras ella ___, yo cocinaba.',
            ['leyó', 'ha leído', 'leía'],
            2,
            'Ação em curso simultânea: imperfecto.',
            'Mientras ella leía, yo cocinaba.',
        ),
        (
            'Complete: Antes ___ mucho café.',
            ['tomábamos', 'tomamos', 'hemos tomado'],
            0,
            'Costume passado: tomábamos.',
            'Antes tomábamos mucho café.',
        ),
        (
            'Complete: El cielo ___ nublado.',
            ['estuvo', 'estaba', 'ha estado'],
            1,
            'Descrição no passado: imperfecto.',
            'El cielo estaba nublado.',
        ),
        (
            'Complete: Ellos ___ felices entonces.',
            ['fueron', 'han sido', 'eran'],
            2,
            'Estado descritivo: eran.',
            'Ellos eran felices entonces.',
        ),
        (
            'Complete: Siempre ___ temprano.',
            ['llegaba', 'llegué', 'he llegado'],
            0,
            "'Siempre' no passado → imperfecto habitual.",
            'Siempre llegaba temprano.',
        ),
    ],
    "es-grammar-complete-a2-04": [  # Pronombres de objeto (6)
        (
            'Complete: ¿La carta? ___ escribí ayer.',
            ['La', 'Le', 'Lo'],
            0,
            'OD feminino singular: la.',
            '¿La carta? La escribí ayer.',
        ),
        (
            'Complete: Voy a ___ un mensaje.',
            ['enviarlo', 'enviarle', 'enviarla'],
            1,
            'OI: enviarle.',
            'Voy a enviarle un mensaje.',
        ),
        (
            'Complete: ¿Los documentos? No ___ tengo.',
            ['les', 'lo', 'los'],
            2,
            'OD masculino plural: los.',
            '¿Los documentos? No los tengo.',
        ),
        (
            'Complete: ___ digo la verdad a Ana.',
            ['Le', 'La', 'Lo'],
            0,
            'OI: le (a Ana).',
            'Le digo la verdad a Ana.',
        ),
        (
            'Complete: ¿Me ___ la sal?',
            ['paso', 'pasas', 'pasan'],
            1,
            'Pedido com OD: ¿me pasas...?',
            '¿Me pasas la sal?',
        ),
        (
            'Complete: Se ___ conté todo.',
            ['le', 'la', 'lo'],
            2,
            'Se + lo: se lo conté.',
            'Se lo conté todo.',
        ),
    ],
    "es-grammar-complete-a2-05": [  # Comparativos e superlativos (6)
        (
            'Complete: Ana es ___ alta que María.',
            ['menos', 'más', 'tan'],
            1,
            'Comparativo de superioridade: más... que.',
            'Ana es más alta que María.',
        ),
        (
            'Complete: Este libro es ___ interesante que ese.',
            ['más', 'tan', 'menos'],
            2,
            'Comparativo de inferioridade: menos... que.',
            'Este libro es menos interesante que ese.',
        ),
        (
            'Complete: Pedro es ___ inteligente como Luis.',
            ['tan', 'más', 'menos'],
            0,
            'Igualdade: tan... como.',
            'Pedro es tan inteligente como Luis.',
        ),
        (
            'Complete: Es el ___ rápido de la clase.',
            ['menos', 'más', 'tan'],
            1,
            'Superlativo relativo: el más...',
            'Es el más rápido de la clase.',
        ),
        (
            'Complete: Tengo ___ libros que tú.',
            ['tan', 'muy', 'más'],
            2,
            'Comparativo com substantivo: más... que.',
            'Tengo más libros que tú.',
        ),
        (
            'Complete: Esta película es ___ buena.',
            ['muy', 'más', 'tan'],
            0,
            'Intensidade (não comparação): muy.',
            'Esta película es muy buena.',
        ),
    ],
    "es-grammar-complete-b1-01": [  # Contraste entre passados (8)
        (
            'Complete: Cuando ___ , sonaba el teléfono.',
            ['llegaba', 'he llegado', 'llegaré', 'llegué'],
            3,
            'Ação pontual que interrompe: indefinido.',
            'Cuando llegué, sonaba el teléfono.',
        ),
        (
            'Complete: Mientras ___ , sonó el teléfono.',
            ['estudiaba', 'estudié', 'he estudiado', 'estudiaré'],
            0,
            'Fundo/ação em curso: imperfecto.',
            'Mientras estudiaba, sonó el teléfono.',
        ),
        (
            'Complete: Hoy ___ tres veces.',
            ['llamé', 'he llamado', 'llamaba', 'llamaré'],
            1,
            'Hoje (período aberto): perfecto.',
            'Hoy he llamado tres veces.',
        ),
        (
            'Complete: En 2010 ___ a España.',
            ['viajaba', 'he viajado', 'viajé', 'viajaré'],
            2,
            'Data fechada: indefinido.',
            'En 2010 viajé a España.',
        ),
        (
            'Complete: Antes ___ más delgado.',
            ['fui', 'he sido', 'seré', 'era'],
            3,
            'Descrição habitual: imperfecto.',
            'Antes era más delgado.',
        ),
        (
            'Complete: Ya ___ el informe.',
            ['he terminado', 'terminé', 'terminaba', 'terminaré'],
            0,
            'Resultado recente: perfecto.',
            'Ya he terminado el informe.',
        ),
        (
            'Complete: De repente, ___ la luz.',
            ['se apagaba', 'se apagó', 'se ha apagado', 'se apagará'],
            1,
            'Evento súbito: indefinido.',
            'De repente, se apagó la luz.',
        ),
        (
            'Complete: Siempre ___ a la misma hora.',
            ['salió', 'ha salido', 'salía', 'saldrá'],
            2,
            'Hábito passado: imperfecto.',
            'Siempre salía a la misma hora.',
        ),
    ],
    "es-grammar-complete-b1-02": [  # Futuro e condicional (8)
        (
            'Complete: Mañana ___ temprano.',
            ['saldría', 'saldré', 'salí', 'salía'],
            1,
            'Futuro simples: saldré.',
            'Mañana saldré temprano.',
        ),
        (
            'Complete: En tu lugar, yo ___.',
            ['iré', 'fui', 'iría', 'iba'],
            2,
            'Conselho hipotético: condicional.',
            'En tu lugar, yo iría.',
        ),
        (
            'Complete: ¿___ venir mañana?',
            ['Podrías', 'Pudiste', 'Podías', 'Podrás'],
            3,
            'Futuro de poder: podrás.',
            '¿Podrás venir mañana?',
        ),
        (
            'Complete: Me ___ un café, por favor.',
            ['gustaría', 'gustará', 'gustó', 'gustaba'],
            0,
            'Pedido educado: me gustaría.',
            'Me gustaría un café, por favor.',
        ),
        (
            'Complete: Creo que ___ tarde.',
            ['llegaría', 'llegará', 'llegó', 'llegaba'],
            1,
            'Previsão: futuro.',
            'Creo que llegará tarde.',
        ),
        (
            'Complete: Sin tu ayuda, no ___ terminado.',
            ['habré', 'había', 'habría', 'he'],
            2,
            'Condicional composto: no habría terminado.',
            'Sin tu ayuda, no habría terminado.',
        ),
        (
            'Complete: El año que viene ___ en París.',
            ['viviría', 'viví', 'vivía', 'viviré'],
            3,
            'Futuro: viviré.',
            'El año que viene viviré en París.',
        ),
        (
            'Complete: ¿Qué ___ tú en esa situación?',
            ['harías', 'harás', 'hiciste', 'hacías'],
            0,
            'Hipotético: harías.',
            '¿Qué harías tú en esa situación?',
        ),
    ],
    "es-grammar-complete-b1-03": [  # Imperativo (8)
        (
            'Complete: ¡___ la puerta, por favor!',
            ['Abre', 'Abres', 'Abrir', 'Abrió'],
            0,
            'Imperativo afirmativo tú: abre.',
            '¡Abre la puerta, por favor!',
        ),
        (
            'Complete: ¡No ___ eso!',
            ['haces', 'hagas', 'haz', 'hiciste'],
            1,
            'Imperativo negativo: no + subjuntivo.',
            '¡No hagas eso!',
        ),
        (
            'Complete: ¡___ ustedes aquí!',
            ['Esperan', 'Esperad', 'Esperen', 'Esperaron'],
            2,
            'Imperativo ustedes: esperen.',
            '¡Esperen ustedes aquí!',
        ),
        (
            'Complete: ¡___ me la verdad!',
            ['Dices', 'Decir', 'Dijo', 'Di'],
            3,
            'Imperativo irregular: di.',
            '¡Dime la verdad!',
        ),
        (
            'Complete: ¡No ___ tarde!',
            ['llegues', 'llegas', 'llega', 'llegaste'],
            0,
            'Negativo tú: no llegues.',
            '¡No llegues tarde!',
        ),
        (
            'Complete: ¡___ con cuidado!',
            ['Vas', 'Ve', 'Ir', 'Fue'],
            1,
            'Imperativo de ir: ve.',
            '¡Ve con cuidado!',
        ),
        (
            'Complete: ¡___ la mesa!',
            ['Ponéis', 'Poner', 'Poned', 'Pusisteis'],
            2,
            'Imperativo vosotros: poned.',
            '¡Poned la mesa!',
        ),
        (
            'Complete: ¡No ___ preocupéis!',
            ['se', 'le', 'te', 'os'],
            3,
            'Negativo vosotros: no os preocupéis.',
            '¡No os preocupéis!',
        ),
    ],
    "es-grammar-complete-b1-04": [  # Pronombres relativos (8)
        (
            'Complete: El libro ___ leí es bueno.',
            ['quien', 'cual', 'que', 'cuyo'],
            2,
            'Relativo geral: que.',
            'El libro que leí es bueno.',
        ),
        (
            'Complete: La mujer ___ habla es mi jefa.',
            ['quien', 'cuyo', 'donde', 'que'],
            3,
            "'Que' com antecedente pessoa (sujeito).",
            'La mujer que habla es mi jefa.',
        ),
        (
            'Complete: El amigo con ___ viajé vive aquí.',
            ['quien', 'que', 'cual', 'cuyo'],
            0,
            'Após preposição + pessoa: quien.',
            'El amigo con quien viajé vive aquí.',
        ),
        (
            'Complete: La casa ___ vivo es antigua.',
            ['que', 'donde', 'quien', 'cuyo'],
            1,
            'Lugar: donde.',
            'La casa donde vivo es antigua.',
        ),
        (
            'Complete: El día ___ nos conocimos fue especial.',
            ['quien', 'cuyo', 'en que', 'donde'],
            2,
            'Tempo: el día en que...',
            'El día en que nos conocimos fue especial.',
        ),
        (
            'Complete: Un autor ___ novelas admiro.',
            ['que', 'quien', 'donde', 'cuyas'],
            3,
            'Posse: cuyas (feminino plural).',
            'Un autor cuyas novelas admiro.',
        ),
        (
            'Complete: Hay personas ___ no escuchan.',
            ['que', 'quien', 'cuyo', 'donde'],
            0,
            'Antecedente plural: que.',
            'Hay personas que no escuchan.',
        ),
        (
            'Complete: Lo ___ dijiste es verdad.',
            ['quien', 'que', 'cual', 'cuyo'],
            1,
            'Neutro: lo que.',
            'Lo que dijiste es verdad.',
        ),
    ],
    "es-grammar-complete-b2-01": [  # Imperfecto de subjuntivo (10)
        (
            'Complete: Quería que ___ conmigo.',
            ['vienes', 'vinieras', 'vengas', 'vendrías'],
            1,
            'Após passado de vontade → imperfecto de subjuntivo.',
            'Quería que vinieras conmigo.',
        ),
        (
            'Complete: Si ___ rico, viajaría más.',
            ['soy', 'sea', 'fuera', 'seré'],
            2,
            'Condicional tipo 2: si + imperfecto de subjuntivo.',
            'Si fuera rico, viajaría más.',
        ),
        (
            'Complete: Me pidió que ___ silencio.',
            ['guardo', 'guarde', 'guardaré', 'guardara'],
            3,
            'Pedido no passado → imperfecto de subjuntivo.',
            'Me pidió que guardara silencio.',
        ),
        (
            'Complete: Ojalá ___ más tiempo.',
            ['tuviera', 'tengo', 'tenga', 'tendré'],
            0,
            "'Ojalá' hipotético: tuviera.",
            'Ojalá tuviera más tiempo.',
        ),
        (
            'Complete: Como si ___ la verdad.',
            ['sabe', 'supiera', 'sepa', 'sabrá'],
            1,
            "'Como si' → imperfecto de subjuntivo.",
            'Habla como si supiera la verdad.',
        ),
        (
            'Complete: Era necesario que ___ pronto.',
            ['salimos', 'salgamos', 'saliéramos', 'saldremos'],
            2,
            'Necessidade no passado → imperfecto de subjuntivo.',
            'Era necesario que saliéramos pronto.',
        ),
        (
            'Complete: No creía que ___ posible.',
            ['es', 'sea', 'será', 'fuera'],
            3,
            'Dúvida no passado → imperfecto de subjuntivo.',
            'No creía que fuera posible.',
        ),
        (
            'Complete: Te aconsejé que ___ al médico.',
            ['fueras', 'vas', 'vayas', 'irás'],
            0,
            'Conselho referido → imperfecto de subjuntivo.',
            'Te aconsejé que fueras al médico.',
        ),
        (
            'Complete: Aunque ___ , no iría.',
            ['llueve', 'lloviera', 'llueva', 'lloverá'],
            1,
            'Concessiva hipotética: aunque + imperfecto de subjuntivo.',
            'Aunque lloviera, no iría.',
        ),
        (
            'Complete: Buscaba a alguien que ___ chino.',
            ['habla', 'hable', 'hablara', 'hablará'],
            2,
            'Antecedente indefinido no passado → imperfecto de subjuntivo.',
            'Buscaba a alguien que hablara chino.',
        ),
    ],
    "es-grammar-complete-b2-02": [  # Condicional compuesto (10)
        (
            'Complete: Si lo hubiera sabido, te lo ___.',
            ['diría', 'diré', 'habría dicho', 'dije'],
            2,
            'Tipo 3: condicional composto.',
            'Si lo hubiera sabido, te lo habría dicho.',
        ),
        (
            'Complete: Sin tu ayuda, no ___ acabado a tiempo.',
            ['habré', 'había', 'he', 'habría'],
            3,
            'Hipotético passado: no habría acabado.',
            'Sin tu ayuda, no habría acabado a tiempo.',
        ),
        (
            'Complete: ¿Qué ___ hecho tú?',
            ['habrías', 'habrás', 'habías', 'has'],
            0,
            'Condicional composto interrogativo.',
            '¿Qué habrías hecho tú?',
        ),
        (
            'Complete: Me ___ gustado conocerte antes.',
            ['habré', 'habría', 'había', 'he'],
            1,
            'Desejo irreal no passado: me habría gustado.',
            'Me habría gustado conocerte antes.',
        ),
        (
            'Complete: Ellos ___ venido si los hubiéramos invitado.',
            ['habrán', 'habían', 'habrían', 'han'],
            2,
            'Principal do tipo 3: habrían venido.',
            'Ellos habrían venido si los hubiéramos invitado.',
        ),
        (
            'Complete: Nunca ___ imaginado semejante final.',
            ['habré', 'había', 'he', 'habría'],
            3,
            'Reflexão hipotética: nunca habría imaginado.',
            'Nunca habría imaginado semejante final.',
        ),
        (
            'Complete: De haber estudiado, ___ aprobado.',
            ['habría', 'habré', 'había', 'he'],
            0,
            "'De haber...' + condicional composto.",
            'De haber estudiado, habría aprobado.',
        ),
        (
            'Complete: En tu lugar, yo no ___ aceptado.',
            ['habré', 'habría', 'había', 'he'],
            1,
            'Conselho sobre o passado: no habría aceptado.',
            'En tu lugar, yo no habría aceptado.',
        ),
        (
            'Complete: ¿Quién ___ pensado eso?',
            ['habrá', 'había', 'habría', 'ha'],
            2,
            'Surpresa hipotética: quién habría pensado.',
            '¿Quién habría pensado eso?',
        ),
        (
            'Complete: Ojalá ___ llegado a tiempo.',
            ['habríamos', 'hemos', 'habíamos', 'hubiéramos'],
            3,
            'Desejo irreal passado: ojalá hubiéramos llegado.',
            'Ojalá hubiéramos llegado a tiempo.',
        ),
    ],
    "es-grammar-complete-b2-03": [  # Pasiva e impessoal (10)
        (
            'Complete: La novela ___ escrita por Carmen.',
            ['es', 'está', 'fue', 'sería'],
            2,
            'Passiva de processo (pretérito): fue escrita.',
            'La novela fue escrita por Carmen.',
        ),
        (
            'Complete: El museo ___ cerrado los lunes.',
            ['es', 'fue', 'sería', 'está'],
            3,
            'Estado resultante: está cerrado.',
            'El museo está cerrado los lunes.',
        ),
        (
            'Complete: ___ dice que va a llover.',
            ['Se', 'Le', 'Lo', 'Uno'],
            0,
            'Impessoal: se dice.',
            'Se dice que va a llover.',
        ),
        (
            'Complete: Los documentos ___ firmados ayer.',
            ['están', 'fueron', 'son', 'serían'],
            1,
            'Passiva com agente implícito: fueron firmados.',
            'Los documentos fueron firmados ayer.',
        ),
        (
            'Complete: Aquí ___ habla inglés.',
            ['le', 'lo', 'se', 'uno'],
            2,
            'Passiva reflexa/impessoal: se habla.',
            'Aquí se habla inglés.',
        ),
        (
            'Complete: La decisión ___ tomada por el comité.',
            ['está', 'es', 'sería', 'fue'],
            3,
            "Passiva com 'por': fue tomada.",
            'La decisión fue tomada por el comité.',
        ),
        (
            'Complete: ___ debe respetar las normas.',
            ['Se', 'Le', 'Lo', 'Uno'],
            0,
            'Impessoal deôntico: se debe.',
            'Se debe respetar las normas.',
        ),
        (
            'Complete: El problema ___ resuelto.',
            ['fue', 'está', 'es', 'sería'],
            1,
            'Resultado: está resuelto.',
            'El problema está resuelto.',
        ),
        (
            'Complete: Las casas ___ construyendo.',
            ['están se', 'son', 'se están', 'fueron'],
            2,
            'Passiva reflexa progressiva: se están construyendo.',
            'Las casas se están construyendo.',
        ),
        (
            'Complete: ___ considera un experto.',
            ['Le se', 'Lo se', 'Se lo', 'Se le'],
            3,
            'Impessoal + OI: se le considera.',
            'Se le considera un experto.',
        ),
    ],
    "es-grammar-complete-b2-04": [  # Verbos de cambio (10)
        (
            'Complete: Se ___ rojo de vergüenza.',
            ['puso', 'hizo', 'volvió', 'llegó'],
            0,
            "'Ponerse' + adjetivo = mudança temporária.",
            'Se puso rojo de vergüenza.',
        ),
        (
            'Complete: Se ___ profesor el año pasado.',
            ['puso', 'hizo', 'volvió', 'quedó'],
            1,
            "'Hacerse' = tornar-se (esforço/profissão).",
            'Se hizo profesor el año pasado.',
        ),
        (
            'Complete: Se ___ loco con la noticia.',
            ['puso', 'hizo', 'volvió', 'llegó'],
            2,
            "'Volverse' = mudança profunda/surpreendente.",
            'Se volvió loco con la noticia.',
        ),
        (
            'Complete: Se ___ viudo muy joven.',
            ['puso', 'hizo', 'volvió', 'quedó'],
            3,
            "'Quedarse' = ficar em um estado resultante.",
            'Se quedó viudo muy joven.',
        ),
        (
            'Complete: ___ a ser un gran artista.',
            ['Llegó', 'Se puso', 'Se hizo', 'Se volvió'],
            0,
            "'Llegar a ser' = tornar-se após processo.",
            'Llegó a ser un gran artista.',
        ),
        (
            'Complete: Se ___ enfermo tras el viaje.',
            ['hizo', 'puso', 'volvió', 'llegó'],
            1,
            "'Ponerse enfermo' = adoecer.",
            'Se puso enfermo tras el viaje.',
        ),
        (
            'Complete: Con el tiempo se ___ más serio.',
            ['ha puesto', 'ha hecho', 'ha vuelto', 'ha llegado'],
            2,
            "'Volverse' para mudança de caráter.",
            'Con el tiempo se ha vuelto más serio.',
        ),
        (
            'Complete: Se ___ de piedra al oírlo.',
            ['puso', 'hizo', 'volvió', 'quedó'],
            3,
            "'Quedarse de piedra' = ficar boquiaberto.",
            'Se quedó de piedra al oírlo.',
        ),
        (
            'Complete: ___ rico vendiendo propiedades.',
            ['Se hizo', 'Se puso', 'Se volvió', 'Se quedó'],
            0,
            "'Hacerse rico' = enriquecer-se.",
            'Se hizo rico vendiendo propiedades.',
        ),
        (
            'Complete: La leche se ___ agria.',
            ['ha hecho', 'ha puesto', 'ha vuelto', 'ha llegado'],
            1,
            "'Ponerse' com mudança física temporária.",
            'La leche se ha puesto agria.',
        ),
    ],
    "es-grammar-complete-b2-05": [  # Verbos de opinião e discurso (10)
        (
            'Complete: Creo que ___ razón.',
            ['tengas', 'tuvieras', 'tienes', 'tendrás'],
            2,
            'Opinião afirmativa → indicativo.',
            'Creo que tienes razón.',
        ),
        (
            'Complete: No creo que ___ razón.',
            ['tienes', 'tuvieras', 'tendrás', 'tengas'],
            3,
            'Opinião negativa → subjuntivo.',
            'No creo que tengas razón.',
        ),
        (
            'Complete: Pienso que ___ necesario.',
            ['es', 'sea', 'fuera', 'será'],
            0,
            "'Pienso que' afirmativo → indicativo.",
            'Pienso que es necesario.',
        ),
        (
            'Complete: Opino que deberíamos ___.',
            ['esperemos', 'esperar', 'esperáramos', 'esperaremos'],
            1,
            "Após 'deberíamos' → infinitivo.",
            'Opino que deberíamos esperar.',
        ),
        (
            'Complete: Dijo que ___ mañana.',
            ['viene', 'venga', 'vendría', 'vino'],
            2,
            'Discurso indireto: futuro → condicional.',
            'Dijo que vendría mañana.',
        ),
        (
            'Complete: Afirmó ___ visto el informe.',
            ['haberlo', 'habiendo', 'haberse', 'haber'],
            3,
            'Após verbo de declaração: haber + participio.',
            'Afirmó haber visto el informe.',
        ),
        (
            'Complete: No me parece que ___ justo.',
            ['sea', 'es', 'fue', 'será'],
            0,
            'Valoração negativa → subjuntivo.',
            'No me parece que sea justo.',
        ),
        (
            'Complete: Según los expertos, el plan ___.',
            ['funcione', 'funcionará', 'funcionara', 'funcionaría'],
            1,
            "Atribuição com 'según' + indicativo futuro.",
            'Según los expertos, el plan funcionará.',
        ),
        (
            'Complete: Negó que ___ involucrado.',
            ['estaba', 'esté', 'estuviera', 'estará'],
            2,
            "'Negar que' no passado → imperfecto de subjuntivo.",
            'Negó que estuviera involucrado.',
        ),
        (
            'Complete: Considero ___ una buena idea.',
            ['que sea', 'que fuera', 'que será', 'que es'],
            3,
            "'Considerar que' afirmativo → indicativo.",
            'Considero que es una buena idea.',
        ),
    ],
    "es-grammar-complete-b2-06": [  # Expressões frequentes (10)
        (
            'Complete: ___ de que me digas eso...',
            ['En cambio', 'A propósito', 'Sin embargo', 'Por cierto'],
            1,
            "'A propósito' = a propósito / falando nisso.",
            'A propósito de que me digas eso...',
        ),
        (
            'Complete: ___, no estoy de acuerdo.',
            ['A propósito', 'Es decir', 'En cambio', 'Por cierto'],
            2,
            "'En cambio' = em compensação / ao contrário.",
            'En cambio, no estoy de acuerdo.',
        ),
        (
            'Complete: ___, ¿vienes mañana?',
            ['En cambio', 'Es decir', 'Sin embargo', 'Por cierto'],
            3,
            "'Por cierto' = a propósito.",
            'Por cierto, ¿vienes mañana?',
        ),
        (
            'Complete: No me importa ___.',
            ['en absoluto', 'en cambio', 'a propósito', 'por cierto'],
            0,
            "'En absoluto' = de forma alguma.",
            'No me importa en absoluto.',
        ),
        (
            'Complete: ___ lo que digan, seguiré.',
            ['En cambio', 'Pese a', 'A propósito', 'Por cierto'],
            1,
            "'Pese a' = apesar de.",
            'Pese a lo que digan, seguiré.',
        ),
        (
            'Complete: Estoy ___ de acuerdo contigo.',
            ['absolutamente no', 'apenas', 'totalmente', 'casi no'],
            2,
            "'Totalmente de acuerdo' = plenamente de acordo.",
            'Estoy totalmente de acuerdo contigo.',
        ),
        (
            'Complete: ___ dicho, cerramos el tema.',
            ['En cambio', 'A propósito', 'Por cierto', 'Dicho esto'],
            3,
            "'Dicho esto' = dito isto.",
            'Dicho esto, cerramos el tema.',
        ),
        (
            'Complete: No es para ___.',
            ['tanto', 'nada', 'poco', 'mucho'],
            0,
            "'No es para tanto' = não é para tanto.",
            'No es para tanto.',
        ),
        (
            'Complete: ___ más, acabamos temprano.',
            ['Hay', 'Es', 'Hace', 'Tiene'],
            1,
            "'Es más' = além disso.",
            'Es más, acabamos temprano.',
        ),
        (
            'Complete: De ___ , avísame.',
            ['ninguna forma', 'alguna forma', 'todas formas', 'otra forma'],
            2,
            "'De todas formas' = de qualquer forma.",
            'De todas formas, avísame.',
        ),
    ],
}


def get_banks():
    return BANKS
