# -*- coding: utf-8 -*-
"""Italian grammar cloze exercise banks keyed by topic_id.

Each exercise is:
  (question, options_list, answer_index, explanation_pt_br, example_correct_sentence)
"""

from __future__ import annotations

BANKS: dict[str, list[tuple[str, list[str], int, str, str]]] = {
    # --- Core A1 ---
    "it-grammar-A1-1": [  # Essere e avere (5)
        (
            'Complete: Io ___ studente.',
            ['sono', 'sei', 'ho'],
            0,
            "Com 'essere' usa-se 'sono' na 1ª pessoa do singular para identidade.",
            'Io sono studente.',
        ),
        (
            'Complete: Maria ___ una macchina nuova.',
            ['ha', 'è', 'sono'],
            0,
            "'Avere' indica posse: lei ha una macchina.",
            'Maria ha una macchina nuova.',
        ),
        (
            'Complete: Tu ___ di Roma?',
            ['sei', 'è', 'hai'],
            0,
            "Origem/nacionalidade: 'essere' + di + lugar.",
            'Tu sei di Roma?',
        ),
        (
            'Complete: Noi ___ freddo oggi.',
            ['avete', 'siamo', 'abbiamo'],
            2,
            "Sensações físicas usam 'avere': avere freddo/fame/sete.",
            'Noi abbiamo freddo oggi.',
        ),
        (
            'Complete: Loro ___ molto stanchi.',
            ['è', 'hanno', 'sono'],
            2,
            "Estados e condições usam 'essere' + adjetivo.",
            'Loro sono molto stanchi.',
        ),
    ],
    "it-grammar-A1-2": [  # Articoli e accordo (5)
        (
            'Complete: ___ libro è interessante.',
            ['Il', 'La', 'Lo'],
            0,
            "'Libro' é masculino singular: artigo 'il'.",
            'Il libro è interessante.',
        ),
        (
            'Complete: ___ casa di Luca è grande.',
            ['La', 'Lo', 'Il'],
            0,
            "'Casa' é feminino singular: artigo 'la'.",
            'La casa di Luca è grande.',
        ),
        (
            'Complete: ___ studenti sono in classe.',
            ['Gli', 'Lo', 'Il'],
            0,
            "Masculino plural começando com s+consoante ou vogal: 'gli'.",
            'Gli studenti sono in classe.',
        ),
        (
            'Complete: Ho comprato ___ scarpe rosse.',
            ['i', 'il', 'le'],
            2,
            "'Scarpe' é feminino plural: artigo 'le'.",
            'Ho comprato le scarpe rosse.',
        ),
        (
            'Complete: Quella ragazza è ___ italiana.',
            ['uno', 'un', 'una'],
            2,
            "Artigo indefinido feminino singular: 'una'.",
            'Quella ragazza è una italiana.',
        ),
    ],
    # --- Core A2 ---
    "it-grammar-A2-3": [  # Il presente (6)
        (
            'Complete: Ogni giorno Marco ___ al lavoro alle otto.',
            ['va', 'andava', 'andrò'],
            0,
            "Presente de 'andare' (3ª pessoa): va — hábito atual.",
            'Ogni giorno Marco va al lavoro alle otto.',
        ),
        (
            "Complete: Noi ___ l'italiano due volte a settimana.",
            ['studiate', 'studiano', 'studiamo'],
            2,
            'Presente regular -are: noi studi-iamo.',
            "Noi studiamo l'italiano due volte a settimana.",
        ),
        (
            'Complete: Tu ___ sempre la verità?',
            ['dici', 'dire', 'dice'],
            0,
            "'Dire' é irregular: tu dici.",
            'Tu dici sempre la verità?',
        ),
        (
            'Complete: Loro ___ in un ristorante vicino.',
            ['mangiamo', 'mangiate', 'mangiano'],
            2,
            'Presente -are, 3ª pessoa plural: mangiano.',
            'Loro mangiano in un ristorante vicino.',
        ),
        (
            'Complete: Io ___ un caffè ogni mattina.',
            ['beve', 'bevo', 'beviamo'],
            1,
            "Presente de 'bere' (irregular): io bevo.",
            'Io bevo un caffè ogni mattina.',
        ),
        (
            'Complete: Voi ___ spesso al cinema?',
            ['andate', 'andiamo', 'vanno'],
            0,
            "Presente de 'andare': voi andate.",
            'Voi andate spesso al cinema?',
        ),
    ],
    "it-grammar-A2-4": [  # Il passato prossimo (6)
        (
            'Complete: Ieri ho ___ un film italiano.',
            ['vedevo', 'visto', 'vedere'],
            1,
            "Passato prossimo com avere: participio di 'vedere' = visto.",
            'Ieri ho visto un film italiano.',
        ),
        (
            'Complete: Sara ___ arrivata tardi alla festa.',
            ['è', 'sono', 'ha'],
            0,
            "Verbos de movimento usam 'essere' no passato prossimo.",
            'Sara è arrivata tardi alla festa.',
        ),
        (
            'Complete: Abbiamo ___ la pizza insieme.',
            ['mangiato', 'mangiati', 'mangiare'],
            0,
            "Com 'avere', o particípio não concorda (forma masculina singular).",
            'Abbiamo mangiato la pizza insieme.',
        ),
        (
            'Complete: I ragazzi ___ andati al mare.',
            ['hanno', 'sono', 'è'],
            1,
            "'Andare' + essere; particípio concorda: andati.",
            'I ragazzi sono andati al mare.',
        ),
        (
            'Complete: Hai ___ le chiavi sul tavolo?',
            ['messo', 'mettere', 'mettevo'],
            0,
            "Participio irregular de 'mettere': messo.",
            'Hai messo le chiavi sul tavolo?',
        ),
        (
            'Complete: Non ___ ancora finito i compiti.',
            ['sono', 'è', 'ho'],
            2,
            "'Finire' usa 'avere' no passato prossimo.",
            'Non ho ancora finito i compiti.',
        ),
    ],
    "it-grammar-A2-5": [  # Futuro e progetti (6)
        (
            'Complete: Domani ___ a Milano per lavoro.',
            ['andavo', 'andrò', 'vado'],
            1,
            "Futuro semplice de 'andare': io andrò.",
            'Domani andrò a Milano per lavoro.',
        ),
        (
            "Complete: L'anno prossimo ___ una casa nuova.",
            ['compravamo', 'compriamo', 'compreremo'],
            2,
            'Futuro de verbo -are: compr-eremo.',
            "L'anno prossimo compreremo una casa nuova.",
        ),
        (
            'Complete: Quando ___? Presto, spero.',
            ['arrivi', 'arrivavi', 'arriverai'],
            2,
            'Futuro 2ª pessoa: arriverai.',
            'Quando arriverai? Presto, spero.',
        ),
        (
            'Complete: Stasera ___ al ristorante con gli amici.',
            ['andiamo', 'andavamo', 'andremo'],
            2,
            'Projeto futuro: andremo (noi).',
            'Stasera andremo al ristorante con gli amici.',
        ),
        (
            'Complete: Tra due giorni ___ il risultato.',
            ['sapevo', 'so', 'saprò'],
            2,
            "Futuro irregular de 'sapere': saprò.",
            'Tra due giorni saprò il risultato.',
        ),
        (
            "Complete: Loro ___ a vivere all'estero.",
            ['andranno', 'andavano', 'vanno'],
            0,
            "Futuro de 'andare': loro andranno.",
            "Loro andranno a vivere all'estero.",
        ),
    ],
    # --- Core B1 ---
    "it-grammar-B1-6": [  # Imperfetto o passato prossimo (8)
        (
            'Complete: Mentre ___ , è suonato il telefono.',
            ['lessi', 'ho letto', 'leggevo', 'leggerò'],
            2,
            'Ação em progresso (fundo): imperfetto; interrupção: passato prossimo.',
            'Mentre leggevo, è suonato il telefono.',
        ),
        (
            'Complete: Ieri ___ al cinema per la prima volta.',
            ['sono andato', 'andrò', 'andassi', 'andavo'],
            0,
            'Evento concluído e pontual: passato prossimo.',
            'Ieri sono andato al cinema per la prima volta.',
        ),
        (
            'Complete: Da bambino ___ sempre al parco.',
            ['sono andato', 'vada', 'andrò', 'andavo'],
            3,
            'Hábito no passado: imperfetto.',
            'Da bambino andavo sempre al parco.',
        ),
        (
            'Complete: Quando siamo entrati, lei ___ già.',
            ['ha dormito', 'dormiva', 'dormirà', 'dorma'],
            1,
            'Situação em curso no passado: imperfetto.',
            'Quando siamo entrati, lei dormiva già.',
        ),
        (
            "Complete: L'anno scorso ___ tre libri di Calvino.",
            ['leggevo', 'ho letto', 'lessi sempre', 'leggerò'],
            1,
            'Quantidade definida / ação completa: passato prossimo.',
            "L'anno scorso ho letto tre libri di Calvino.",
        ),
        (
            'Complete: Faceva freddo e ___ la neve.',
            ['cadeva', 'è caduta', 'cadrà', 'cada'],
            0,
            'Descrição atmosférica: imperfetto.',
            'Faceva freddo e cadeva la neve.',
        ),
        (
            "Complete: All'improvviso ___ un rumore forte.",
            ['sentiremo', 'abbiamo sentito', 'sentivamo', 'sentissimo'],
            1,
            'Evento súbito: passato prossimo.',
            "All'improvviso abbiamo sentito un rumore forte.",
        ),
        (
            'Complete: Non ___ bene, perciò sono restato a casa.',
            ['stia', 'starò', 'sono stato', 'stavo'],
            3,
            "Estado/condição de fundo: imperfetto de 'stare'.",
            'Non stavo bene, perciò sono restato a casa.',
        ),
    ],
    "it-grammar-B1-7": [  # Pronomi combinati (8)
        (
            'Complete: Hai il libro? Sì, ___ do subito.',
            ['ce lo', 'ti lo', 'te lo', 'lo ti'],
            2,
            'Indireto + direto: ti+lo → te lo.',
            'Hai il libro? Sì, te lo do subito.',
        ),
        (
            'Complete: Le chiavi? ___ do dopo cena.',
            ['Te le', 'Le ti', 'Ce le', 'Ti le'],
            0,
            'ti + le → te le (pronomes combinados).',
            'Le chiavi? Te le do dopo cena.',
        ),
        (
            'Complete: Il messaggio a Maria? Glielo ___ ieri.',
            ['mandavo', 'mandassi', 'ho mandato', 'manderò'],
            2,
            'gli/le + lo → glielo; passado com avere.',
            'Il messaggio a Maria? Glielo ho mandato ieri.',
        ),
        (
            'Complete: Non ___ dire.',
            ['posso gli la', 'gli la posso', 'gliela posso', 'la gli posso'],
            2,
            'Com modal, o clítico fica antes: gliela posso dire.',
            'Non gliela posso dire.',
        ),
        (
            'Complete: Vuoi i documenti? ___ porto domani.',
            ['Ce li', 'Li ti', 'Ti li', 'Te li'],
            3,
            'ti + li → te li.',
            'Vuoi i documenti? Te li porto domani.',
        ),
        (
            'Complete: A loro la notizia? ___ abbiamo detto.',
            ['La gli', 'Gliela', 'Li la', 'Ce la'],
            1,
            'A loro + la → gliela (mesmo clítico de gli).',
            'A loro la notizia? Gliela abbiamo detto.',
        ),
        (
            'Complete: Mi puoi prestare la penna? Sì, ___ presto.',
            ['me la', 'te la', 'ti la', 'la ti'],
            1,
            'Resposta: te la presto (ti+la).',
            'Mi puoi prestare la penna? Sì, te la presto.',
        ),
        (
            'Complete: Perché non ___ spieghi?',
            ['mi lo', 'lo mi', 'ce lo', 'me lo'],
            3,
            'mi + lo → me lo.',
            'Perché non me lo spieghi?',
        ),
    ],
    "it-grammar-B1-8": [  # Il congiuntivo (8)
        (
            'Complete: Penso che lui ___ ragione.',
            ['ha', 'aveva', 'abbia', 'avrà'],
            2,
            'Após opinião (penso che): congiuntivo presente.',
            'Penso che lui abbia ragione.',
        ),
        (
            'Complete: È importante che tu ___ in orario.',
            ['arrivavi', 'arriverai', 'arriva', 'arrivi'],
            3,
            "Após 'è importante che': congiuntivo (tu arrivi).",
            'È importante che tu arrivi in orario.',
        ),
        (
            'Complete: Dubito che loro ___ la verità.',
            ['sappiano', 'sapevano', 'sapranno', 'sanno'],
            0,
            "Após 'dubito che': congiuntivo de 'sapere' = sappiano.",
            'Dubito che loro sappiano la verità.',
        ),
        (
            'Complete: Voglio che voi ___ più attenti.',
            ['eravate', 'sarete', 'siete', 'siate'],
            3,
            "Após vontade (voglio che): congiuntivo di 'essere' = siate.",
            'Voglio che voi siate più attenti.',
        ),
        (
            'Complete: Non credo che ___ così facile.',
            ['era', 'è', 'sarà', 'sia'],
            3,
            'Negação de crença → congiuntivo: sia.',
            'Non credo che sia così facile.',
        ),
        (
            'Complete: Sebbene ___ stanco, continua a lavorare.',
            ['è', 'sarà', 'sia', 'era'],
            2,
            "Concessiva 'sebbene' + congiuntivo.",
            'Sebbene sia stanco, continua a lavorare.',
        ),
        (
            'Complete: Prima che ___ , chiudi la porta.',
            ['parta', 'partiva', 'parte', 'partirà'],
            0,
            "'Prima che' exige congiuntivo: parta.",
            'Prima che parta, chiudi la porta.',
        ),
        (
            'Complete: Spero che tutto ___ bene.',
            ['va', 'andava', 'vada', 'andrà'],
            2,
            "Após 'spero che': congiuntivo de 'andare' = vada.",
            'Spero che tutto vada bene.',
        ),
    ],
    # --- Core B2 ---
    "it-grammar-B2-9": [  # Periodo ipotetico (10)
        (
            'Complete: Se ___ tempo, vengo con te.',
            ['avrò avuto', 'avessi avuto', 'avessi', 'ho'],
            3,
            'I tipo (real): se + presente / presente ou futuro.',
            'Se ho tempo, vengo con te.',
        ),
        (
            'Complete: Se ___ ricco, viaggerei di più.',
            ['fossi', 'sarò', 'ero', 'sono'],
            0,
            'II tipo (irreal presente): se + congiuntivo imperfetto / condizionale.',
            'Se fossi ricco, viaggerei di più.',
        ),
        (
            "Complete: Se avessi studiato, ___ l'esame.",
            ['supero', 'avrei superato', 'supererei', 'superassi'],
            1,
            'III tipo (irreal passado): se + trapassato / condizionale passato.',
            "Se avessi studiato, avrei superato l'esame.",
        ),
        (
            'Complete: Se piovesse, ___ a casa.',
            ['restassi', 'resto', 'resterei', 'sono restato'],
            2,
            'II tipo: hipótese presente → condizionale presente.',
            'Se piovesse, resterei a casa.',
        ),
        (
            'Complete: Se ___ prima, non avremmo perso il treno.',
            ['partiremmo', 'fossimo partiti', 'partiamo', 'partiamo stati'],
            1,
            'III tipo: se + congiuntivo trapassato.',
            'Se fossimo partiti prima, non avremmo perso il treno.',
        ),
        (
            'Complete: Se mi avesse chiamato, ___ andato subito.',
            ['sarei', 'andassi', 'vado', 'andrei'],
            0,
            'III tipo misto possível: sarei andato (condizionale passato).',
            'Se mi avesse chiamato, sarei andato subito.',
        ),
        (
            'Complete: Se ___ , telefona!',
            ['avessi bisogno', 'avessi avuto bisogno', 'avrai bisogno avuto', 'hai bisogno'],
            3,
            'I tipo imperativo no apodose: se + presente.',
            'Se hai bisogno, telefona!',
        ),
        (
            'Complete: Non ___ così se lo sapessi.',
            ['parlassi', 'ho parlato', 'parlerei', 'parlo'],
            2,
            'II tipo: condizionale na oração principal.',
            'Non parlerei così se lo sapessi.',
        ),
        (
            'Complete: Se non ___ , sarei arrivato in orario.',
            ['ci fosse stato il traffico', "c'era stato", "c'è il traffico", 'ci sarà traffico'],
            0,
            'III tipo: se + trapassato congiuntivo.',
            'Se non ci fosse stato il traffico, sarei arrivato in orario.',
        ),
        (
            'Complete: Qualora ___ problemi, chiamaci.',
            ['ci fossero', "c'erano", 'ci saranno', 'ci sono'],
            0,
            "'Qualora' + congiuntivo (hipótese formal).",
            'Qualora ci fossero problemi, chiamaci.',
        ),
    ],
    "it-grammar-B2-10": [  # Discorso indiretto (10)
        (
            'Complete: Ha detto che ___ stanco.',
            ['era', 'è', 'sia', 'sarà'],
            0,
            'Discurso indiretto: presente → imperfetto (concordância temporal).',
            'Ha detto che era stanco.',
        ),
        (
            'Complete: Mi ha chiesto se ___ andare con lui.',
            ['volessi', 'volevo', 'voglio', 'vorrò'],
            1,
            'Pergunta indireta: presente → imperfetto.',
            'Mi ha chiesto se volevo andare con lui.',
        ),
        (
            'Complete: Hanno dichiarato che ___ il giorno dopo.',
            ['partono', 'sarebbero partiti', 'partiranno', 'partissero'],
            1,
            'Futuro no passado: futuro no direto → condizionale composto.',
            'Hanno dichiarato che sarebbero partiti il giorno dopo.',
        ),
        (
            'Complete: Lei ha negato di ___ mentito.',
            ['avere', 'aver', 'avesse', 'ha'],
            1,
            "Após 'negare di': infinito passato (aver mentito).",
            'Lei ha negato di aver mentito.',
        ),
        (
            'Complete: Mi ha promesso che ___ presto.',
            ['tornerà', 'torna', 'sarebbe tornato', 'tornasse'],
            2,
            'Promessa futura no passado: condizionale composto.',
            'Mi ha promesso che sarebbe tornato presto.',
        ),
        (
            'Complete: Ha spiegato perché ___ in ritardo.',
            ['arriva', 'arrivi', 'arriverà', 'era arrivato'],
            3,
            'Passado no direto → trapassato no indireto.',
            'Ha spiegato perché era arrivato in ritardo.',
        ),
        (
            'Complete: Ci hanno detto di ___ silenzio.',
            ['fare', 'facciamo', 'facessimo', 'faremo'],
            0,
            'Ordem/pedido: di + infinito.',
            'Ci hanno detto di fare silenzio.',
        ),
        (
            'Complete: Ha chiesto dove ___ le chiavi.',
            ['fossero', 'erano state', 'saranno', 'sono'],
            0,
            'Pergunta indireta com congiuntivo (registro formal) ou imperfetto; aqui congiuntivo.',
            'Ha chiesto dove fossero le chiavi.',
        ),
        (
            'Complete: Ha affermato di non ___ niente.',
            ['sappia', 'sapere', 'sa', 'sapeva'],
            1,
            'Verbo declarativo + di + infinito.',
            'Ha affermato di non sapere niente.',
        ),
        (
            'Complete: Mi ha detto che ___ il giorno prima.',
            ['era uscito', 'uscirà', 'esce', 'esca'],
            0,
            "'Ieri' → 'il giorno prima'; passato → trapassato.",
            'Mi ha detto che era uscito il giorno prima.',
        ),
    ],
    # --- Extra ---
    "it-grammar-extra-01": [  # Preposizioni (A1,5)
        (
            'Complete: Vivo ___ Roma.',
            ['di', 'in', 'a'],
            2,
            "Cidades: preposição 'a' (a Roma).",
            'Vivo a Roma.',
        ),
        (
            'Complete: Studio ___ Italia.',
            ['in', 'da', 'a'],
            0,
            "Países: preposição 'in'.",
            'Studio in Italia.',
        ),
        (
            'Complete: Il treno parte ___ Milano.',
            ['da', 'in', 'a'],
            0,
            "Origem/partida: 'da'.",
            'Il treno parte da Milano.',
        ),
        (
            'Complete: Il libro è ___ tavolo.',
            ['sul', 'al', 'nel'],
            0,
            'su + il = sul (em cima de).',
            'Il libro è sul tavolo.',
        ),
        (
            'Complete: Vado ___ scuola ogni giorno.',
            ['di', 'a', 'in'],
            1,
            'Destino com lugares institucionais: a scuola.',
            'Vado a scuola ogni giorno.',
        ),
    ],
    "it-grammar-extra-02": [  # Congiunzioni (A2,6)
        (
            'Complete: Studio italiano ___ mi piace molto.',
            ['perché', 'ma', 'o'],
            0,
            "'Perché' introduz causa.",
            'Studio italiano perché mi piace molto.',
        ),
        (
            'Complete: Vorrei uscire, ___ piove.',
            ['o', 'e', 'ma'],
            2,
            "'Ma' contrasta ideias.",
            'Vorrei uscire, ma piove.',
        ),
        (
            'Complete: Prendi il tè ___ il caffè?',
            ['o', 'e', 'ma'],
            0,
            "'O' expressa alternativa.",
            'Prendi il tè o il caffè?',
        ),
        (
            'Complete: Finisco i compiti ___ esco.',
            ['però', 'e poi', 'oppure'],
            1,
            'Sequência temporal: e poi.',
            'Finisco i compiti e poi esco.',
        ),
        (
            'Complete: Non ho fame, ___ mangio qualcosa.',
            ['tuttavia', 'quindi', 'perché'],
            0,
            "'Tuttavia' = contudo (oposição).",
            'Non ho fame, tuttavia mangio qualcosa.',
        ),
        (
            'Complete: È tardi, ___ andiamo a casa.',
            ['mentre', 'sebbene', 'quindi'],
            2,
            "'Quindi' indica consequência.",
            'È tardi, quindi andiamo a casa.',
        ),
    ],
    "it-grammar-extra-03": [  # Essere/avere particularidades (A2,6)
        (
            "Complete: ___ vent'anni.",
            ['Sono', 'Ho', 'È'],
            1,
            'Idade em italiano: avere + anni.',
            "Ho vent'anni.",
        ),
        (
            'Complete: ___ fame: mangiamo!',
            ['Sono', 'Ho', 'Faccio'],
            1,
            'Sensação: avere fame.',
            'Ho fame: mangiamo!',
        ),
        (
            'Complete: Oggi ___ bel tempo.',
            ['ha', 'è ha', "c'è"],
            2,
            "Clima com 'c'è' / 'fa': c'è bel tempo.",
            "Oggi c'è bel tempo.",
        ),
        (
            'Complete: ___ paura del buio.',
            ['Faccio', 'Sono', 'Ho'],
            2,
            'Emoções: avere paura.',
            'Ho paura del buio.',
        ),
        (
            'Complete: Quanto ___ ? Due metri.',
            ['sei alto', 'fai alto', 'hai alto'],
            0,
            'Altura: essere alto (não avere).',
            'Quanto sei alto? Due metri.',
        ),
        (
            'Complete: ___ bisogno di aiuto.',
            ['Sono', 'Faccio', 'Ho'],
            2,
            'Necessidade: avere bisogno di.',
            'Ho bisogno di aiuto.',
        ),
    ],
    "it-grammar-extra-04": [  # Ci e ne (B1,8)
        (
            'Complete: Vai in palestra? Sì, ___ vado ogni giorno.',
            ['la', 'ci', 'ne', 'lo'],
            1,
            "'Ci' substitui complemento de lugar (in palestra).",
            'Vai in palestra? Sì, ci vado ogni giorno.',
        ),
        (
            'Complete: Hai delle mele? Sì, ___ ho tre.',
            ['le', 'li', 'ci', 'ne'],
            3,
            "'Ne' = di + quantidade/parte.",
            'Hai delle mele? Sì, ne ho tre.',
        ),
        (
            'Complete: Pensi ai problemi? Non ___ penso più.',
            ['lo', 'ci', 'li', 'ne'],
            1,
            "'Pensare a' → ci penso.",
            'Pensi ai problemi? Non ci penso più.',
        ),
        (
            'Complete: Quanti fratelli hai? ___ ho due.',
            ['Ci', 'Ne', 'Gli', 'Li'],
            1,
            "Quantidade com 'ne'.",
            'Quanti fratelli hai? Ne ho due.',
        ),
        (
            "Complete: C'è del pane? Sì, ___ è ancora.",
            ['ce', 'ci ne', 'lo', 'ne'],
            0,
            "c'è + ne → ce n'è (aqui: ce n'è ancora).",
            "C'è del pane? Sì, ce n'è ancora.",
        ),
        (
            'Complete: Ti piace la città? Sì, ___ abito da anni.',
            ['ci', 'la', 'vi', 'ne'],
            0,
            "'Abitare in' → ci abito.",
            'Ti piace la città? Sì, ci abito da anni.',
        ),
        (
            'Complete: Parli di politica? Non ___ parlo volentieri.',
            ['la', 'lo', 'ci', 'ne'],
            3,
            "'Parlare di' → ne parlo.",
            'Parli di politica? Non ne parlo volentieri.',
        ),
        (
            'Complete: Sei andato al mare? No, non ___ sono andato.',
            ['ne', 'ci', 'vi', 'lo'],
            1,
            'Lugar com movimento: non ci sono andato.',
            'Sei andato al mare? No, non ci sono andato.',
        ),
    ],
    "it-grammar-extra-05": [  # Connettivi (B1,8)
        (
            'Complete: ___ fosse tardi, siamo restati.',
            ['Oppure', 'Sebbene', 'Perché', 'Quindi'],
            1,
            "'Sebbene' + congiuntivo (concessão).",
            'Sebbene fosse tardi, siamo restati.',
        ),
        (
            "Complete: Ha studiato poco; ___ non ha passato l'esame.",
            ['affinché', 'sebbene', 'mentre', 'di conseguenza'],
            3,
            'Conector de consequência: di conseguenza.',
            "Ha studiato poco; di conseguenza non ha passato l'esame.",
        ),
        (
            'Complete: ___ tu prepari la cena, io apparecchio.',
            ['Affinché', 'Poiché', 'Mentre', 'Sebbene'],
            2,
            "'Mentre' = enquanto (simultaneidade).",
            'Mentre tu prepari la cena, io apparecchio.',
        ),
        (
            'Complete: Ti chiamo ___ tu sappia la verità.',
            ['perché', 'affinché', 'mentre', 'quindi'],
            1,
            "'Affinché' + congiuntivo (finalidade).",
            'Ti chiamo affinché tu sappia la verità.',
        ),
        (
            'Complete: ___ pioveva, siamo usciti lo stesso.',
            ['Infatti', 'Anche se', 'Oppure', 'Quindi'],
            1,
            "'Anche se' = mesmo se (concessão).",
            'Anche se pioveva, siamo usciti lo stesso.',
        ),
        (
            'Complete: Non è venuto; ___ era malato.',
            ['oppure', 'mentre', 'infatti', 'tuttavia'],
            2,
            "'Infatti' confirma/explica.",
            'Non è venuto; infatti era malato.',
        ),
        (
            "Complete: Preferisco il treno ___ l'aereo.",
            ['poiché', 'quindi', 'affinché', 'anziché'],
            3,
            "'Anziché' = em vez de.",
            "Preferisco il treno anziché l'aereo.",
        ),
        (
            'Complete: ___ hai finito, possiamo partire.',
            ['Dato che', 'Sebbene', 'Affinché', 'Anziché'],
            0,
            "'Dato che' = visto que (causa).",
            'Dato che hai finito, possiamo partire.',
        ),
    ],
    "it-grammar-extra-06": [  # Verbi pronominali (B1,8)
        (
            'Complete: Mi ___ ogni mattina alle sette.',
            ['alza', 'alzo', 'alzi', 'alziamo'],
            1,
            "'Alzarsi': io mi alzo.",
            'Mi alzo ogni mattina alle sette.',
        ),
        (
            'Complete: Come ti ___ ?',
            ['chiama', 'chiami', 'chiamate', 'chiamo'],
            1,
            "'Chiamarsi': tu ti chiami.",
            'Come ti chiami?',
        ),
        (
            'Complete: Ci ___ alle nove davanti al cinema.',
            ['vedo', 'vediamo', 'vedete', 'vedono'],
            1,
            "'Vedersi': ci vediamo (encontro).",
            'Ci vediamo alle nove davanti al cinema.',
        ),
        (
            'Complete: Non ___ ricordato del tuo compleanno.',
            ['mi sono', 'sono', 'ho', 'mi ho'],
            0,
            'Verbos pronominais no composto: essere + mi sono ricordato.',
            'Non mi sono ricordato del tuo compleanno.',
        ),
        (
            'Complete: Si ___ sempre di politica a cena.',
            ['parlano', 'parlate', 'parla', 'parliamo'],
            2,
            "'Si' impersonale: si parla.",
            'Si parla sempre di politica a cena.',
        ),
        (
            'Complete: Me ne ___ a casa presto.',
            ['andate', 'vado', 'andiamo', 'va'],
            1,
            "'Andarsene': me ne vado.",
            'Me ne vado a casa presto.',
        ),
        (
            'Complete: Ce la ___ a finire in tempo.',
            ['facciamo', 'faremo', 'fare', 'facciamo ce'],
            1,
            "'Farcela': ce la faremo.",
            'Ce la faremo a finire in tempo.',
        ),
        (
            'Complete: Non ___ con questa grammatica!',
            ['la faccio', 'ci faccio', 'mi faccio', 'ce la faccio'],
            3,
            "'Farcela' negativo: non ce la faccio.",
            'Non ce la faccio con questa grammatica!',
        ),
    ],
    "it-grammar-extra-07": [  # Congiuntivo e ipotetico (B2,10)
        (
            'Complete: Se ___ , te lo direi.',
            ['lo sapessi', 'lo saprò', 'lo so', 'lo sapevo'],
            0,
            'II tipo: se + congiuntivo imperfetto.',
            'Se lo sapessi, te lo direi.',
        ),
        (
            'Complete: Temo che non ___ in tempo.',
            ['arrivi', 'arriverà', 'arriva', 'arrivava'],
            0,
            "'Temere che' + congiuntivo.",
            'Temo che non arrivi in tempo.',
        ),
        (
            'Complete: Se mi avessero avvisato, ___ venuto.',
            ['verrei', 'sono', 'sarei', 'venissi'],
            2,
            'III tipo: condizionale passato (sarei venuto).',
            'Se mi avessero avvisato, sarei venuto.',
        ),
        (
            'Complete: È meglio che ___ subito.',
            ['partiate', 'partirete', 'partivate', 'partite'],
            0,
            'Juízo de valor + congiuntivo: partiate.',
            'È meglio che partiate subito.',
        ),
        (
            'Complete: Qualora ___ necessario, interverremo.',
            ['sarà', 'era', 'fosse', 'è'],
            2,
            "'Qualora' + congiuntivo.",
            'Qualora fosse necessario, interverremo.',
        ),
        (
            'Complete: Non pensavo che ___ così difficile.',
            ['sarà', 'sia stato', 'fosse', 'è'],
            2,
            'Opinião no passado + congiuntivo imperfetto.',
            'Non pensavo che fosse così difficile.',
        ),
        (
            'Complete: Se non ___ , avremmo perso tutto.',
            ["c'eri tu", 'ci sei tu', 'ci fossi stato tu', 'ci sarai tu'],
            2,
            "III tipo com 'esserci'.",
            'Se non ci fossi stato tu, avremmo perso tutto.',
        ),
        (
            'Complete: Benchè ___ giovane, è molto esperto.',
            ['era', 'sia', 'è', 'sarà'],
            1,
            "'Benchè' + congiuntivo.",
            'Benchè sia giovane, è molto esperto.',
        ),
        (
            'Complete: Se avessi più soldi, ___ una casa al mare.',
            ['comprerei', 'comprassi', 'compro', 'ho comprato'],
            0,
            'II tipo: condizionale presente no apodose.',
            'Se avessi più soldi, comprerei una casa al mare.',
        ),
        (
            'Complete: Dubitavo che loro ___ già partiti.',
            ['siano', 'erano', 'fossero', 'saranno'],
            2,
            'Dúvida no passado + trapassato congiuntivo.',
            'Dubitavo che loro fossero già partiti.',
        ),
    ],
    "it-grammar-extra-08": [  # Idiomi e collocazioni (B2,10)
        (
            'Complete: Non ___ senso protestare ora.',
            ['dà', 'fa', 'ha', 'è'],
            2,
            'Colocação: non ha senso.',
            'Non ha senso protestare ora.',
        ),
        (
            'Complete: Dobbiamo ___ una decisione.',
            ['mettere', 'dare', 'fare', 'prendere'],
            3,
            'Colocação: prendere una decisione.',
            'Dobbiamo prendere una decisione.',
        ),
        (
            'Complete: Mi ha ___ una mano con il trasloco.',
            ['dato', 'messo', 'fatto', 'preso'],
            0,
            'Idioma: dare una mano = ajudar.',
            'Mi ha dato una mano con il trasloco.',
        ),
        (
            'Complete: Non ___ col fuoco con questo argomento.',
            ['fare', 'prendere', 'giocare', 'mettere'],
            2,
            'Idioma: giocare col fuoco.',
            'Non giocare col fuoco con questo argomento.',
        ),
        (
            'Complete: Ha ___ i nervi durante la riunione.',
            ['dato', 'preso', 'perso', 'fatto'],
            2,
            'Colocação: perdere i nervi.',
            'Ha perso i nervi durante la riunione.',
        ),
        (
            'Complete: Non ___ parola di quello che ti ho detto.',
            ['mettere', 'dire', 'prendere', 'fare'],
            1,
            'Idioma: non dire parola.',
            'Non dire parola di quello che ti ho detto.',
        ),
        (
            'Complete: Dobbiamo ___ conto delle spese.',
            ['fare', 'dare', 'prendere', 'tenere'],
            3,
            'Colocação: tenere conto di.',
            'Dobbiamo tenere conto delle spese.',
        ),
        (
            "Complete: L'idea non mi ___ convincente.",
            ['sembra', 'ha', 'fa', 'dà'],
            0,
            'Colocação: sembrare + aggettivo.',
            "L'idea non mi sembra convincente.",
        ),
        (
            'Complete: Ha ___ un errore grave.',
            ['commesso', 'dato', 'preso', 'fatto stato'],
            0,
            'Colocação formal: commettere un errore (também: fare un errore).',
            'Ha commesso un errore grave.',
        ),
        (
            'Complete: Non ___ di vista i tuoi obiettivi.',
            ['mettere', 'fare', 'dare', 'perdere'],
            3,
            'Idioma: non perdere di vista.',
            'Non perdere di vista i tuoi obiettivi.',
        ),
    ],
    # --- Complete A1 ---
    "it-grammar-complete-a1-01": [  # Pronomi personali (5)
        (
            'Complete: ___ sono italiano.',
            ['Io', 'Lui', 'Tu'],
            0,
            'Pronome sujeito 1ª pessoa: io.',
            'Io sono italiano.',
        ),
        (
            'Complete: ___ sei studente?',
            ['Io', 'Tu', 'Noi'],
            1,
            'Pronome 2ª pessoa singular: tu.',
            'Tu sei studente?',
        ),
        (
            'Complete: ___ abitiamo a Firenze.',
            ['Loro', 'Noi', 'Voi'],
            1,
            'Pronome 1ª pessoa plural: noi.',
            'Noi abitiamo a Firenze.',
        ),
        (
            'Complete: Dove andate ___ ?',
            ['loro', 'noi', 'voi'],
            2,
            'Pronome 2ª pessoa plural: voi.',
            'Dove andate voi?',
        ),
        (
            'Complete: ___ lavorano in banca.',
            ['Tu', 'Noi', 'Loro'],
            2,
            'Pronome 3ª pessoa plural: loro.',
            'Loro lavorano in banca.',
        ),
    ],
    "it-grammar-complete-a1-02": [  # Presente regolare (5)
        (
            'Complete: Io ___ in un ufficio.',
            ['lavora', 'lavoro', 'lavori'],
            1,
            'Presente -are: io lavor-o.',
            'Io lavoro in un ufficio.',
        ),
        (
            'Complete: Tu ___ molte email.',
            ['scrivo', 'scrive', 'scrivi'],
            2,
            'Presente -ere: tu scriv-i.',
            'Tu scrivi molte email.',
        ),
        (
            'Complete: Lei ___ alle otto.',
            ['parte', 'parti', 'parto'],
            0,
            'Presente -ire: lei part-e.',
            'Lei parte alle otto.',
        ),
        (
            'Complete: Noi ___ la televisione.',
            ['guardiamo', 'guardano', 'guardate'],
            0,
            'Presente -are: noi guard-iamo.',
            'Noi guardiamo la televisione.',
        ),
        (
            'Complete: Loro ___ il giornale.',
            ['leggono', 'leggete', 'leggiamo'],
            0,
            'Presente -ere: loro legg-ono.',
            'Loro leggono il giornale.',
        ),
    ],
    "it-grammar-complete-a1-03": [  # Essere, avere e c'è (5)
        (
            'Complete: ___ un libro sul tavolo.',
            ['Ha', 'Ci sono', "C'è"],
            2,
            "Existência singular: c'è.",
            "C'è un libro sul tavolo.",
        ),
        (
            'Complete: ___ due sedie in cucina.',
            ["C'è", 'Ci sono', 'Hanno'],
            1,
            'Existência plural: ci sono.',
            'Ci sono due sedie in cucina.',
        ),
        (
            'Complete: Lei ___ una sorella.',
            ["c'è", 'ha', 'è'],
            1,
            'Posse: avere.',
            'Lei ha una sorella.',
        ),
        (
            'Complete: Marco ___ medico.',
            ["c'è", 'ha', 'è'],
            2,
            'Profissão: essere.',
            'Marco è medico.',
        ),
        (
            'Complete: Quanti studenti ___ in classe?',
            ['hanno', 'ci sono', "c'è"],
            1,
            'Pergunta de existência plural: ci sono.',
            'Quanti studenti ci sono in classe?',
        ),
    ],
    "it-grammar-complete-a1-04": [  # Andare, venire, fare, stare (5)
        (
            'Complete: Dove ___ stasera?',
            ['fai', 'vai', 'viene'],
            1,
            "Presente de 'andare': tu vai.",
            'Dove vai stasera?',
        ),
        (
            'Complete: ___ da Roma in treno.',
            ['Vengo', 'Sto', 'Vado'],
            0,
            "'Venire' = vir de: vengo da.",
            'Vengo da Roma in treno.',
        ),
        (
            'Complete: Che cosa ___ di lavoro?',
            ['vai', 'fai', 'stai'],
            1,
            "'Fare' para ocupação: che cosa fai?",
            'Che cosa fai di lavoro?',
        ),
        (
            'Complete: Come ___ ? Bene, grazie.',
            ['stai', 'vai', 'fai'],
            0,
            "'Stare' para estado: come stai?",
            'Come stai? Bene, grazie.',
        ),
        (
            'Complete: Oggi ___ bel tempo.',
            ['fa', 'sta', 'va'],
            0,
            'Clima: fa bel tempo / fa caldo.',
            'Oggi fa bel tempo.',
        ),
    ],
    "it-grammar-complete-a1-05": [  # Potere, volere, dovere (5)
        (
            'Complete: ___ venire con te?',
            ['Devo', 'Posso', 'Voglio'],
            1,
            "'Potere' = poder/capacidade ou permissão.",
            'Posso venire con te?',
        ),
        (
            'Complete: ___ un caffè, per favore.',
            ['Posso', 'Vorrei', 'Devo'],
            1,
            "'Vorrei' (condizionale di volere) é pedido educado.",
            'Vorrei un caffè, per favore.',
        ),
        (
            "Complete: ___ studiare per l'esame.",
            ['Voglio solo', 'Devo', 'Posso'],
            1,
            "'Dovere' = obrigação.",
            "Devo studiare per l'esame.",
        ),
        (
            'Complete: Non ___ uscire stasera: lavoro.',
            ['voglio', 'devo', 'posso'],
            2,
            'Impossibilidade: non posso.',
            'Non posso uscire stasera: lavoro.',
        ),
        (
            'Complete: ___ aiutarci, per favore?',
            ['Dovete', 'Volete solo', 'Potete'],
            2,
            "Pedido com 'potere': potete...?",
            'Potete aiutarci, per favore?',
        ),
    ],
    "it-grammar-complete-a1-06": [  # Interrogativi (5)
        (
            'Complete: ___ ti chiami?',
            ['Come', 'Dove', 'Quando'],
            0,
            "'Come' = como (nome).",
            'Come ti chiami?',
        ),
        (
            'Complete: ___ abiti?',
            ['Quanto', 'Dove', 'Chi'],
            1,
            "'Dove' = onde.",
            'Dove abiti?',
        ),
        (
            'Complete: ___ parti?',
            ['Come', 'Dove', 'Quando'],
            2,
            "'Quando' = quando.",
            'Quando parti?',
        ),
        (
            'Complete: ___ è quella ragazza?',
            ['Chi', 'Che', 'Quanto'],
            0,
            "'Chi' = quem (pessoas).",
            'Chi è quella ragazza?',
        ),
        (
            'Complete: ___ costa questo libro?',
            ['Dove', 'Come', 'Quanto'],
            2,
            "'Quanto' = quanto (preço/quantidade).",
            'Quanto costa questo libro?',
        ),
    ],
    "it-grammar-complete-a1-07": [  # Articoli (5)
        (
            'Complete: ___ amico di Paolo è gentile.',
            ['Il', "L'", 'Lo'],
            1,
            "Antes de vogal: l' (l'amico).",
            "L'amico di Paolo è gentile.",
        ),
        (
            'Complete: ___ zaino è pesante.',
            ['Il', 'Lo', 'La'],
            1,
            'Masculino com z: lo zaino.',
            'Lo zaino è pesante.',
        ),
        (
            'Complete: ___ università è moderna.',
            ['Il', "L'", 'La'],
            1,
            "Feminino + vogal: l'università.",
            "L'università è moderna.",
        ),
        (
            'Complete: ___ amici arrivano presto.',
            ['Le', 'Gli', 'I'],
            1,
            'Plural masculino + vogal: gli amici.',
            'Gli amici arrivano presto.',
        ),
        (
            'Complete: Compra ___ pane, per favore.',
            ['lo', 'la', 'il'],
            2,
            'Masculino singular comum: il pane.',
            'Compra il pane, per favore.',
        ),
    ],
    # --- Complete A2 ---
    "it-grammar-complete-a2-01": [  # Passato prossimo (6)
        (
            'Complete: Ieri ___ una bella passeggiata.',
            ['ho fatto', 'sono fatto', 'facevo'],
            0,
            "'Fare' no passato prossimo: avere + fatto.",
            'Ieri ho fatto una bella passeggiata.',
        ),
        (
            'Complete: Laura ___ partita per Napoli.',
            ['sono', 'è', 'ha'],
            1,
            "'Partire' usa 'essere' no passato prossimo; particípio concorda.",
            'Laura è partita per Napoli.',
        ),
        (
            'Complete: Abbiamo ___ molto durante le vacanze.',
            ['viaggiato', 'viaggiati', 'viaggiare'],
            0,
            'Com avere, particípio invariável (viaggiato).',
            'Abbiamo viaggiato molto durante le vacanze.',
        ),
        (
            'Complete: I bambini ___ nati a Roma.',
            ['hanno', 'è', 'sono'],
            2,
            "'Nascere' usa essere; particípio concorda.",
            'I bambini sono nati a Roma.',
        ),
        (
            'Complete: Hai ___ il mio messaggio?',
            ['ricevere', 'ricevevi', 'ricevuto'],
            2,
            'Participio: ricevuto.',
            'Hai ricevuto il mio messaggio?',
        ),
        (
            'Complete: Non ___ ancora deciso.',
            ['è', 'sono', 'ho'],
            2,
            "'Decidere' + avere.",
            'Non ho ancora deciso.',
        ),
    ],
    "it-grammar-complete-a2-02": [  # Imperfetto (6)
        (
            'Complete: Da piccolo ___ a Firenze.',
            ['ho abitato', 'abiterò', 'abitavo'],
            2,
            'Descrição/hábito passado: imperfetto.',
            'Da piccolo abitavo a Firenze.',
        ),
        (
            'Complete: Mentre ___ , ascoltavo la radio.',
            ['ho cucinato', 'cucinerò', 'cucinavo'],
            2,
            'Ação em progresso: imperfetto.',
            'Mentre cucinavo, ascoltavo la radio.',
        ),
        (
            'Complete: Ieri ___ bel tempo.',
            ['ha fatto', 'faceva', 'farà'],
            1,
            'Clima no passado descritivo: faceva.',
            'Ieri faceva bel tempo.',
        ),
        (
            'Complete: Loro ___ sempre in ritardo.',
            ['sono arrivati', 'arriveranno', 'arrivavano'],
            2,
            'Hábito repetido: imperfetto.',
            'Loro arrivavano sempre in ritardo.',
        ),
        (
            'Complete: Non ___ cosa fare.',
            ['ho saputo', 'saprò', 'sapevo'],
            2,
            'Estado mental: imperfetto di sapere.',
            'Non sapevo cosa fare.',
        ),
        (
            'Complete: Quando ero giovane, ___ molto.',
            ['leggevo', 'leggerò', 'ho letto'],
            0,
            'Costume no passado: imperfetto.',
            'Quando ero giovane, leggevo molto.',
        ),
    ],
    "it-grammar-complete-a2-03": [  # Futuro semplice (6)
        (
            'Complete: Tra un mese ___ a New York.',
            ['parto', 'partivo', 'partirò'],
            2,
            'Futuro: io partirò.',
            'Tra un mese partirò a New York.',
        ),
        (
            'Complete: Domani ___ il contratto.',
            ['firmiamo', 'firmavamo', 'firmeremo'],
            2,
            'Futuro -are: firmeremo.',
            'Domani firmeremo il contratto.',
        ),
        (
            'Complete: Quando ___ i risultati?',
            ['arrivavano', 'arrivano', 'arriveranno'],
            2,
            'Futuro 3ª plural: arriveranno.',
            'Quando arriveranno i risultati?',
        ),
        (
            'Complete: Non ___ più questi errori.',
            ['faccio', 'farò', 'facevo'],
            1,
            "Futuro irregular di 'fare': farò.",
            'Non farò più questi errori.',
        ),
        (
            'Complete: Loro ___ una soluzione.',
            ['trovavano', 'troveranno', 'trovano'],
            1,
            'Futuro: troveranno.',
            'Loro troveranno una soluzione.',
        ),
        (
            'Complete: Tra poco ___ buio.',
            ['farà', 'fa', 'faceva'],
            0,
            "Futuro di 'fare' (clima/hora): farà buio.",
            'Tra poco farà buio.',
        ),
    ],
    "it-grammar-complete-a2-04": [  # Comparativi e superlativi (6)
        (
            'Complete: Marco è ___ alto di Luca.',
            ['meno molto', 'il più', 'più'],
            2,
            'Comparativo de superioridade: più ... di.',
            'Marco è più alto di Luca.',
        ),
        (
            'Complete: Questo film è ___ interessante del primo.',
            ['più il', 'meno', 'il meno'],
            1,
            'Comparativo de inferioridade: meno ... di.',
            'Questo film è meno interessante del primo.',
        ),
        (
            'Complete: Anna è ___ ragazza della classe.',
            ['più intelligente', 'la più intelligente', 'meno intelligente'],
            1,
            'Superlativo relativo: la più + adj + di.',
            'Anna è la più intelligente ragazza della classe.',
        ),
        (
            'Complete: Oggi sto ___ di ieri.',
            ['il meglio', 'più buono', 'meglio'],
            2,
            "Comparativo irregular de 'bene': meglio.",
            'Oggi sto meglio di ieri.',
        ),
        (
            'Complete: Questo è ___ ristorante della città.',
            ['più buono', 'meglio', 'il migliore'],
            2,
            "Superlativo irregular di 'buono': il migliore.",
            'Questo è il migliore ristorante della città.',
        ),
        (
            'Complete: Lui parla ___ di me.',
            ['il peggiore', 'più male', 'peggio'],
            2,
            "Comparativo irregular di 'male': peggio.",
            'Lui parla peggio di me.',
        ),
    ],
    "it-grammar-complete-a2-05": [  # Pronomi diretti e indiretti (6)
        (
            'Complete: Vedi Maria? Sì, ___ vedo.',
            ['li', 'la', 'le'],
            1,
            'Objeto direto feminino singular: la.',
            'Vedi Maria? Sì, la vedo.',
        ),
        (
            'Complete: Parli a Paolo? Sì, ___ telefono spesso.',
            ['gli', 'lo', 'li'],
            0,
            'Objeto indireto masculino: gli (a lui).',
            'Parli a Paolo? Sì, gli telefono spesso.',
        ),
        (
            'Complete: Hai i libri? Sì, ___ ho.',
            ['gli', 'le', 'li'],
            2,
            'Objeto direto masculino plural: li.',
            'Hai i libri? Sì, li ho.',
        ),
        (
            'Complete: Scrivi a Laura? Sì, ___ scrivo ogni giorno.',
            ['le', 'la', 'gli'],
            0,
            'Objeto indireto feminino: le (a lei).',
            'Scrivi a Laura? Sì, le scrivo ogni giorno.',
        ),
        (
            'Complete: Conosci i miei genitori? Sì, ___ conosco bene.',
            ['li', 'gli', 'le'],
            0,
            'Direto plural masculino: li.',
            'Conosci i miei genitori? Sì, li conosco bene.',
        ),
        (
            'Complete: Mi dai la penna? Sì, ___ do.',
            ['te la', 'la ti', 'ti la'],
            0,
            'Combinado: ti + la → te la.',
            'Mi dai la penna? Sì, te la do.',
        ),
    ],
    # --- Complete B1 ---
    "it-grammar-complete-b1-01": [  # Passato prossimo ou imperfetto (8)
        (
            'Complete: Quando ___ giovane, giocavo a calcio.',
            ['ero', 'fossi', 'sarò', 'sono stato'],
            0,
            'Descrição de idade/estado: imperfetto.',
            'Quando ero giovane, giocavo a calcio.',
        ),
        (
            'Complete: Ieri sera ___ un incidente.',
            ["c'era", "c'è stato", 'ci fosse', 'ci sarà'],
            1,
            "Evento pontual: passato prossimo (c'è stato).",
            "Ieri sera c'è stato un incidente.",
        ),
        (
            'Complete: Mentre ___ , ho visto un amico.',
            ['ho passeggiato', 'passeggerò', 'passeggiassi', 'passeggiavo'],
            3,
            'Fundo contínuo + interrupção: imperfetto.',
            'Mentre passeggiavo, ho visto un amico.',
        ),
        (
            "Complete: L'anno scorso ___ tre volte a Parigi.",
            ['andassi', 'sono andato', 'andavo', 'andrò'],
            1,
            'Número definido de vezes: passato prossimo.',
            "L'anno scorso sono andato tre volte a Parigi.",
        ),
        (
            'Complete: In quel periodo ___ molto stressato.',
            ['ero', 'sarò', 'sono stato una volta', 'sia'],
            0,
            'Estado duradouro: imperfetto.',
            'In quel periodo ero molto stressato.',
        ),
        (
            "Complete: All'improvviso ___ la luce.",
            ['si spenga', 'si è spenta', 'si spegneva', 'si spegnerà'],
            1,
            'Evento súbito: passato prossimo.',
            "All'improvviso si è spenta la luce.",
        ),
        (
            'Complete: Ogni estate ___ al mare.',
            ['andavamo', 'siamo andati', 'andremo', 'andassimo'],
            0,
            'Repetição habitual: imperfetto.',
            'Ogni estate andavamo al mare.',
        ),
        (
            'Complete: Finalmente ___ la verità.',
            ['ho scoperto', 'scoprirò', 'scoprivo', 'scoprissi'],
            0,
            'Descoberta pontual: passato prossimo.',
            'Finalmente ho scoperto la verità.',
        ),
    ],
    "it-grammar-complete-b1-02": [  # Condizionale presente (8)
        (
            'Complete: ___ un consiglio, se possibile.',
            ['Volessi', 'Voglio', 'Volevo', 'Vorrei'],
            3,
            'Pedido educado: condizionale di volere.',
            'Vorrei un consiglio, se possibile.',
        ),
        (
            'Complete: Con più tempo, ___ meglio.',
            ['lavoro', 'lavoravo', 'lavorassi', 'lavorerei'],
            3,
            'Condizionale presente: hipótese.',
            'Con più tempo, lavorerei meglio.',
        ),
        (
            'Complete: ___ venire, ma non posso.',
            ['Voglio', 'Vorrei stato', 'Volessi', 'Vorrei'],
            3,
            'Desejo + obstáculo: vorrei.',
            'Vorrei venire, ma non posso.',
        ),
        (
            'Complete: Secondo me, ___ partire subito.',
            ['dobbiamo stati', 'dovevamo', 'dobbiamo', 'dovremmo'],
            3,
            'Conselho suave: condizionale di dovere.',
            'Secondo me, dovremmo partire subito.',
        ),
        (
            'Complete: Cosa ___ al mio posto?',
            ['facessi', 'fai', 'faresti', 'facevi'],
            2,
            'Condizionale 2ª pessoa: faresti.',
            'Cosa faresti al mio posto?',
        ),
        (
            'Complete: ___ utile avere più informazioni.',
            ['È', 'Sarebbe', 'Era', 'Sarà'],
            1,
            'Juízo hipotético: sarebbe.',
            'Sarebbe utile avere più informazioni.',
        ),
        (
            'Complete: Non ___ mai una cosa del genere.',
            ['direi', 'dico', 'dica', 'dicevo'],
            0,
            "Condizionale di 'dire': direi.",
            'Non direi mai una cosa del genere.',
        ),
        (
            'Complete: ___ volentieri aiutarvi.',
            ['Posso', 'Potrei', 'Potevo', 'Possa'],
            1,
            'Oferta educada: potrei.',
            'Potrei volentieri aiutarvi.',
        ),
    ],
    "it-grammar-complete-b1-03": [  # Pronomi relativi (8)
        (
            'Complete: Ecco il libro ___ ti ho parlato.',
            ['che', 'dove', 'di cui', 'il quale'],
            2,
            "'Parlare di' → di cui.",
            'Ecco il libro di cui ti ho parlato.',
        ),
        (
            'Complete: La ragazza ___ abita qui è simpatica.',
            ['di cui', 'che', 'cui', 'dove'],
            1,
            'Sujeito relativo: che.',
            'La ragazza che abita qui è simpatica.',
        ),
        (
            'Complete: La città ___ sono nato è piccola.',
            ['di cui', 'il quale', 'che', 'in cui'],
            3,
            'Lugar com preposição: in cui (ou dove).',
            'La città in cui sono nato è piccola.',
        ),
        (
            'Complete: Gli amici ___ ho inviato la mail sono partiti.',
            ['di cui', 'a cui', 'che', 'dove'],
            1,
            "'Inviare a' → a cui.",
            'Gli amici a cui ho inviato la mail sono partiti.',
        ),
        (
            'Complete: Questo è il motivo ___ sono venuto.',
            ['dove', 'di cui', 'che', 'per cui'],
            3,
            'Causa: per cui.',
            'Questo è il motivo per cui sono venuto.',
        ),
        (
            'Complete: La persona ___ ti fidi è onesta.',
            ['che', 'dove', 'a cui', 'di cui'],
            3,
            "'Fidarsi di' → di cui.",
            'La persona di cui ti fidi è onesta.',
        ),
        (
            'Complete: Il film ___ abbiamo visto era lungo.',
            ['di cui', 'dove', 'cui', 'che'],
            3,
            'Objeto direto: che.',
            'Il film che abbiamo visto era lungo.',
        ),
        (
            "Complete: Ecco l'ufficio ___ lavora mio padre.",
            ['il quale', 'che', 'di cui', 'dove'],
            3,
            'Lugar: dove (relativo).',
            "Ecco l'ufficio dove lavora mio padre.",
        ),
    ],
    "it-grammar-complete-b1-04": [  # Discorso indiretto (8)
        (
            'Complete: Ha detto che ___ contento.',
            ['sarà', 'è', 'era', 'sia'],
            2,
            'Presente → imperfetto no discurso indireto.',
            'Ha detto che era contento.',
        ),
        (
            'Complete: Mi ha chiesto se ___ fame.',
            ['ho', 'avrò', 'avessi', 'avevo'],
            3,
            'Pergunta indireta: presente → imperfetto.',
            'Mi ha chiesto se avevo fame.',
        ),
        (
            'Complete: Hanno promesso che ___ il giorno dopo.',
            ['verranno', 'vengono', 'venissero', 'sarebbero venuti'],
            3,
            'Futuro no passado: condizionale composto.',
            'Hanno promesso che sarebbero venuti il giorno dopo.',
        ),
        (
            'Complete: Ci ha detto di ___ attenzione.',
            ['faremo', 'facessimo', 'facciamo', 'fare'],
            3,
            'Ordem: di + infinito.',
            'Ci ha detto di fare attenzione.',
        ),
        (
            'Complete: Ha spiegato che ___ il giorno prima.',
            ['arrivi', 'arriva', 'arriverà', 'era arrivato'],
            3,
            "Passado → trapassato; 'ieri' → 'il giorno prima'.",
            'Ha spiegato che era arrivato il giorno prima.',
        ),
        (
            'Complete: Ha negato di ___ mentito.',
            ['avere', 'aver', 'avesse', 'ha'],
            1,
            'Negare di + infinito passato: aver mentito.',
            'Ha negato di aver mentito.',
        ),
        (
            'Complete: Mi ha chiesto dove ___ le chiavi.',
            ['fossero', 'siano state', 'sono', 'saranno'],
            0,
            'Pergunta indireta: congiuntivo ou imperfetto.',
            'Mi ha chiesto dove fossero le chiavi.',
        ),
        (
            'Complete: Ha affermato di non ___ niente.',
            ['sapere', 'sappia', 'sa', 'sapeva'],
            0,
            'Afirmare di + infinito.',
            'Ha affermato di non sapere niente.',
        ),
    ],
    # --- Complete B2 ---
    "it-grammar-complete-b2-01": [  # Condizionale passato (10)
        (
            'Complete: ___ chiamato, ma non avevo il numero.',
            ['Vorrei', 'Avrei', 'Chiamerei', 'Avevo'],
            1,
            'Condizionale passato: avrei chiamato (ação não realizada).',
            'Avrei chiamato, ma non avevo il numero.',
        ),
        (
            'Complete: Senza il tuo aiuto, non ___ finito.',
            ['avrei', 'finivo', 'avrei stato', 'finirei'],
            0,
            'Condizionale passato: non avrei finito.',
            'Senza il tuo aiuto, non avrei finito.',
        ),
        (
            'Complete: ___ venuto ieri, ma pioveva.',
            ['Verrei', 'Venissi', 'Sarei', 'Sono'],
            2,
            'Com essere: sarei venuto.',
            'Sarei venuto ieri, ma pioveva.',
        ),
        (
            'Complete: Chi ___ pensato una cosa simile?',
            ['pensava', 'penserebbe', 'avrebbe', 'avrebbe stato'],
            2,
            'Condizionale passato 3ª: avrebbe pensato.',
            'Chi avrebbe pensato una cosa simile?',
        ),
        (
            'Complete: ___ dovuto avvisarti prima.',
            ['Dovrei', 'Debba', 'Avrei', 'Dovevo'],
            2,
            'Lamento: avrei dovuto + infinito.',
            'Avrei dovuto avvisarti prima.',
        ),
        (
            "Complete: In quel caso, ___ accettato l'offerta.",
            ['avrei', 'accetterei', 'accettassi', 'accettavo'],
            0,
            'Hipótese passada: avrei accettato.',
            "In quel caso, avrei accettato l'offerta.",
        ),
        (
            'Complete: Non ___ mai immaginato un successo così.',
            ['avrei', 'immaginassi', 'immaginerei', 'immaginavo'],
            0,
            'Surpresa retrospectiva: non avrei mai immaginato.',
            'Non avrei mai immaginato un successo così.',
        ),
        (
            'Complete: ___ potuto aiutarti, se me lo avessi chiesto.',
            ['Avrei', 'Possa', 'Potrei', 'Potevo'],
            0,
            'Condizionale passato de potere: avrei potuto.',
            'Avrei potuto aiutarti, se me lo avessi chiesto.',
        ),
        (
            'Complete: Loro ___ partiti prima, ma il treno era pieno.',
            ['sarebbero', 'partivano', 'partirebbero', 'partissero'],
            0,
            'Condizionale passato com essere: sarebbero partiti.',
            'Loro sarebbero partiti prima, ma il treno era pieno.',
        ),
        (
            'Complete: ___ preferito restare a casa.',
            ['Avrei', 'Preferivo', 'Preferissi', 'Preferirei'],
            0,
            'Preferência no passado: avrei preferito.',
            'Avrei preferito restare a casa.',
        ),
    ],
    "it-grammar-complete-b2-02": [  # Periodo ipotetico misto (10)
        (
            'Complete: Se ___ studiato di più, ora non avresti problemi.',
            ['avevi', 'avessi', 'hai', 'avrai'],
            1,
            'Misto: passado irreal (trapassato) → consequência presente (condizionale).',
            'Se avessi studiato di più, ora non avresti problemi.',
        ),
        (
            'Complete: Se fossi più organizzato, ieri ___ finito in tempo.',
            ['avrei', 'finissi', 'finivo', 'finirei'],
            0,
            'Misto: condição presente irreal → consequência passada.',
            'Se fossi più organizzato, ieri avrei finito in tempo.',
        ),
        (
            'Complete: Se non ___ piovuto, oggi saremmo al mare.',
            ['pioveva', 'è', 'pioverà', 'fosse'],
            3,
            'Passado irreal → presente hipotético.',
            'Se non fosse piovuto, oggi saremmo al mare.',
        ),
        (
            'Complete: Se ___ ascoltato i consigli, adesso staresti meglio.',
            ['hai', 'ascoltavi', 'avessi', 'ascolterai'],
            2,
            'Trapassato na prótase + condizionale presente.',
            'Se avessi ascoltato i consigli, adesso staresti meglio.',
        ),
        (
            'Complete: Se fossi venuto ieri, oggi non ___ questi problemi.',
            ['avevi', 'avresti', 'avrai', 'hai'],
            1,
            'Misto III→II: avresti.',
            'Se fossi venuto ieri, oggi non avresti questi problemi.',
        ),
        (
            'Complete: Se non ___ così timido, avresti parlato ieri.',
            ['fossi', 'sarai', 'sei', 'eri'],
            0,
            'Condição presente → consequência passada.',
            'Se non fossi così timido, avresti parlato ieri.',
        ),
        (
            "Complete: Se ___ preso l'altro treno, ora saremmo già arrivati.",
            ['prendiamo', 'prenderemo', 'prendevamo', 'avessimo'],
            3,
            'Trapassato + condizionale composto (resultado até agora).',
            "Se avessimo preso l'altro treno, ora saremmo già arrivati.",
        ),
        (
            'Complete: Se fossi ricco, ___ già comprato quella casa.',
            ['avrei', 'compravo', 'comprerei', 'comprassi'],
            0,
            'II + III misto: avrei già comprato.',
            'Se fossi ricco, avrei già comprato quella casa.',
        ),
        (
            'Complete: Se mi ___ avvisato, adesso saprei cosa fare.',
            ['avessi', 'avevi', 'hai', 'avrai'],
            0,
            'Passado irreal → conhecimento presente.',
            'Se mi avessi avvisato, adesso saprei cosa fare.',
        ),
        (
            'Complete: Se non ___ malato, ieri saresti venuto.',
            ['fossi stato', 'sei', 'eri', 'sarai'],
            0,
            'Estado passado irreal → ação passada.',
            'Se non fossi stato malato, ieri saresti venuto.',
        ),
    ],
    "it-grammar-complete-b2-03": [  # Dislocazione e pronomi (10)
        (
            'Complete: Il caffè, ___ prendo dopo.',
            ['ci', 'ne', 'lo', 'gli'],
            2,
            'Dislocação à esquerda: objeto retomado por lo.',
            'Il caffè, lo prendo dopo.',
        ),
        (
            'Complete: A Maria, ___ ho già detto tutto.',
            ['lo', 'le lo', 'glielo', 'ne'],
            2,
            'Dislocação do indireto: glielo.',
            'A Maria, glielo ho già detto tutto.',
        ),
        (
            'Complete: Di problemi, ___ abbiamo tanti.',
            ['ne', 'lo', 'li', 'ci'],
            0,
            "Dislocação com 'di': ne.",
            'Di problemi, ne abbiamo tanti.',
        ),
        (
            'Complete: In montagna, ___ vado ogni estate.',
            ['ci', 'ne', 'la', 'vi lo'],
            0,
            'Lugar dislocado: ci.',
            'In montagna, ci vado ogni estate.',
        ),
        (
            'Complete: Queste chiavi, ___ hai viste?',
            ['li', 'ci', 'ne', 'le'],
            3,
            'Objeto feminino plural + acordo no particípio: le hai viste.',
            'Queste chiavi, le hai viste?',
        ),
        (
            'Complete: Ai ragazzi, ___ ho spiegato la regola.',
            ['li', 'la', 'ne', 'gliela'],
            3,
            'Indireto plural + direto: gliela.',
            'Ai ragazzi, gliela ho spiegato la regola.',
        ),
        (
            'Complete: Di libri, ___ leggo pochi.',
            ['lo', 'li', 'ci', 'ne'],
            3,
            'Quantidade partitiva: ne.',
            'Di libri, ne leggo pochi.',
        ),
        (
            'Complete: Quel film, non ___ ho ancora visto.',
            ['ne', 'gli', 'lo', 'ci'],
            2,
            'Dislocação: lo ho visto.',
            'Quel film, non lo ho ancora visto.',
        ),
        (
            'Complete: A casa, non ___ sono ancora tornato.',
            ['ci', 'lo', 'ne', 'la'],
            0,
            'Lugar com movimento: ci sono tornato.',
            'A casa, non ci sono ancora tornato.',
        ),
        (
            'Complete: La verità, ___ dobbiamo dire.',
            ['la ci', 'ce la', 'gli', 'ne'],
            1,
            "Combinado com 'dovere': ce la dobbiamo dire / dobbiamo dirla.",
            'La verità, ce la dobbiamo dire.',
        ),
    ],
    "it-grammar-complete-b2-04": [  # Gerundio e participio (10)
        (
            'Complete: ___ , ho incontrato un amico.',
            ['Uscito', 'Uscissi', 'Uscendo', 'Uscire'],
            2,
            'Gerundio = simultaneidade/meio: uscendo.',
            'Uscendo, ho incontrato un amico.',
        ),
        (
            'Complete: ___ i compiti, sono uscito.',
            ['Finissi', 'Finire', 'Finiti', 'Finendo'],
            2,
            'Participio assoluto: finiti i compiti.',
            'Finiti i compiti, sono uscito.',
        ),
        (
            "Complete: Ha imparato l'italiano ___ all'estero.",
            ['viva', 'vivendo', 'vivere', 'vissuto'],
            1,
            'Gerundio de meio/circunstância: vivendo.',
            "Ha imparato l'italiano vivendo all'estero.",
        ),
        (
            'Complete: ___ la notizia, è diventato pallido.',
            ['Sentendo', 'Senta', 'Sentita', 'Sentire'],
            2,
            'Participio (acordo): sentita la notizia.',
            'Sentita la notizia, è diventato pallido.',
        ),
        (
            'Complete: Camminando e ___, abbiamo perso tempo.',
            ['parlando', 'parlato', 'parlassimo', 'parlare'],
            0,
            'Dois gerúndios coordenados.',
            'Camminando e parlando, abbiamo perso tempo.',
        ),
        (
            'Complete: ___ da Roma, ha trovato lavoro subito.',
            ['Arrivato', 'Arrivare', 'Arrivando stato', 'Arrivi'],
            0,
            'Participio passato (sujeito implícito): arrivato.',
            'Arrivato da Roma, ha trovato lavoro subito.',
        ),
        (
            'Complete: Non ___ cosa dire, è rimasto in silenzio.',
            ['sappia', 'sapere', 'saputo', 'sapendo'],
            3,
            'Gerundio causal: non sapendo.',
            'Non sapendo cosa dire, è rimasto in silenzio.',
        ),
        (
            'Complete: ___ le luci, siamo andati a letto.',
            ['Spegnere', 'Spegendo', 'Spegnessimo', 'Spente'],
            3,
            'Participio absoluto: spente le luci.',
            'Spente le luci, siamo andati a letto.',
        ),
        (
            'Complete: Si è ferito ___ a calcio.',
            ['giocato', 'giocare', 'giochi', 'giocando'],
            3,
            'Gerundio circunstancial: giocando.',
            'Si è ferito giocando a calcio.',
        ),
        (
            'Complete: ___ il problema, abbiamo trovato la soluzione.',
            ['Capire', 'Capisca', 'Capito', 'Capendo stato'],
            2,
            'Participio: capito il problema.',
            'Capito il problema, abbiamo trovato la soluzione.',
        ),
    ],
    "it-grammar-complete-b2-05": [  # Verbi di discorso (10)
        (
            'Complete: Ha ___ che sarebbe arrivato tardi.',
            ['ordinato', 'detto', 'chiesto di', 'domandato'],
            1,
            "'Dire che' introduz declaração.",
            'Ha detto che sarebbe arrivato tardi.',
        ),
        (
            'Complete: Mi ha ___ se volevo uscire.',
            ['detto', 'negato', 'affermato', 'chiesto'],
            3,
            "'Chiedere se' = perguntar se.",
            'Mi ha chiesto se volevo uscire.',
        ),
        (
            'Complete: Ha ___ di essere innocente.',
            ['chiesto', 'ordinato', 'domandato', 'affermato'],
            3,
            "'Affermare di' + infinito.",
            'Ha affermato di essere innocente.',
        ),
        (
            'Complete: Ha ___ di aver mentito.',
            ['detto', 'promesso', 'negato', 'chiesto'],
            2,
            "'Negare di' + infinito passato.",
            'Ha negato di aver mentito.',
        ),
        (
            'Complete: Ci ha ___ di chiudere la porta.',
            ['detto che', 'chiesto se', 'ordinato', 'affermato'],
            2,
            "'Ordinare di' + infinito.",
            'Ci ha ordinato di chiudere la porta.',
        ),
        (
            'Complete: Ha ___ che avrebbe aiutato.',
            ['negato', 'promesso', 'ordinato', 'chiesto'],
            1,
            "'Promettere che' + futuro no passado.",
            'Ha promesso che avrebbe aiutato.',
        ),
        (
            'Complete: Gli ho ___ di non preoccuparsi.',
            ['affermato che', 'negato di', 'detto', 'chiesto se'],
            2,
            "'Dire di' + infinito (conselho/ordem).",
            'Gli ho detto di non preoccuparsi.',
        ),
        (
            'Complete: Ha ___ perché era in ritardo.',
            ['negato', 'spiegato', 'promesso', 'ordinato'],
            1,
            "'Spiegare perché'.",
            'Ha spiegato perché era in ritardo.',
        ),
        (
            'Complete: Mi ha ___ di prestarle la macchina.',
            ['negato', 'affermato', 'chiesto', 'detto che'],
            2,
            "'Chiedere di' + infinito (pedido).",
            'Mi ha chiesto di prestarle la macchina.',
        ),
        (
            'Complete: Hanno ___ che i prezzi sarebbero aumentati.',
            ['annunciato', 'chiesto', 'ordinato', 'negato di'],
            0,
            "'Annunciare che' + condizionale composto.",
            'Hanno annunciato che i prezzi sarebbero aumentati.',
        ),
    ],
    "it-grammar-complete-b2-06": [  # Espressioni frequenti (10)
        (
            'Complete: ___ di solito vado a letto presto.',
            ['Tra', 'Di', 'Con', 'Per'],
            1,
            'Expressão: di solito = normalmente.',
            'Di solito vado a letto presto.',
        ),
        (
            'Complete: ___ tanto, ci vediamo!',
            ['Con', 'Di', 'A', 'Per'],
            2,
            'Despedida: a tanto / a presto.',
            'A tanto, ci vediamo!',
        ),
        (
            "Complete: Non vedo l'ora ___ partire.",
            ['per', 'da', 'di', 'a'],
            2,
            "Expressão: non vedo l'ora di + infinito.",
            "Non vedo l'ora di partire.",
        ),
        (
            'Complete: ___ caso di pioggia, restiamo a casa.',
            ['Di', 'Per', 'In', 'A'],
            2,
            'Expressão: in caso di.',
            'In caso di pioggia, restiamo a casa.',
        ),
        (
            'Complete: ___ proposito, hai finito il report?',
            ['In', 'Di', 'Per', 'A'],
            3,
            'Mudança de assunto: a proposito.',
            'A proposito, hai finito il report?',
        ),
        (
            'Complete: Facciamo ___ che sia vero.',
            ['senso', 'forza', 'conto', 'caso'],
            2,
            'Expressão: fare conto che = imaginar/supor.',
            'Facciamo conto che sia vero.',
        ),
        (
            'Complete: ___ forza! Ce la farai.',
            ['Di', 'Per', 'Con', 'Dai'],
            3,
            'Encorajamento coloquial: Dai, forza!',
            'Dai forza! Ce la farai.',
        ),
        (
            "Complete: Sono d'accordo ___ te.",
            ['con', 'per', 'di', 'a'],
            0,
            "Expressão: essere d'accordo con.",
            "Sono d'accordo con te.",
        ),
        (
            'Complete: ___ volte a settimana vado in palestra.',
            ['Due', 'Di', 'Tra', 'Per'],
            0,
            'Frequência: due volte a settimana.',
            'Due volte a settimana vado in palestra.',
        ),
        (
            'Complete: ___ fretta di uscire.',
            ['Vado', 'Faccio', 'Sono', 'Ho'],
            3,
            'Expressão: avere fretta.',
            'Ho fretta di uscire.',
        ),
    ],
}


def get_banks() -> dict[str, list[tuple[str, list[str], int, str, str]]]:
    return BANKS
