# -*- coding: utf-8 -*-
"""French grammar cloze exercise banks keyed by topic_id.

Each item: (question, options_list, answer_index, explanation_pt_br, example_correct_sentence)
Counts/options by level: A1=5/3, A2=6/3, B1=8/4, B2=10/4.
"""

from __future__ import annotations

BANKS: dict[str, list[tuple[str, list[str], int, str, str]]] = {
    "fr-grammar-A1-1": [
        (
            "Complete: Je ___ étudiant.",
            ["suis", "ai", "est"],
            0,
            "Com o verbo être, a 1ª pessoa do singular é suis.",
            "Je suis étudiant.",
        ),
        (
            "Complete: Tu ___ un frère.",
            ["es", "as", "a"],
            1,
            "Avoir na 2ª pessoa do singular é as.",
            "Tu as un frère.",
        ),
        (
            "Complete: Elle ___ française.",
            ["a", "sont", "est"],
            2,
            "Être descreve nacionalidade e identidade.",
            "Elle est française.",
        ),
        (
            "Complete: Nous ___ faim.",
            ["avons", "sommes", "êtes"],
            0,
            "Expressões como avoir faim usam avoir, não être.",
            "Nous avons faim.",
        ),
        (
            "Complete: Ils ___ à Paris.",
            ["ont", "sont", "êtes"],
            1,
            "Être localiza; ils/elles usam sont.",
            "Ils sont à Paris.",
        ),
    ],
    "fr-grammar-A1-2": [
        (
            "Complete: ___ livre est intéressant.",
            ["La", "Les", "Le"],
            2,
            "Livre é masculino singular: artigo le.",
            "Le livre est intéressant.",
        ),
        (
            "Complete: C'est ___ amie.",
            ["une", "un", "des"],
            0,
            "Amie é feminino: une.",
            "C'est une amie.",
        ),
        (
            "Complete: Les maisons sont ___ .",
            ["blanc", "blanches", "blanche"],
            1,
            "Adjetivo concorda em gênero e número: femininas plurais → blanches.",
            "Les maisons sont blanches.",
        ),
        (
            "Complete: J'ai ___ pommes.",
            ["de la", "du", "des"],
            2,
            "Plural indeterminado: des + substantivo plural.",
            "J'ai des pommes.",
        ),
        (
            "Complete: ___ école est grande.",
            ["L'", "Le", "Les"],
            0,
            "École começa por vogal: L'école.",
            "L'école est grande.",
        ),
    ],
    "fr-grammar-A2-3": [
        (
            "Complete: Je ___ français tous les jours.",
            ["parles", "parle", "parlons"],
            1,
            "Verbos em -er: je + radical + e.",
            "Je parle français tous les jours.",
        ),
        (
            "Complete: Tu ___ à quelle heure ?",
            ["finit", "finissons", "finis"],
            2,
            "Finir (2º grupo): tu finis.",
            "Tu finis à quelle heure ?",
        ),
        (
            "Complete: Nous ___ le train.",
            ["prenons", "prend", "prenez"],
            0,
            "Prendre: nous prenons.",
            "Nous prenons le train.",
        ),
        (
            "Complete: Ils ___ au cinéma.",
            ["va", "vont", "allez"],
            1,
            "Aller: ils/elles vont.",
            "Ils vont au cinéma.",
        ),
        (
            "Complete: Elle ___ du café le matin.",
            ["bois", "buvez", "boit"],
            2,
            "Boire: il/elle/on boit.",
            "Elle boit du café le matin.",
        ),
        (
            "Complete: Vous ___ ici ?",
            ["habitez", "habites", "habite"],
            0,
            "Habiter: vous habitez.",
            "Vous habitez ici ?",
        ),
    ],
    "fr-grammar-A2-4": [
        (
            "Complete: Hier, j'___ mangé une pizza.",
            ["suis", "ai", "a"],
            1,
            "Manger conjuga-se com avoir no passé composé.",
            "Hier, j'ai mangé une pizza.",
        ),
        (
            "Complete: Elle ___ arrivée tôt.",
            ["a", "sont", "est"],
            2,
            "Verbos de movimento (arriver) usam être e o particípio concorda.",
            "Elle est arrivée tôt.",
        ),
        (
            "Complete: Nous ___ vu le film.",
            ["avons", "sommes", "êtes"],
            0,
            "Voir usa avoir: nous avons vu.",
            "Nous avons vu le film.",
        ),
        (
            "Complete: Ils ___ partis hier.",
            ["ont", "sont", "avez"],
            1,
            "Partir usa être; particípio no plural: partis.",
            "Ils sont partis hier.",
        ),
        (
            "Complete: Tu ___ fini ton travail ?",
            ["es", "a", "as"],
            2,
            "Finir com avoir: tu as fini.",
            "Tu as fini ton travail ?",
        ),
        (
            "Complete: Je ___ allé au marché.",
            ["suis", "ai", "est"],
            0,
            "Aller usa être: je suis allé(e).",
            "Je suis allé au marché.",
        ),
    ],
    "fr-grammar-A2-5": [
        (
            "Complete: Demain, je ___ appeler Marie.",
            ["va", "vais", "allez"],
            1,
            "Futur proche: aller no presente + infinitivo.",
            "Demain, je vais appeler Marie.",
        ),
        (
            "Complete: Nous ___ demain matin.",
            ["partons", "partions", "partirons"],
            2,
            "Futur simple: nous partirons.",
            "Nous partirons demain matin.",
        ),
        (
            "Complete: Tu ___ venir ce soir ?",
            ["vas", "va", "allez"],
            0,
            "Projeto próximo: tu vas + infinitivo.",
            "Tu vas venir ce soir ?",
        ),
        (
            "Complete: Ils ___ en France l'année prochaine.",
            ["habitent", "habiteront", "habitaient"],
            1,
            "Futur simples expressa planos ou previsões.",
            "Ils habiteront en France l'année prochaine.",
        ),
        (
            "Complete: Elle ___ un voyage en mai.",
            ["fait", "faisait", "fera"],
            2,
            "Faire no futur: elle fera.",
            "Elle fera un voyage en mai.",
        ),
        (
            "Complete: Vous ___ bientôt ?",
            ["allez partir", "partez allez", "partir allez"],
            0,
            "Futur proche com vous: vous allez + infinitivo.",
            "Vous allez partir bientôt ?",
        ),
    ],
    "fr-grammar-B1-6": [
        (
            "Complete: Quand j'étais enfant, je ___ souvent ici.",
            ["jouais", "ai joué", "jouerai", "joue"],
            0,
            "Hábito no passado → imparfait.",
            "Quand j'étais enfant, je jouais souvent ici.",
        ),
        (
            "Complete: Hier, il ___ à 8 heures.",
            ["arrivait", "est arrivé", "arrive", "arrivera"],
            1,
            "Evento pontual concluído → passé composé.",
            "Hier, il est arrivé à 8 heures.",
        ),
        (
            "Complete: Je ___ quand le téléphone a sonné.",
            ["ai lu", "lis", "lisais", "lirai"],
            2,
            "Ação em curso interrompida → imparfait + passé composé.",
            "Je lisais quand le téléphone a sonné.",
        ),
        (
            "Complete: Il ___ toute la matinée.",
            ["a plu", "pleut", "pleuvra", "pleuvait"],
            3,
            "Descrição / contexto climático → imparfait.",
            "Il pleuvait toute la matinée.",
        ),
        (
            "Complete: Soudain, elle ___ la porte.",
            ["a ouvert", "ouvrait", "ouvre", "ouvrira"],
            0,
            "Ação súbita na narrativa → passé composé.",
            "Soudain, elle a ouvert la porte.",
        ),
        (
            "Complete: À cette époque, nous ___ à Lyon.",
            ["avons habité", "habitions", "habitons", "habiterons"],
            1,
            "Situação duradoura no passado → imparfait.",
            "À cette époque, nous habitions à Lyon.",
        ),
        (
            "Complete: L'année dernière, ils ___ le projet.",
            ["terminaient", "terminent", "ont terminé", "termineront"],
            2,
            "Fato concluído em período fechado → passé composé.",
            "L'année dernière, ils ont terminé le projet.",
        ),
        (
            "Complete: Pendant que tu ___, j'ai préparé le dîner.",
            ["as dormi", "dors", "dormiras", "dormais"],
            3,
            "Fundo simultâneo → imparfait; evento → passé composé.",
            "Pendant que tu dormais, j'ai préparé le dîner.",
        ),
    ],
    "fr-grammar-B1-7": [
        (
            "Complete: Je ___ donne le livre.",
            ["lui", "le", "la", "leur"],
            0,
            "Complemento indireto de pessoa singular: lui.",
            "Je lui donne le livre.",
        ),
        (
            "Complete: Tu ___ vois demain ?",
            ["lui", "la", "leur", "y"],
            1,
            "Complemento direto feminino: la.",
            "Tu la vois demain ?",
        ),
        (
            "Complete: Nous ___ parlons souvent.",
            ["les", "le", "leur", "en"],
            2,
            "Complemento indireto plural: leur.",
            "Nous leur parlons souvent.",
        ),
        (
            "Complete: Il ___ a envoyés hier.",
            ["leur", "lui", "y", "les"],
            3,
            "COD plural antecede o auxiliar; particípio pode concordar.",
            "Il les a envoyés hier.",
        ),
        (
            "Complete: Elle m'___ a dit.",
            ["le", "lui", "leur", "en"],
            0,
            "Ordem: me + le antes do auxiliar (me l'a).",
            "Elle me l'a dit.",
        ),
        (
            "Complete: Je ___ téléphone ce soir.",
            ["le", "lui", "la", "les"],
            1,
            "Téléphoner à quelqu'un → lui.",
            "Je lui téléphone ce soir.",
        ),
        (
            "Complete: Tu ___ as déjà vus ?",
            ["leur", "lui", "les", "y"],
            2,
            "COD plural: les antes do auxiliar.",
            "Tu les as déjà vus ?",
        ),
        (
            "Complete: Donne-___ le document, s'il te plaît.",
            ["le", "leur", "en", "lui"],
            3,
            "Imperativo afirmativo: COD/COI depois do verbo com hífen.",
            "Donne-lui le document, s'il te plaît.",
        ),
    ],
    "fr-grammar-B1-8": [
        (
            "Complete: Il faut que tu ___ à l'heure.",
            ["sois", "es", "seras", "étais"],
            0,
            "Il faut que exige subjuntivo: tu sois.",
            "Il faut que tu sois à l'heure.",
        ),
        (
            "Complete: Je veux qu'elle ___ avec nous.",
            ["vient", "vienne", "viendra", "venait"],
            1,
            "Vouloir que + subjuntivo: elle vienne.",
            "Je veux qu'elle vienne avec nous.",
        ),
        (
            "Complete: Bien qu'il ___ tard, elle continue.",
            ["est", "sera", "soit", "était"],
            2,
            "Bien que + subjuntivo.",
            "Bien qu'il soit tard, elle continue.",
        ),
        (
            "Complete: Je doute qu'ils ___ prêts.",
            ["sont", "seront", "étaient", "soient"],
            3,
            "Douter que + subjuntivo: ils soient.",
            "Je doute qu'ils soient prêts.",
        ),
        (
            "Complete: Il est important que nous ___ demain.",
            ["partions", "partons", "partirons", "partaient"],
            0,
            "Expressões de importância + subjuntivo: nous partions.",
            "Il est important que nous partions demain.",
        ),
        (
            "Complete: Pourvu qu'il ___ beau !",
            ["fait", "fasse", "fera", "faisait"],
            1,
            "Pourvu que + subjuntivo: il fasse.",
            "Pourvu qu'il fasse beau !",
        ),
        (
            "Complete: Je suis contente que tu ___ réussi.",
            ["as", "auras", "aies", "avais"],
            2,
            "Emoção + que → subjuntivo (passé): tu aies réussi.",
            "Je suis contente que tu aies réussi.",
        ),
        (
            "Complete: Avant que vous ___, appelez-moi.",
            ["partez", "partirez", "partaient", "partiez"],
            3,
            "Avant que + subjuntivo: vous partiez.",
            "Avant que vous partiez, appelez-moi.",
        ),
    ],
    "fr-grammar-B2-9": [
        (
            "Complete: Si j'avais le temps, je ___ plus.",
            ["voyagerais", "voyage", "voyagerai", "voyageais"],
            0,
            "Hipótese irreal no presente: si + imparfait, conditionnel présent.",
            "Si j'avais le temps, je voyagerais plus.",
        ),
        (
            "Complete: Si tu ___ plus tôt, tu n'aurais pas raté le train.",
            ["pars", "étais parti", "partirais", "es parti"],
            1,
            "Hipótese passada: si + plus-que-parfait, conditionnel passé.",
            "Si tu étais parti plus tôt, tu n'aurais pas raté le train.",
        ),
        (
            "Complete: Si elle travaille bien, elle ___ le poste.",
            ["obtiendrait", "obtenait", "obtiendra", "a obtenu"],
            2,
            "Hipótese real/futura: si + présent, futur.",
            "Si elle travaille bien, elle obtiendra le poste.",
        ),
        (
            "Complete: À ta place, je ___ au directeur.",
            ["parle", "parlerai", "parlais", "parlerais"],
            3,
            "Conselho hipotético: conditionnel présent.",
            "À ta place, je parlerais au directeur.",
        ),
        (
            "Complete: S'il ___ plu, nous serions restés.",
            ["avait", "a", "aurait", "aura"],
            0,
            "Si + plus-que-parfait (il avait plu).",
            "S'il avait plu, nous serions restés.",
        ),
        (
            "Complete: Même si c'est difficile, je ___ essayer.",
            ["irais", "vais", "allais", "aille"],
            1,
            "Même si admite a realidade; pode combinar com futur proche.",
            "Même si c'est difficile, je vais essayer.",
        ),
        (
            "Complete: Si nous ___ riches, nous achèterions une maison.",
            ["sommes", "serons", "étions", "avons été"],
            2,
            "Si + imparfait para hipótese presente irreal.",
            "Si nous étions riches, nous achèterions une maison.",
        ),
        (
            "Complete: J'___ accepté avec plus d'informations.",
            ["avais", "aurai", "aie", "aurais"],
            3,
            "Conditionnel passé: hipótese ou arrependimento.",
            "J'aurais accepté avec plus d'informations.",
        ),
        (
            "Complete: Au cas où tu ___ besoin, appelle-moi.",
            ["aurais", "as", "aies", "avais"],
            0,
            "Au cas où + conditionnel.",
            "Au cas où tu aurais besoin, appelle-moi.",
        ),
        (
            "Complete: Sans ton aide, je n'___ pas réussi.",
            ["avais", "aurais", "aurai", "ai"],
            1,
            "Sans + nome equivale a hipótese; conditionnel passé no resultado.",
            "Sans ton aide, je n'aurais pas réussi.",
        ),
    ],
    "fr-grammar-B2-10": [
        (
            "Complete: Elle a dit qu'elle ___ prête.",
            ["est", "sera", "était", "soit"],
            2,
            "Discurso indireto no passado: présent → imparfait.",
            "Elle a dit qu'elle était prête.",
        ),
        (
            "Complete: Il m'a demandé si je ___.",
            ["viens", "viendrai", "vienne", "venais"],
            3,
            "Pergunta sim/não → si + recuo temporal.",
            "Il m'a demandé si je venais.",
        ),
        (
            "Complete: Elle a affirmé qu'elle ___ le rapport.",
            ["avait fini", "a fini", "finit", "finira"],
            0,
            "Passé composé no discurso direto → plus-que-parfait no indireto.",
            "Elle a affirmé qu'elle avait fini le rapport.",
        ),
        (
            "Complete: Il a promis qu'il ___ le lendemain.",
            ["vient", "viendrait", "viendra", "vienne"],
            1,
            "Futur no discurso direto → conditionnel no indireto passado.",
            "Il a promis qu'il viendrait le lendemain.",
        ),
        (
            "Complete: Elle m'a demandé où j'___.",
            ["habite", "habiterai", "habitais", "habiterais"],
            2,
            "Interrogativa parcial: palavra interrogativa + ordem afirmativa.",
            "Elle m'a demandé où j'habitais.",
        ),
        (
            "Complete: Il a dit qu'il ___ le lendemain.",
            ["part", "partira", "parte", "partirait"],
            3,
            "Demain → le lendemain; futur → conditionnel.",
            "Il a dit qu'il partirait le lendemain.",
        ),
        (
            "Complete: Elle a expliqué qu'elle ___ malade la veille.",
            ["avait été", "est", "sera", "soit"],
            0,
            "Hier → la veille; passé → plus-que-parfait.",
            "Elle a expliqué qu'elle avait été malade la veille.",
        ),
        (
            "Complete: On m'a dit de ___ prudent.",
            ["suis", "être", "soit", "étais"],
            1,
            "Ordem/conselho: dire de + infinitivo.",
            "On m'a dit d'être prudent.",
        ),
        (
            "Complete: Il a nié ___ vu le message.",
            ["a", "qu'il a", "avoir", "d'avoir"],
            2,
            "Nier + infinitivo passado: nier avoir + particípio.",
            "Il a nié avoir vu le message.",
        ),
        (
            "Complete: Elle a demandé qui ___ appelé.",
            ["a", "aura", "ait", "avait"],
            3,
            "Sujeto interrogativo mantido; tempo geralmente recua.",
            "Elle a demandé qui avait appelé.",
        ),
    ],
    "fr-grammar-extra-01": [
        (
            "Complete: Le livre est ___ la table.",
            ["sur", "dans", "à"],
            0,
            "Sur indica superfície.",
            "Le livre est sur la table.",
        ),
        (
            "Complete: Je vais ___ école.",
            ["en", "à l'", "chez"],
            1,
            "Aller à + artigo: à l'école.",
            "Je vais à l'école.",
        ),
        (
            "Complete: Le rendez-vous est ___.",
            ["en lundi", "dans lundi", "lundi"],
            2,
            "Dias da semana sem preposição para data habitual: lundi.",
            "Le rendez-vous est lundi.",
        ),
        (
            "Complete: Elle habite ___ Paris.",
            ["à", "en", "dans"],
            0,
            "Cidades: à + nome da cidade.",
            "Elle habite à Paris.",
        ),
        (
            "Complete: Nous arrivons ___ 9 heures.",
            ["en", "à", "dans"],
            1,
            "Horas: à + hora.",
            "Nous arrivons à 9 heures.",
        ),
    ],
    "fr-grammar-extra-02": [
        (
            "Complete: Je reste ___ il pleut.",
            ["mais", "ou", "parce que"],
            2,
            "Parce que introduz causa.",
            "Je reste parce qu'il pleut.",
        ),
        (
            "Complete: Il est fatigué, ___ il continue.",
            ["mais", "donc", "car"],
            0,
            "Mais marca oposição.",
            "Il est fatigué, mais il continue.",
        ),
        (
            "Complete: Tu viens ___ tu restes ?",
            ["et", "ou", "si"],
            1,
            "Ou expressa alternativa.",
            "Tu viens ou tu restes ?",
        ),
        (
            "Complete: Il pleut, ___ prends un parapluie.",
            ["car", "ou", "donc"],
            2,
            "Donc introduz consequência.",
            "Il pleut, donc prends un parapluie.",
        ),
        (
            "Complete: Je mange ___ j'ai faim.",
            ["car", "mais", "ou"],
            0,
            "Car também indica causa (mais formal que parce que).",
            "Je mange car j'ai faim.",
        ),
        (
            "Complete: Elle étudie ___ elle veut réussir.",
            ["mais", "parce que", "ou"],
            1,
            "Parce que liga motivo à ação.",
            "Elle étudie parce qu'elle veut réussir.",
        ),
    ],
    "fr-grammar-extra-03": [
        (
            "Complete: Je bois ___ eau.",
            ["du", "des", "de l'"],
            2,
            "Partitivo diante de vogal: de l'.",
            "Je bois de l'eau.",
        ),
        (
            "Complete: Elle mange ___ pain.",
            ["du", "de la", "des"],
            0,
            "Masculino singular partitivo: du.",
            "Elle mange du pain.",
        ),
        (
            "Complete: Nous prenons ___ salade.",
            ["du", "de la", "des"],
            1,
            "Feminino singular: de la.",
            "Nous prenons de la salade.",
        ),
        (
            "Complete: Il y a ___ fruits sur la table.",
            ["du", "de la", "des"],
            2,
            "Plural: des (mesmo sentido partitivo/indefinido).",
            "Il y a des fruits sur la table.",
        ),
        (
            "Complete: Je n'ai pas ___ lait.",
            ["de", "du", "de la"],
            0,
            "Após negação, o partitivo vira de/d'.",
            "Je n'ai pas de lait.",
        ),
        (
            "Complete: Tu veux ___ fromage ?",
            ["de la", "du", "des"],
            1,
            "Fromage é masculino: du fromage.",
            "Tu veux du fromage ?",
        ),
    ],
    "fr-grammar-extra-04": [
        (
            "Complete: Tu vas à Paris ? Oui, j'___ vais.",
            ["en", "y", "le", "lui"],
            1,
            "Y substitui à + lugar.",
            "Tu vas à Paris ? Oui, j'y vais.",
        ),
        (
            "Complete: Tu veux du pain ? Oui, j'___ veux.",
            ["y", "le", "en", "lui"],
            2,
            "En substitui de + quantidade/partitivo.",
            "Tu veux du pain ? Oui, j'en veux.",
        ),
        (
            "Complete: Il pense à son projet. Il ___ pense souvent.",
            ["en", "le", "lui", "y"],
            3,
            "Y também substitui à + coisa.",
            "Il y pense souvent.",
        ),
        (
            "Complete: Elle a trois frères. Elle ___ a trois.",
            ["en", "y", "les", "leur"],
            0,
            "En retoma quantidade com de.",
            "Elle en a trois.",
        ),
        (
            "Complete: Tu reviens du marché ? Oui, j'___ reviens.",
            ["y", "en", "le", "lui"],
            1,
            "En substitui de + lugar de origem.",
            "Oui, j'en reviens.",
        ),
        (
            "Complete: Nous irons à la plage. Nous ___ irons demain.",
            ["en", "la", "y", "leur"],
            2,
            "Y = à la plage.",
            "Nous y irons demain.",
        ),
        (
            "Complete: Il parle de son voyage. Il ___ parle souvent.",
            ["y", "le", "lui", "en"],
            3,
            "En = de + coisa mencionada.",
            "Il en parle souvent.",
        ),
        (
            "Complete: J'ai besoin de conseils. J'___ ai besoin.",
            ["en", "y", "les", "lui"],
            0,
            "Avoir besoin de → en.",
            "J'en ai besoin.",
        ),
    ],
    "fr-grammar-extra-05": [
        (
            "Complete: ___ , le projet est viable.",
            ["Pourtant", "En effet", "Sinon", "Alors que"],
            1,
            "En effet confirma ou explica.",
            "En effet, le projet est viable.",
        ),
        (
            "Complete: Il a étudié ; ___ , il a échoué.",
            ["donc", "ainsi", "pourtant", "car"],
            2,
            "Pourtant marca contraste inesperado.",
            "Il a étudié ; pourtant, il a échoué.",
        ),
        (
            "Complete: ___ les données manquent, la conclusion est fragile.",
            ["Pourtant", "Ainsi", "Or", "Puisque"],
            3,
            "Puisque introduz causa conhecida.",
            "Puisque les données manquent, la conclusion est fragile.",
        ),
        (
            "Complete: Il a plu ; ___ , la rue est mouillée.",
            ["par conséquent", "pourtant", "sinon", "or"],
            0,
            "Par conséquent marca consequência lógica.",
            "Il a plu ; par conséquent, la rue est mouillée.",
        ),
        (
            "Complete: ___ , il faudrait vérifier les sources.",
            ["Ainsi", "Toutefois", "Car", "Donc"],
            1,
            "Toutefois atenua ou contrapõe.",
            "Toutefois, il faudrait vérifier les sources.",
        ),
        (
            "Complete: D'abord, lisez le texte ; ___ , répondez.",
            ["pourtant", "sinon", "ensuite", "car"],
            2,
            "Ensuite ordena etapas.",
            "D'abord, lisez le texte ; ensuite, répondez.",
        ),
        (
            "Complete: ___ il soit compétent, il doute encore.",
            ["Parce que", "Donc", "Ainsi", "Bien que"],
            3,
            "Bien que + subjuntivo expressa concessão.",
            "Bien qu'il soit compétent, il doute encore.",
        ),
        (
            "Complete: Le rapport est clair ; ___ , les chiffres restent discutables.",
            ["en revanche", "ainsi", "car", "donc"],
            0,
            "En revanche marca oposição.",
            "Le rapport est clair ; en revanche, les chiffres restent discutables.",
        ),
    ],
    "fr-grammar-extra-06": [
        (
            "Complete: Je ___ de partir.",
            ["vais", "viens", "dois", "peux"],
            1,
            "Venir de + infinitivo = acabou de.",
            "Je viens de partir.",
        ),
        (
            "Complete: Elle ___ de comprendre le problème.",
            ["vient", "finit", "est en train", "cesse"],
            2,
            "Être en train de = ação em curso.",
            "Elle est en train de comprendre le problème.",
        ),
        (
            "Complete: Nous ___ de terminer le rapport.",
            ["allons", "sommes", "avons", "venons"],
            3,
            "Venir de no plural: nous venons de.",
            "Nous venons de terminer le rapport.",
        ),
        (
            "Complete: Il ___ se tromper.",
            ["risque de", "vient de", "est en train de", "cesse de"],
            0,
            "Risquer de = haver possibilidade de.",
            "Il risque de se tromper.",
        ),
        (
            "Complete: Tu ___ de fumer ?",
            ["viens", "as arrêté", "es en train", "vas"],
            1,
            "Arrêter de + infinitivo.",
            "Tu as arrêté de fumer ?",
        ),
        (
            "Complete: Je ___ finir ce soir.",
            ["viens", "suis", "compte", "dois"],
            2,
            "Compter + infinitivo = pretender.",
            "Je compte finir ce soir.",
        ),
        (
            "Complete: Elle ___ de travailler à 18 h.",
            ["vient", "est", "va", "a fini"],
            3,
            "Finir de + infinitivo.",
            "Elle a fini de travailler à 18 h.",
        ),
        (
            "Complete: Nous ___ à résoudre ce point.",
            ["tenons", "venons", "allons", "sommes"],
            0,
            "Tenir à + infinitivo = dar importância a.",
            "Nous tenons à résoudre ce point.",
        ),
    ],
    "fr-grammar-extra-07": [
        (
            "Complete: Je ne pense pas qu'il ___ raison.",
            ["a", "ait", "aura", "avait"],
            1,
            "Negação de opinião → subjuntivo.",
            "Je ne pense pas qu'il ait raison.",
        ),
        (
            "Complete: Le seul ami que j'___ est parti.",
            ["ai", "aurai", "aie", "avais"],
            2,
            "Antecedente com superlativo/seul frequentemente + subjuntivo.",
            "Le seul ami que j'aie est parti.",
        ),
        (
            "Complete: Quoi que vous ___, écoutez d'abord.",
            ["dites", "direz", "disait", "disiez"],
            3,
            "Quoi que + subjuntivo.",
            "Quoi que vous disiez, écoutez d'abord.",
        ),
        (
            "Complete: Il est temps que nous ___.",
            ["agissions", "agissons", "agirons", "agissaient"],
            0,
            "Il est temps que + subjuntivo.",
            "Il est temps que nous agissions.",
        ),
        (
            "Complete: Je cherche une solution qui ___ efficace.",
            ["est", "soit", "sera", "était"],
            1,
            "Relativa com valor de desejo/objetivo → subjuntivo.",
            "Je cherche une solution qui soit efficace.",
        ),
        (
            "Complete: Sans que personne ne ___, il est parti.",
            ["le sait", "le saura", "le sache", "le savait"],
            2,
            "Sans que + subjuntivo.",
            "Sans que personne ne le sache, il est parti.",
        ),
        (
            "Complete: Pour peu qu'il ___, tout change.",
            ["acceptait", "acceptera", "accepterait", "accepte"],
            3,
            "Pour peu que + subjuntivo.",
            "Pour peu qu'il accepte, tout change.",
        ),
        (
            "Complete: Je crains qu'elle ne ___ pas.",
            ["vienne", "vient", "viendra", "venait"],
            0,
            "Craindre que (+ ne explétif) + subjuntivo.",
            "Je crains qu'elle ne vienne pas.",
        ),
        (
            "Complete: Jusqu'à ce que tu ___, reste ici.",
            ["as fini", "aies fini", "auras fini", "avais fini"],
            1,
            "Jusqu'à ce que + subjuntivo (souvent passé).",
            "Jusqu'à ce que tu aies fini, reste ici.",
        ),
        (
            "Complete: Quoiqu'il ___ tard, elle insiste.",
            ["est", "sera", "soit", "était"],
            2,
            "Quoique = bien que → subjuntivo.",
            "Quoiqu'il soit tard, elle insiste.",
        ),
    ],
    "fr-grammar-extra-08": [
        (
            "Complete: Ça ___ le coup d'essayer.",
            ["fait", "prend", "donne", "vaut"],
            3,
            "Ça vaut le coup = vale a pena.",
            "Ça vaut le coup d'essayer.",
        ),
        (
            "Complete: J'___ hâte de vous revoir.",
            ["ai", "suis", "fais", "prends"],
            0,
            "Avoir hâte de = mal poder esperar.",
            "J'ai hâte de vous revoir.",
        ),
        (
            "Complete: Tu peux me ___ au courant ?",
            ["mettre", "tenir", "faire", "dire"],
            1,
            "Tenir au courant = manter informado.",
            "Tu peux me tenir au courant ?",
        ),
        (
            "Complete: Vous êtes ___ répondre demain.",
            ["pensé", "voulu", "censé", "dû"],
            2,
            "Être censé + infinitivo = espera-se que.",
            "Vous êtes censé répondre demain.",
        ),
        (
            "Complete: Il faut ___ les bouchées doubles.",
            ["prendre", "mettre", "avoir", "faire"],
            3,
            "Faire les bouchées doubles = acelerar o ritmo.",
            "Il faut faire les bouchées doubles.",
        ),
        (
            "Complete: Elle a pris la mouche : elle s'est ___.",
            ["vexée", "réjouie", "endormie", "ennuyée"],
            0,
            "Prendre la mouche = ofender-se.",
            "Elle a pris la mouche : elle s'est vexée.",
        ),
        (
            "Complete: On va ___ un coup d'œil au dossier.",
            ["faire", "jeter", "prendre", "donner"],
            1,
            "Jeter un coup d'œil = dar uma olhada.",
            "On va jeter un coup d'œil au dossier.",
        ),
        (
            "Complete: Il a ___ le problème sous le tapis.",
            ["mis", "jeté", "balayé", "posé"],
            2,
            "Balayer sous le tapis = esconder um problema (registre figuré).",
            "Il a balayé le problème sous le tapis.",
        ),
        (
            "Complete: Ce n'est pas ___ de le dire.",
            ["de refus", "le cas", "le moment", "la peine"],
            3,
            "Ce n'est pas la peine = não vale a pena / não precisa.",
            "Ce n'est pas la peine de le dire.",
        ),
        (
            "Complete: Ils sont ___ d'accord sur ce point.",
            ["bel et bien", "peu", "à peine", "loin"],
            0,
            "Bel et bien = efetivamente, de fato.",
            "Ils sont bel et bien d'accord sur ce point.",
        ),
    ],
    "fr-grammar-complete-a1-01": [
        (
            "Complete: ___ travaille avec moi.",
            ["La", "Elle", "Lui"],
            1,
            "Pronome sujeito feminino: elle.",
            "Elle travaille avec moi.",
        ),
        (
            "Complete: Moi, j'aime le café ; ___ , il préfère le thé.",
            ["il", "le", "lui"],
            2,
            "Forma tônica de contraste: lui.",
            "Moi, j'aime le café ; lui, il préfère le thé.",
        ),
        (
            "Complete: Elle travaille avec ___.",
            ["moi", "je", "me"],
            0,
            "Após preposição usa-se a forma tônica: moi.",
            "Elle travaille avec moi.",
        ),
        (
            "Complete: ___ allons au cinéma.",
            ["On", "Nous", "Ils"],
            1,
            "Nous é sujeito de 1ª pessoa do plural.",
            "Nous allons au cinéma.",
        ),
        (
            "Complete: C'est pour ___ ?",
            ["tu", "te", "toi"],
            2,
            "Após pour: forma tônica toi.",
            "C'est pour toi ?",
        ),
    ],
    "fr-grammar-complete-a1-02": [
        (
            "Complete: J'___ vingt ans.",
            ["ai", "suis", "est"],
            0,
            "Idade com avoir: j'ai … ans.",
            "J'ai vingt ans.",
        ),
        (
            "Complete: Il ___ un café ici.",
            ["est", "y a", "a"],
            1,
            "Il y a indica existência.",
            "Il y a un café ici.",
        ),
        (
            "Complete: Elle ___ fatiguée.",
            ["a", "sont", "est"],
            2,
            "Estado com être.",
            "Elle est fatiguée.",
        ),
        (
            "Complete: Nous ___ soif.",
            ["avons", "sommes", "êtes"],
            0,
            "Avoir soif = estar com sede.",
            "Nous avons soif.",
        ),
        (
            "Complete: Tu ___ mon frère ?",
            ["as", "es", "a"],
            1,
            "Identidade: être.",
            "Tu es mon frère ?",
        ),
    ],
    "fr-grammar-complete-a1-03": [
        (
            "Complete: Nous ___ français.",
            ["parle", "parlez", "parlons"],
            2,
            "Parler (-er): nous parlons.",
            "Nous parlons français.",
        ),
        (
            "Complete: Ils ___ à six heures.",
            ["finissent", "finit", "finissons"],
            0,
            "Finir (-ir): ils finissent.",
            "Ils finissent à six heures.",
        ),
        (
            "Complete: Tu ___ une lettre.",
            ["écrit", "écris", "écrivez"],
            1,
            "Écrire (-re): tu écris.",
            "Tu écris une lettre.",
        ),
        (
            "Complete: Je ___ ici.",
            ["habites", "habitons", "habite"],
            2,
            "Habiter: je habite → j'habite.",
            "J'habite ici.",
        ),
        (
            "Complete: Vous ___ le train ?",
            ["attendez", "attends", "attend"],
            0,
            "Attendre: vous attendez.",
            "Vous attendez le train ?",
        ),
    ],
    "fr-grammar-complete-a1-04": [
        (
            "Complete: Je ___ au travail.",
            ["vas", "vais", "allez"],
            1,
            "Aller: je vais.",
            "Je vais au travail.",
        ),
        (
            "Complete: Nous ___ les courses.",
            ["faites", "font", "faisons"],
            2,
            "Faire: nous faisons.",
            "Nous faisons les courses.",
        ),
        (
            "Complete: Elle ___ le bus.",
            ["prend", "prends", "prenez"],
            0,
            "Prendre: elle prend.",
            "Elle prend le bus.",
        ),
        (
            "Complete: Ils ___ de France.",
            ["vient", "viennent", "venez"],
            1,
            "Venir: ils viennent.",
            "Ils viennent de France.",
        ),
        (
            "Complete: Tu ___ du sport ?",
            ["fait", "faisons", "fais"],
            2,
            "Faire: tu fais.",
            "Tu fais du sport ?",
        ),
    ],
    "fr-grammar-complete-a1-05": [
        (
            "Complete: Je ___ vous aider.",
            ["peux", "peut", "pouvez"],
            0,
            "Pouvoir + infinitivo: je peux.",
            "Je peux vous aider.",
        ),
        (
            "Complete: Nous ___ partir maintenant.",
            ["doivent", "devons", "dois"],
            1,
            "Devoir: nous devons + infinitivo.",
            "Nous devons partir maintenant.",
        ),
        (
            "Complete: Tu ___ venir avec nous ?",
            ["veut", "voulez", "veux"],
            2,
            "Vouloir: tu veux.",
            "Tu veux venir avec nous ?",
        ),
        (
            "Complete: Elle ___ parler anglais.",
            ["peut", "peux", "pouvez"],
            0,
            "Pouvoir: elle peut.",
            "Elle peut parler anglais.",
        ),
        (
            "Complete: Vous ___ répondre demain.",
            ["doit", "devez", "devons"],
            1,
            "Devoir: vous devez.",
            "Vous devez répondre demain.",
        ),
    ],
    "fr-grammar-complete-a1-06": [
        (
            "Complete: ___ tu habites ?",
            ["Où que", "Est-ce où", "Où est-ce que"],
            2,
            "Est-ce que após a palavra interrogativa.",
            "Où est-ce que tu habites ?",
        ),
        (
            "Complete: ___ vous parlez français ?",
            ["Est-ce que", "Que est", "Est que"],
            0,
            "Est-ce que introduz pergunta sim/não.",
            "Est-ce que vous parlez français ?",
        ),
        (
            "Complete: ___ est-ce que tu t'appelles ?",
            ["Quel", "Comment", "Combien"],
            1,
            "Comment para o nome.",
            "Comment est-ce que tu t'appelles ?",
        ),
        (
            "Complete: ___ est-ce que le cours commence ?",
            ["Qui", "Que", "Quand"],
            2,
            "Quand pergunta o momento.",
            "Quand est-ce que le cours commence ?",
        ),
        (
            "Complete: ___ est-ce que c'est ?",
            ["Qu'est-ce que", "Qui est-ce", "Combien"],
            0,
            "Qu'est-ce que c'est ? = o que é isto?",
            "Qu'est-ce que c'est ?",
        ),
    ],
    "fr-grammar-complete-a1-07": [
        (
            "Complete: Je ___ travaille ___ ici.",
            ["pas … ne", "ne … pas", "ne … jamais"],
            1,
            "Negação padrão: ne … pas em torno do verbo.",
            "Je ne travaille pas ici.",
        ),
        (
            "Complete: Elle ___ aime ___ le café.",
            ["ne … pas", "pas … n'", "n' … pas"],
            2,
            "Diante de vogal: n' … pas.",
            "Elle n'aime pas le café.",
        ),
        (
            "Complete: Nous ___ allons ___ au cinéma.",
            ["n' … pas", "ne … pas", "pas … ne"],
            0,
            "Aller começa por vogal: n' … pas.",
            "Nous n'allons pas au cinéma.",
        ),
        (
            "Complete: Tu ___ as ___ de voiture.",
            ["ne … pas", "n' … pas", "pas … de"],
            1,
            "Negação com avoir: n'as pas.",
            "Tu n'as pas de voiture.",
        ),
        (
            "Complete: Ils ___ sont ___ prêts.",
            ["n' … pas", "pas … ne", "ne … pas"],
            2,
            "Com être: ne sont pas.",
            "Ils ne sont pas prêts.",
        ),
    ],
    "fr-grammar-complete-a2-01": [
        (
            "Complete: Elle ___ arrivée hier.",
            ["est", "a", "sont"],
            0,
            "Arriver usa être; acordo do particípio.",
            "Elle est arrivée hier.",
        ),
        (
            "Complete: Nous ___ pris le train.",
            ["sommes", "avons", "êtes"],
            1,
            "Prendre com avoir.",
            "Nous avons pris le train.",
        ),
        (
            "Complete: Ils ___ partis tôt.",
            ["ont", "avez", "sont"],
            2,
            "Partir com être.",
            "Ils sont partis tôt.",
        ),
        (
            "Complete: J'___ mangé trop.",
            ["ai", "suis", "a"],
            0,
            "Manger com avoir.",
            "J'ai mangé trop.",
        ),
        (
            "Complete: Tu ___ vu ce film ?",
            ["es", "as", "a"],
            1,
            "Voir: tu as vu.",
            "Tu as vu ce film ?",
        ),
        (
            "Complete: Elle ___ née en 1990.",
            ["a", "sont", "est"],
            2,
            "Naître usa être.",
            "Elle est née en 1990.",
        ),
    ],
    "fr-grammar-complete-a2-02": [
        (
            "Complete: Quand j'___ enfant, je jouais ici.",
            ["étais", "ai été", "serai"],
            0,
            "Descrição no passado: imparfait.",
            "Quand j'étais enfant, je jouais ici.",
        ),
        (
            "Complete: Il ___ froid ce jour-là.",
            ["a fait", "faisait", "fait"],
            1,
            "Clima/contexto: imparfait.",
            "Il faisait froid ce jour-là.",
        ),
        (
            "Complete: Nous ___ à Lyon à l'époque.",
            ["avons habité", "habitons", "habitions"],
            2,
            "Situação duradoura: imparfait.",
            "Nous habitions à Lyon à l'époque.",
        ),
        (
            "Complete: Elle ___ toujours le même café.",
            ["prenait", "a pris", "prend"],
            0,
            "Hábito passado: imparfait.",
            "Elle prenait toujours le même café.",
        ),
        (
            "Complete: Vous ___ déjà français ?",
            ["avez parlé", "parliez", "parlez"],
            1,
            "Pergunta sobre hábito/capacidade passada: imparfait.",
            "Vous parliez déjà français ?",
        ),
        (
            "Complete: Les rues ___ vides.",
            ["ont été", "sont", "étaient"],
            2,
            "Descrição de cenário: imparfait.",
            "Les rues étaient vides.",
        ),
    ],
    "fr-grammar-complete-a2-03": [
        (
            "Complete: Je ___ appeler Marie.",
            ["vais", "va", "allez"],
            0,
            "Futur proche: aller + infinitivo.",
            "Je vais appeler Marie.",
        ),
        (
            "Complete: Nous ___ demain.",
            ["partons", "partirons", "partions"],
            1,
            "Futur simple: nous partirons.",
            "Nous partirons demain.",
        ),
        (
            "Complete: Ils ___ bientôt.",
            ["arrivent vont", "arriveront vont", "vont arriver"],
            2,
            "Futur proche: ils vont arriver.",
            "Ils vont arriver bientôt.",
        ),
        (
            "Complete: Elle ___ un message.",
            ["enverra", "envoie", "envoyait"],
            0,
            "Futur de envoyer: elle enverra.",
            "Elle enverra un message.",
        ),
        (
            "Complete: Tu ___ venir ce soir ?",
            ["va", "vas", "irez"],
            1,
            "Intenção próxima: tu vas + infinitivo.",
            "Tu vas venir ce soir ?",
        ),
        (
            "Complete: Vous ___ plus tard.",
            ["savez", "saviez", "saurez"],
            2,
            "Futur de savoir: vous saurez.",
            "Vous saurez plus tard.",
        ),
    ],
    "fr-grammar-complete-a2-04": [
        (
            "Complete: Ce livre est ___ que l'autre.",
            ["meilleur", "plus bon", "le plus bon"],
            0,
            "Comparativo de bon: meilleur.",
            "Ce livre est meilleur que l'autre.",
        ),
        (
            "Complete: Elle travaille ___ vite que lui.",
            ["plus aussi", "aussi", "si"],
            1,
            "Igualdade: aussi … que.",
            "Elle travaille aussi vite que lui.",
        ),
        (
            "Complete: C'est ___ intéressant du groupe.",
            ["plus", "le mieux", "le plus"],
            2,
            "Superlativo de adjetivo: le/la/les plus.",
            "C'est le plus intéressant du groupe.",
        ),
        (
            "Complete: Il court ___ que moi.",
            ["moins vite", "moins plus vite", "le moins"],
            0,
            "Comparativo de inferioridade: moins … que.",
            "Il court moins vite que moi.",
        ),
        (
            "Complete: Elle chante ___ que lui.",
            ["plus bien", "mieux", "le mieux"],
            1,
            "Comparativo de bien: mieux.",
            "Elle chante mieux que lui.",
        ),
        (
            "Complete: C'est ___ solution.",
            ["la plus bonne", "meilleure la", "la meilleure"],
            2,
            "Superlativo de bon: le/la meilleur(e).",
            "C'est la meilleure solution.",
        ),
    ],
    "fr-grammar-complete-a2-05": [
        (
            "Complete: Je ___ donne le document.",
            ["lui", "le", "la"],
            0,
            "COI de pessoa: lui.",
            "Je lui donne le document.",
        ),
        (
            "Complete: Je l'___ vue hier.",
            ["suis", "ai", "a"],
            1,
            "COD antecede o auxiliar; acordo possível com COD anterior.",
            "Je l'ai vue hier.",
        ),
        (
            "Complete: Tu ___ vois demain ?",
            ["leur", "lui", "les"],
            2,
            "COD plural: les.",
            "Tu les vois demain ?",
        ),
        (
            "Complete: Elle ___ téléphone ce soir.",
            ["leur", "les", "le"],
            0,
            "Téléphoner à → leur (plural).",
            "Elle leur téléphone ce soir.",
        ),
        (
            "Complete: Il ___ a envoyé un message.",
            ["me", "m'", "moi"],
            1,
            "Antes de vogal, me → m'.",
            "Il m'a envoyé un message.",
        ),
        (
            "Complete: Nous ___ écrivons souvent.",
            ["le", "la", "lui"],
            2,
            "Écrire à quelqu'un → lui.",
            "Nous lui écrivons souvent.",
        ),
    ],
    "fr-grammar-complete-b1-01": [
        (
            "Complete: Je ___ quand il a appelé.",
            ["ai lu", "lis", "lisais", "lirai"],
            2,
            "Ação em curso (imparfait) interrompida por evento (passé composé).",
            "Je lisais quand il a appelé.",
        ),
        (
            "Complete: Hier, elle ___ à huit heures.",
            ["partait", "part", "partira", "est partie"],
            3,
            "Evento pontual: passé composé.",
            "Hier, elle est partie à huit heures.",
        ),
        (
            "Complete: Il ___ toute la matinée.",
            ["pleuvait", "a plu", "pleut", "pleuvra"],
            0,
            "Contexto/descrição: imparfait.",
            "Il pleuvait toute la matinée.",
        ),
        (
            "Complete: Soudain, quelqu'un ___ à la porte.",
            ["frappait", "a frappé", "frappe", "frappera"],
            1,
            "Ação súbita: passé composé.",
            "Soudain, quelqu'un a frappé à la porte.",
        ),
        (
            "Complete: À l'époque, nous ___ près de l'école.",
            ["avons habité", "habitons", "habitions", "habiterons"],
            2,
            "Situação passada: imparfait.",
            "À l'époque, nous habitions près de l'école.",
        ),
        (
            "Complete: L'an dernier, ils ___ le concours.",
            ["réussissaient", "réussissent", "réussiront", "ont réussi"],
            3,
            "Fato concluído: passé composé.",
            "L'an dernier, ils ont réussi le concours.",
        ),
        (
            "Complete: Pendant qu'il ___, j'ai cuisiné.",
            ["dormait", "a dormi", "dort", "dormira"],
            0,
            "Fundo simultâneo: imparfait.",
            "Pendant qu'il dormait, j'ai cuisiné.",
        ),
        (
            "Complete: Un jour, elle ___ une décision importante.",
            ["prenait", "a pris", "prend", "prendra"],
            1,
            "Evento narrativo: passé composé.",
            "Un jour, elle a pris une décision importante.",
        ),
    ],
    "fr-grammar-complete-b1-02": [
        (
            "Complete: Je ___ réserver une table.",
            ["veux", "voudrai", "voudrais", "voulais"],
            2,
            "Cortesia: conditionnel présent.",
            "Je voudrais réserver une table.",
        ),
        (
            "Complete: À ta place, je ___ au directeur.",
            ["parle", "parlerai", "parlais", "parlerais"],
            3,
            "Conselho hipotético: conditionnel.",
            "À ta place, je parlerais au directeur.",
        ),
        (
            "Complete: Si j'avais le temps, je ___.",
            ["voyagerais", "voyage", "voyagerai", "voyageais"],
            0,
            "Si + imparfait → conditionnel présent.",
            "Si j'avais le temps, je voyagerais.",
        ),
        (
            "Complete: Pourriez-vous m'___ ?",
            ["aidez", "aider", "aidiez", "aidé"],
            1,
            "Pedido cortês: conditionnel + infinitivo.",
            "Pourriez-vous m'aider ?",
        ),
        (
            "Complete: Il ___ plus prudent d'attendre.",
            ["est", "sera", "serait", "était"],
            2,
            "Opinião atenuada: conditionnel.",
            "Il serait plus prudent d'attendre.",
        ),
        (
            "Complete: Nous ___ volontiers venir.",
            ["venons", "viendrons", "venions", "viendrions"],
            3,
            "Aceitação cortês: conditionnel.",
            "Nous viendrions volontiers.",
        ),
        (
            "Complete: Tu ___ m'appeler demain ?",
            ["pourrais", "peux", "pourras", "pouvais"],
            0,
            "Pedido: tu pourrais… ?",
            "Tu pourrais m'appeler demain ?",
        ),
        (
            "Complete: Elle ___ une réponse claire.",
            ["aime", "aimerait", "aimera", "aimait"],
            1,
            "Desejo atenuado: conditionnel.",
            "Elle aimerait une réponse claire.",
        ),
    ],
    "fr-grammar-complete-b1-03": [
        (
            "Complete: La personne ___ parle est ma sœur.",
            ["que", "dont", "qui", "où"],
            2,
            "Qui = sujeito da relativa.",
            "La personne qui parle est ma sœur.",
        ),
        (
            "Complete: C'est le livre ___ j'ai besoin.",
            ["que", "qui", "où", "dont"],
            3,
            "Dont substitui de + complemento.",
            "C'est le livre dont j'ai besoin.",
        ),
        (
            "Complete: Voici le film ___ j'ai vu hier.",
            ["que", "qui", "dont", "où"],
            0,
            "Que = objeto direto.",
            "Voici le film que j'ai vu hier.",
        ),
        (
            "Complete: C'est l'endroit ___ nous nous sommes rencontrés.",
            ["qui", "où", "que", "dont"],
            1,
            "Où refere-se a lugar (ou tempo).",
            "C'est l'endroit où nous nous sommes rencontrés.",
        ),
        (
            "Complete: Le collègue ___ j'ai parlé est nouveau.",
            ["que", "dont", "à qui", "où"],
            2,
            "Parler à → à qui.",
            "Le collègue à qui j'ai parlé est nouveau.",
        ),
        (
            "Complete: La raison ___ il est parti reste obscure.",
            ["qui", "que", "dont", "pour laquelle"],
            3,
            "Pour laquelle = pour + razão.",
            "La raison pour laquelle il est parti reste obscure.",
        ),
        (
            "Complete: Ce ___ m'intéresse, c'est le résultat.",
            ["qui", "que", "dont", "où"],
            0,
            "Ce qui = sujeito neutro.",
            "Ce qui m'intéresse, c'est le résultat.",
        ),
        (
            "Complete: Ce ___ je veux, c'est comprendre.",
            ["qui", "que", "dont", "où"],
            1,
            "Ce que = objeto neutro.",
            "Ce que je veux, c'est comprendre.",
        ),
    ],
    "fr-grammar-complete-b1-04": [
        (
            "Complete: Elle a dit qu'elle ___ prête.",
            ["est", "sera", "était", "soit"],
            2,
            "Présent → imparfait no discurso indireto passado.",
            "Elle a dit qu'elle était prête.",
        ),
        (
            "Complete: Il m'a demandé si je ___.",
            ["viens", "viendrai", "vienne", "venais"],
            3,
            "Pergunta fechada: si + recuo.",
            "Il m'a demandé si je venais.",
        ),
        (
            "Complete: Elle a promis qu'elle ___ le lendemain.",
            ["appellerait", "appelle", "appellera", "appelait"],
            0,
            "Futur → conditionnel; demain → le lendemain.",
            "Elle a promis qu'elle appellerait le lendemain.",
        ),
        (
            "Complete: Il a expliqué qu'il ___ déjà fini.",
            ["a", "avait", "aura", "ait"],
            1,
            "Passé composé → plus-que-parfait.",
            "Il a expliqué qu'il avait déjà fini.",
        ),
        (
            "Complete: On m'a dit de ___ calme.",
            ["reste", "restais", "rester", "resterai"],
            2,
            "Ordem: dire de + infinitivo.",
            "On m'a dit de rester calme.",
        ),
        (
            "Complete: Elle a demandé où nous ___.",
            ["habitons", "habiterons", "habiterions", "habitions"],
            3,
            "Interrogativa parcial sem inversão.",
            "Elle a demandé où nous habitions.",
        ),
        (
            "Complete: Il a affirmé qu'il ___ le jour précédent.",
            ["était venu", "est venu", "viendra", "vienne"],
            0,
            "Hier → le jour précédent; passé → plus-que-parfait.",
            "Il a affirmé qu'il était venu le jour précédent.",
        ),
        (
            "Complete: Elle a répondu qu'elle ___ d'accord.",
            ["est", "était", "sera", "soit"],
            1,
            "Discurso indireto: recuo do presente.",
            "Elle a répondu qu'elle était d'accord.",
        ),
    ],
    "fr-grammar-complete-b2-01": [
        (
            "Complete: J'___ accepté avec plus de temps.",
            ["avais", "aurai", "aurais", "aie"],
            2,
            "Conditionnel passé: hipótese não realizada.",
            "J'aurais accepté avec plus de temps.",
        ),
        (
            "Complete: Il ___ parti hier.",
            ["aurait", "est", "était", "serait"],
            3,
            "Com être: serait + particípio.",
            "Il serait parti hier.",
        ),
        (
            "Complete: Si tu m'avais prévenu, je ___ venu.",
            ["serais", "aurais", "suis", "étais"],
            0,
            "Si + plus-que-parfait → conditionnel passé (venir → être).",
            "Si tu m'avais prévenu, je serais venu.",
        ),
        (
            "Complete: Sans ton aide, nous n'___ pas réussi.",
            ["avions", "aurions", "aurons", "ayons"],
            1,
            "Sans … equivale a hipótese; conditionnel passé.",
            "Sans ton aide, nous n'aurions pas réussi.",
        ),
        (
            "Complete: Elle ___ dû prévenir plus tôt.",
            ["avait", "aura", "aurait", "ait"],
            2,
            "Dever no passado hipotético: aurait dû.",
            "Elle aurait dû prévenir plus tôt.",
        ),
        (
            "Complete: Qui ___ pu imaginer cela ?",
            ["avait", "aura", "ait", "aurait"],
            3,
            "Conjectura no passado: conditionnel passé.",
            "Qui aurait pu imaginer cela ?",
        ),
        (
            "Complete: Nous ___ préféré une autre option.",
            ["aurions", "avions", "aurons", "ayons"],
            0,
            "Preferência hipotética passada.",
            "Nous aurions préféré une autre option.",
        ),
        (
            "Complete: Tu ___ pu m'appeler.",
            ["avais", "aurais", "auras", "aies"],
            1,
            "Crítica suave: tu aurais pu…",
            "Tu aurais pu m'appeler.",
        ),
        (
            "Complete: Ils ___ arrivés à l'heure.",
            ["auraient", "sont", "seraient", "étaient"],
            2,
            "Arriver com être no conditionnel passé.",
            "Ils seraient arrivés à l'heure.",
        ),
        (
            "Complete: J'___ voulu te le dire.",
            ["avais", "aurai", "aie", "aurais"],
            3,
            "Arrependimento: j'aurais voulu…",
            "J'aurais voulu te le dire.",
        ),
    ],
    "fr-grammar-complete-b2-02": [
        (
            "Complete: ___ Marie qui a appelé.",
            ["C'est", "Ce qui", "Ce que", "Il est"],
            0,
            "C'est … qui destaca o sujeito.",
            "C'est Marie qui a appelé.",
        ),
        (
            "Complete: ___ je veux, c'est comprendre.",
            ["Ce qui", "Ce que", "C'est", "Qui"],
            1,
            "Ce que = objeto destacado.",
            "Ce que je veux, c'est comprendre.",
        ),
        (
            "Complete: ___ m'intéresse, c'est le fond.",
            ["Ce que", "C'est", "Ce qui", "Que"],
            2,
            "Ce qui = sujeito neutro em relevo.",
            "Ce qui m'intéresse, c'est le fond.",
        ),
        (
            "Complete: C'est à Paris ___ nous nous sommes rencontrés.",
            ["qui", "où", "dont", "que"],
            3,
            "C'est … que destaca complemento (não sujeito).",
            "C'est à Paris que nous nous sommes rencontrés.",
        ),
        (
            "Complete: C'est lui ___ a raison.",
            ["qui", "que", "dont", "où"],
            0,
            "Após c'est + sujeito: qui.",
            "C'est lui qui a raison.",
        ),
        (
            "Complete: C'est ce rapport ___ je lis.",
            ["qui", "que", "dont", "où"],
            1,
            "Objeto destacado: que.",
            "C'est ce rapport que je lis.",
        ),
        (
            "Complete: ___ compte, c'est la clarté.",
            ["Ce que", "C'est", "Ce qui", "Qui"],
            2,
            "Ce qui compte = o que importa.",
            "Ce qui compte, c'est la clarté.",
        ),
        (
            "Complete: C'est demain ___ nous partons.",
            ["qui", "où", "dont", "que"],
            3,
            "Tempo destacado com c'est … que.",
            "C'est demain que nous partons.",
        ),
        (
            "Complete: C'est de cela ___ je parle.",
            ["que", "qui", "dont", "où"],
            0,
            "Complemento preposicional destacado: que.",
            "C'est de cela que je parle.",
        ),
        (
            "Complete: ___ me préoccupe, c'est le délai.",
            ["Ce que", "Ce qui", "C'est", "Que"],
            1,
            "Ce qui introduz o tema em relevo.",
            "Ce qui me préoccupe, c'est le délai.",
        ),
    ],
    "fr-grammar-complete-b2-03": [
        (
            "Complete: La ___ des coûts reste prioritaire.",
            ["réduire", "réduit", "réduction", "réduisant"],
            2,
            "Nominalização: verbo → nome (réduction).",
            "La réduction des coûts reste prioritaire.",
        ),
        (
            "Complete: La mise en ___ du projet prendra un an.",
            ["œuvreux", "œuvrer", "œuvrement", "œuvre"],
            3,
            "Mise en œuvre = implementação.",
            "La mise en œuvre du projet prendra un an.",
        ),
        (
            "Complete: L'___ des données est essentielle.",
            ["analyse", "analyser", "analysé", "analysant"],
            0,
            "Analyser → analyse (nome).",
            "L'analyse des données est essentielle.",
        ),
        (
            "Complete: La ___ des délais inquiète l'équipe.",
            ["prolonger", "prolongation", "prolongé", "prolongeant"],
            1,
            "Prolonger → prolongation.",
            "La prolongation des délais inquiète l'équipe.",
        ),
        (
            "Complete: Le ___ des résultats est en cours.",
            ["traiter", "traité", "traitement", "traitant"],
            2,
            "Traiter → traitement.",
            "Le traitement des résultats est en cours.",
        ),
        (
            "Complete: Une ___ rapide s'impose.",
            ["décider", "décidé", "décidant", "décision"],
            3,
            "Décider → décision.",
            "Une décision rapide s'impose.",
        ),
        (
            "Complete: La ___ des compétences est encouragée.",
            ["valorisation", "valoriser", "valorisé", "valorisant"],
            0,
            "Valoriser → valorisation.",
            "La valorisation des compétences est encouragée.",
        ),
        (
            "Complete: L'___ du risque a été sous-estimée.",
            ["évaluer", "évaluation", "évalué", "évaluant"],
            1,
            "Évaluer → évaluation.",
            "L'évaluation du risque a été sous-estimée.",
        ),
        (
            "Complete: La ___ des procédures reste complexe.",
            ["améliorer", "amélioré", "amélioration", "améliorant"],
            2,
            "Améliorer → amélioration.",
            "L'amélioration des procédures reste complexe.",
        ),
        (
            "Complete: Le ___ des responsabilités doit être clarifié.",
            ["partager", "partagé", "partageant", "partage"],
            3,
            "Partager → partage.",
            "Le partage des responsabilités doit être clarifié.",
        ),
    ],
    "fr-grammar-complete-b2-04": [
        (
            "Complete: Bien qu'il ___ tard, elle continue.",
            ["soit", "est", "sera", "était"],
            0,
            "Bien que + subjuntivo.",
            "Bien qu'il soit tard, elle continue.",
        ),
        (
            "Complete: Il a beau ___, il échoue.",
            ["essaie", "essayer", "essayé", "essayant"],
            1,
            "Avoir beau + infinitivo = esforço inútil.",
            "Il a beau essayer, il échoue.",
        ),
        (
            "Complete: ___ la pluie, le match a lieu.",
            ["Bien que", "Quoique", "Malgré", "Sans que"],
            2,
            "Malgré + nome (sem verbo finito).",
            "Malgré la pluie, le match a lieu.",
        ),
        (
            "Complete: Quoiqu'elle ___ fatiguée, elle insiste.",
            ["est", "sera", "était", "soit"],
            3,
            "Quoique + subjuntivo.",
            "Quoiqu'elle soit fatiguée, elle insiste.",
        ),
        (
            "Complete: En dépit ___ difficultés, ils avancent.",
            ["des", "de", "du", "les"],
            0,
            "En dépit de + artigo: en dépit des.",
            "En dépit des difficultés, ils avancent.",
        ),
        (
            "Complete: Même si c'est dur, je ___.",
            ["persiste que", "persiste", "persiste de", "persiste à"],
            1,
            "Même si + indicativo (não subjuntivo).",
            "Même si c'est dur, je persiste.",
        ),
        (
            "Complete: Pour ___ difficile que ce soit, on continue.",
            ["si", "tant", "aussi", "tel"],
            2,
            "Pour aussi … que + subjuntivo = concessão.",
            "Pour aussi difficile que ce soit, on continue.",
        ),
        (
            "Complete: Quelque ___ qu'il fasse, on le critique.",
            ["efforts", "effortant", "efforté", "effort"],
            3,
            "Quelque(s) + nome + que + subjuntivo.",
            "Quelque effort qu'il fasse, on le critique.",
        ),
        (
            "Complete: Elle continue ___ le doute.",
            ["malgré", "bien que", "quoique", "sans que"],
            0,
            "Malgré + nome: malgré le doute.",
            "Elle continue malgré le doute.",
        ),
        (
            "Complete: Il ___ beau dire, personne n'écoute.",
            ["est", "a", "fait", "peut"],
            1,
            "Avoir beau + infinitivo.",
            "Il a beau dire, personne n'écoute.",
        ),
    ],
    "fr-grammar-complete-b2-05": [
        (
            "Complete: L'étude ___ que les résultats varient.",
            ["souligne de", "souligne à", "souligne", "souligne pour"],
            2,
            "Souligner que + indicativo.",
            "L'étude souligne que les résultats varient.",
        ),
        (
            "Complete: L'auteur ___ cette idée en cause.",
            ["met", "pose", "prend", "remet"],
            3,
            "Remettre en cause = questionar.",
            "L'auteur remet cette idée en cause.",
        ),
        (
            "Complete: Le rapport ___ un manque de données.",
            ["constate", "constate de", "constate à", "constate pour"],
            0,
            "Constater + objeto / que…",
            "Le rapport constate un manque de données.",
        ),
        (
            "Complete: Elle ___ que la méthode est efficace.",
            ["affirme de", "affirme", "affirme à", "affirme pour"],
            1,
            "Affirmer que…",
            "Elle affirme que la méthode est efficace.",
        ),
        (
            "Complete: Il ___ les limites du modèle.",
            ["reconnaît de", "reconnaît à", "reconnaît", "reconnaît pour"],
            2,
            "Reconnaître + objeto.",
            "Il reconnaît les limites du modèle.",
        ),
        (
            "Complete: Les auteurs ___ une autre hypothèse.",
            ["avancent de", "avancent à", "avancent pour", "avancent"],
            3,
            "Avancer une hypothèse = propor.",
            "Les auteurs avancent une autre hypothèse.",
        ),
        (
            "Complete: On ___ souvent que le contexte compte.",
            ["rappelle", "rappelle de", "rappelle à", "rappelle pour"],
            0,
            "Rappeler que…",
            "On rappelle souvent que le contexte compte.",
        ),
        (
            "Complete: Elle ___ la pertinence de l'outil.",
            ["questionne de", "questionne", "questionne à", "questionne pour"],
            1,
            "Questionner + objeto direto.",
            "Elle questionne la pertinence de l'outil.",
        ),
        (
            "Complete: Le texte ___ sur deux points clés.",
            ["insiste de", "insiste que", "insiste", "insiste pour"],
            2,
            "Insister sur…",
            "Le texte insiste sur deux points clés.",
        ),
        (
            "Complete: Ils ___ que les preuves manquent.",
            ["soutiennent de", "soutiennent à", "soutiennent pour", "soutiennent"],
            3,
            "Soutenir que…",
            "Ils soutiennent que les preuves manquent.",
        ),
    ],
    "fr-grammar-complete-b2-06": [
        (
            "Complete: J'___ hâte de vous revoir.",
            ["ai", "suis", "fais", "prends"],
            0,
            "Avoir hâte de…",
            "J'ai hâte de vous revoir.",
        ),
        (
            "Complete: Ça ___ le coup.",
            ["fait", "vaut", "prend", "donne"],
            1,
            "Ça vaut le coup = vale a pena.",
            "Ça vaut le coup.",
        ),
        (
            "Complete: Tu peux me ___ au courant ?",
            ["mettre", "faire", "tenir", "dire"],
            2,
            "Tenir quelqu'un au courant.",
            "Tu peux me tenir au courant ?",
        ),
        (
            "Complete: Vous êtes ___ répondre demain.",
            ["pensé", "voulu", "dû", "censé"],
            3,
            "Être censé + infinitivo.",
            "Vous êtes censé répondre demain.",
        ),
        (
            "Complete: On va ___ un coup d'œil.",
            ["jeter", "faire", "prendre", "donner"],
            0,
            "Jeter un coup d'œil.",
            "On va jeter un coup d'œil.",
        ),
        (
            "Complete: Ce n'est pas ___ de s'inquiéter.",
            ["de refus", "la peine", "le cas", "le moment"],
            1,
            "Ce n'est pas la peine de…",
            "Ce n'est pas la peine de s'inquiéter.",
        ),
        (
            "Complete: Il faut ___ attention aux détails.",
            ["prendre", "mettre", "faire", "avoir"],
            2,
            "Faire attention à…",
            "Il faut faire attention aux détails.",
        ),
        (
            "Complete: Elle a ___ de nouvelles idées.",
            ["plein", "le plein", "en plein", "plein de"],
            3,
            "Avoir plein de = ter um montão de (informal).",
            "Elle a plein de nouvelles idées.",
        ),
        (
            "Complete: On est ___ d'accord.",
            ["bel et bien", "peu", "à peine", "loin"],
            0,
            "Bel et bien = de fato.",
            "On est bel et bien d'accord.",
        ),
        (
            "Complete: Il ___ de se dépêcher.",
            ["vaut le coup", "vaut mieux", "fait mieux", "prend mieux"],
            1,
            "Il vaut mieux + infinitivo.",
            "Il vaut mieux se dépêcher.",
        ),
    ],
}


def get_banks() -> dict[str, list[tuple[str, list[str], int, str, str]]]:
    return BANKS


if __name__ == "__main__":
    counts = {k: len(v) for k, v in BANKS.items()}
    print(f"topics={len(BANKS)}")
    for tid, n in sorted(counts.items()):
        print(f"  {tid}: {n}")
    print(f"total_exercises={sum(counts.values())}")
