-- Gerado por scripts/generate-extended-grammar.mjs.

insert into public.grammar_topics (
  id, language, level, title, overview_pt_br, formation_pt_br,
  use_cases, common_mistakes, notes_pt_br, sort_order
) values
  ('en-grammar-extra-01', 'en', 'A1', 'Preposições de lugar, tempo e movimento', 'As preposições inglesas não correspondem palavra por palavra ao português. A escolha depende de como o falante representa lugar, período ou deslocamento.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Lugar: at para ponto, in para área ou interior e on para superfície. Tempo: at + hora, on + dia e in + mês, ano ou período. Movimento: to, into, onto, from e through.', '[{"title_pt_br":"Lugar","explanation_pt_br":"Use at para um ponto, in para um espaço e on para uma superfície.","examples":[{"target":"The keys are on the table.","translation_pt_br":"As chaves estão sobre a mesa."}]},{"title_pt_br":"Tempo","explanation_pt_br":"A precisão cresce de in para on e at.","examples":[{"target":"The meeting is on Monday at nine.","translation_pt_br":"A reunião é na segunda-feira às nove."}]},{"title_pt_br":"Movimento","explanation_pt_br":"Into destaca entrada; to indica destino.","examples":[{"target":"She walked into the room.","translation_pt_br":"Ela entrou caminhando na sala."}]}]'::jsonb, '[{"incorrect":"I work in Monday.","correct":"I work on Monday.","explanation_pt_br":"Dias da semana usam on."},{"incorrect":"She arrived to the airport.","correct":"She arrived at the airport.","explanation_pt_br":"Arrive usa at para pontos e in para cidades ou países."}]'::jsonb, '["Não traduza em/no/na automaticamente como in.","Memorize preposição junto com a expressão."]'::jsonb, 101),
  ('en-grammar-extra-02', 'en', 'A2', 'Conjunções coordenativas e subordinativas', 'Conjunções ligam ideias e deixam a fala menos fragmentada. Elas podem adicionar, contrastar, apresentar causa, consequência, condição ou tempo.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Coordenação: and, but, or, so e yet. Subordinação: because, although, if, when, while, before e after + oração.', '[{"title_pt_br":"Causa e consequência","explanation_pt_br":"Because apresenta causa; so introduz resultado.","examples":[{"target":"I stayed home because it was raining.","translation_pt_br":"Fiquei em casa porque estava chovendo."}]},{"title_pt_br":"Contraste","explanation_pt_br":"Although inicia uma concessão; but conecta duas orações independentes.","examples":[{"target":"Although I was tired, I finished the report.","translation_pt_br":"Embora estivesse cansado, terminei o relatório."}]},{"title_pt_br":"Condição","explanation_pt_br":"If apresenta a condição necessária.","examples":[{"target":"If you need help, call me.","translation_pt_br":"Se precisar de ajuda, ligue para mim."}]}]'::jsonb, '[{"incorrect":"Because it rained, so I stayed home.","correct":"Because it rained, I stayed home.","explanation_pt_br":"Não combine because e so na mesma relação."},{"incorrect":"Although she was tired, but she continued.","correct":"Although she was tired, she continued.","explanation_pt_br":"Although já marca o contraste."}]'::jsonb, '["Use vírgula quando a oração subordinada vier primeiro.","Yet expressa contraste mais enfático que but."]'::jsonb, 102),
  ('en-grammar-extra-03', 'en', 'A2', 'Phrasal verbs essenciais', 'Phrasal verbs combinam verbo e partícula e formam um significado próprio. A partícula pode alterar completamente o sentido do verbo original.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Inseparáveis: look after someone. Separáveis: turn the light off ou turn off the light; com pronome, turn it off. Alguns são intransitivos: wake up.', '[{"title_pt_br":"Rotina","explanation_pt_br":"Wake up, get up, put on e take off descrevem ações frequentes.","examples":[{"target":"I wake up at seven and put on my jacket.","translation_pt_br":"Acordo às sete e visto minha jaqueta."}]},{"title_pt_br":"Interação","explanation_pt_br":"Find out, look for e pick up aparecem em situações cotidianas.","examples":[{"target":"I need to find out the train time.","translation_pt_br":"Preciso descobrir o horário do trem."}]},{"title_pt_br":"Cuidado","explanation_pt_br":"Look after significa cuidar, não olhar depois.","examples":[{"target":"Can you look after my dog?","translation_pt_br":"Você pode cuidar do meu cachorro?"}]}]'::jsonb, '[{"incorrect":"Turn off it.","correct":"Turn it off.","explanation_pt_br":"Pronomes ficam entre verbo e partícula nos separáveis."},{"incorrect":"I am looking my keys.","correct":"I am looking for my keys.","explanation_pt_br":"Look for significa procurar."}]'::jsonb, '["Aprenda cada phrasal verb com uma frase.","Confira se ele é separável no dicionário."]'::jsonb, 103),
  ('en-grammar-extra-04', 'en', 'B1', 'Conectores para organizar ideias', 'Conectores orientam o leitor ou ouvinte sobre a relação lógica entre partes do discurso. Eles são essenciais para respostas longas e textos coesos.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Adição: moreover, in addition. Contraste: however, whereas. Resultado: therefore, as a result. Exemplificação: for instance. Sequência: first, then, finally.', '[{"title_pt_br":"Contraste formal","explanation_pt_br":"However costuma iniciar uma nova oração e recebe pontuação.","examples":[{"target":"The plan is expensive. However, it may save time.","translation_pt_br":"O plano é caro. Entretanto, pode economizar tempo."}]},{"title_pt_br":"Resultado","explanation_pt_br":"Therefore e as a result apresentam uma conclusão lógica.","examples":[{"target":"Demand increased; therefore, we hired more staff.","translation_pt_br":"A demanda aumentou; portanto, contratamos mais pessoas."}]},{"title_pt_br":"Exemplo","explanation_pt_br":"For example e for instance concretizam uma afirmação.","examples":[{"target":"Some habits improve sleep; for instance, avoiding screens.","translation_pt_br":"Alguns hábitos melhoram o sono; por exemplo, evitar telas."}]}]'::jsonb, '[{"incorrect":"However the plan is useful.","correct":"However, the plan is useful.","explanation_pt_br":"Como advérbio conector inicial, however pede vírgula."},{"incorrect":"Because demand rose. Therefore we hired.","correct":"Demand rose; therefore, we hired.","explanation_pt_br":"Evite fragmentos e pontue a relação entre orações."}]'::jsonb, '["Conectores não substituem uma relação lógica clara.","Varie os conectores sem usar termos excessivamente formais na fala casual."]'::jsonb, 104),
  ('en-grammar-extra-05', 'en', 'B1', 'Gerúndio e infinitivo', 'Depois de certos verbos, o inglês exige forma em -ing ou infinitivo com to. Alguns verbos aceitam ambos, às vezes com mudança importante de significado.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Enjoy, avoid, suggest + -ing. Want, decide, need + to + verbo. Make/let + objeto + verbo sem to. Stop/remember/try mudam de sentido conforme a forma.', '[{"title_pt_br":"Preferência e decisão","explanation_pt_br":"Enjoy seleciona -ing; decide seleciona infinitivo.","examples":[{"target":"She enjoys reading but decided to study law.","translation_pt_br":"Ela gosta de ler, mas decidiu estudar direito."}]},{"title_pt_br":"Mudança de sentido","explanation_pt_br":"Stop doing encerra uma ação; stop to do interrompe algo para realizar outra ação.","examples":[{"target":"He stopped smoking.","translation_pt_br":"Ele parou de fumar."}]},{"title_pt_br":"Tentativa","explanation_pt_br":"Try doing testa uma solução; try to do enfatiza o esforço.","examples":[{"target":"Try restarting the computer.","translation_pt_br":"Tente reiniciar o computador."}]}]'::jsonb, '[{"incorrect":"I enjoy to travel.","correct":"I enjoy traveling.","explanation_pt_br":"Enjoy é seguido de gerúndio."},{"incorrect":"She suggested to leave.","correct":"She suggested leaving.","explanation_pt_br":"Suggest seleciona forma em -ing."}]'::jsonb, '["Registre o verbo junto com seu complemento.","O uso britânico e americano pode variar na grafia de traveling/travelling."]'::jsonb, 105),
  ('en-grammar-extra-06', 'en', 'B1', 'Collocations e expressões frequentes', 'Collocations são combinações que os falantes consideram naturais. Mesmo uma frase gramatical pode soar artificial quando usa uma combinação improvável.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Verbo + substantivo: make a decision, take a break, have a chance, do research. Adjetivo + substantivo: heavy rain, strong opinion. Expressões devem ser aprendidas em blocos.', '[{"title_pt_br":"Make e do","explanation_pt_br":"Make costuma criar ou produzir; do se liga a tarefas e atividades.","examples":[{"target":"We need to make a decision after doing more research.","translation_pt_br":"Precisamos tomar uma decisão após fazer mais pesquisa."}]},{"title_pt_br":"Take e have","explanation_pt_br":"Take aparece em ações delimitadas; have em experiências ou posse.","examples":[{"target":"Let''s take a break and have a coffee.","translation_pt_br":"Vamos fazer uma pausa e tomar um café."}]},{"title_pt_br":"Intensidade natural","explanation_pt_br":"Dizemos heavy rain e strong coffee, não strong rain.","examples":[{"target":"Heavy rain caused serious damage.","translation_pt_br":"A chuva forte causou danos graves."}]}]'::jsonb, '[{"incorrect":"Do a decision.","correct":"Make a decision.","explanation_pt_br":"Decision forma collocation com make."},{"incorrect":"A powerful rain.","correct":"Heavy rain.","explanation_pt_br":"Heavy é a combinação convencional com rain."}]'::jsonb, '["Use corpus ou dicionário de collocations.","Aprender blocos melhora fluência e precisão."]'::jsonb, 106),
  ('en-grammar-extra-07', 'en', 'B2', 'Phrasal verbs avançados e registro', 'Em níveis avançados, phrasal verbs expressam processos abstratos e variam de registro. Em textos formais, muitas vezes existe um verbo latino equivalente.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Carry out = perform; put off = postpone; bring up = mention; come up with = devise; rule out = eliminate; put up with = tolerate.', '[{"title_pt_br":"Trabalho e pesquisa","explanation_pt_br":"Carry out e follow up descrevem execução e acompanhamento.","examples":[{"target":"The team carried out the study and followed up on the results.","translation_pt_br":"A equipe realizou o estudo e acompanhou os resultados."}]},{"title_pt_br":"Discussão","explanation_pt_br":"Bring up introduz um assunto; point out chama atenção para um aspecto.","examples":[{"target":"She brought up the budget and pointed out a risk.","translation_pt_br":"Ela levantou o orçamento e apontou um risco."}]},{"title_pt_br":"Solução","explanation_pt_br":"Come up with cria uma ideia; rule out elimina uma hipótese.","examples":[{"target":"We came up with a solution after ruling out two options.","translation_pt_br":"Encontramos uma solução após descartar duas opções."}]}]'::jsonb, '[{"incorrect":"We carried the research.","correct":"We carried out the research.","explanation_pt_br":"Carry out significa realizar uma atividade planejada."},{"incorrect":"She brought the issue up it.","correct":"She brought the issue up.","explanation_pt_br":"Não repita o objeto após um phrasal verb separável."}]'::jsonb, '["Prefira equivalentes formais quando o gênero exigir.","A posição do objeto depende da separabilidade."]'::jsonb, 107),
  ('en-grammar-extra-08', 'en', 'B2', 'Idioms, nuance e linguagem figurada', 'Expressões idiomáticas não podem ser interpretadas literalmente. Elas carregam tom, contexto cultural e grau de formalidade, por isso devem ser usadas com moderação.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Idioms funcionam como blocos: get the ball rolling, be on the same page, take something with a grain of salt, miss the point. O contexto determina tempo e concordância.', '[{"title_pt_br":"Colaboração","explanation_pt_br":"Be on the same page indica entendimento compartilhado.","examples":[{"target":"Let''s confirm the goals so everyone is on the same page.","translation_pt_br":"Vamos confirmar as metas para que todos estejam alinhados."}]},{"title_pt_br":"Ceticismo","explanation_pt_br":"Take with a grain of salt recomenda não aceitar algo totalmente.","examples":[{"target":"Take those predictions with a grain of salt.","translation_pt_br":"Considere essas previsões com cautela."}]},{"title_pt_br":"Início de ação","explanation_pt_br":"Get the ball rolling significa iniciar um processo.","examples":[{"target":"A short meeting will get the ball rolling.","translation_pt_br":"Uma reunião curta dará início ao processo."}]}]'::jsonb, '[{"incorrect":"We are in the same page.","correct":"We are on the same page.","explanation_pt_br":"A expressão fixa usa on."},{"incorrect":"Let''s start the ball rolling it.","correct":"Let''s get the ball rolling.","explanation_pt_br":"Não altere livremente uma expressão cristalizada."}]'::jsonb, '["Evite idioms em contratos e instruções críticas.","Confirme o registro antes de usar uma expressão cultural."]'::jsonb, 108),
  ('es-grammar-extra-01', 'es', 'A1', 'Preposiciones básicas: a, de, en, con', 'As preposições espanholas parecem próximas do português, mas apresentam regências próprias. A escolha correta depende de destino, origem, localização, companhia e modo.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'A indica destino e hora; de indica origem e posse; en marca localização e meio; con expressa companhia ou instrumento. Al e del são contrações obrigatórias.', '[{"title_pt_br":"Destino e localização","explanation_pt_br":"Use a para movimento e en para posição.","examples":[{"target":"Voy al mercado y estoy en la tienda.","translation_pt_br":"Vou ao mercado e estou na loja."}]},{"title_pt_br":"Origem e posse","explanation_pt_br":"De liga origem, matéria ou possuidor.","examples":[{"target":"El libro de Ana viene de Madrid.","translation_pt_br":"O livro de Ana vem de Madri."}]},{"title_pt_br":"Companhia","explanation_pt_br":"Con apresenta companhia ou instrumento.","examples":[{"target":"Hablo con mi profesor.","translation_pt_br":"Falo com meu professor."}]}]'::jsonb, '[{"incorrect":"Voy en Madrid.","correct":"Voy a Madrid.","explanation_pt_br":"Destinos usam a."},{"incorrect":"Vengo a Brasil.","correct":"Vengo de Brasil.","explanation_pt_br":"Origem usa de."}]'::jsonb, '["A + el = al; de + el = del.","Meios de transporte geralmente usam en."]'::jsonb, 101),
  ('es-grammar-extra-02', 'es', 'A2', 'Por e para', 'Por e para frequentemente correspondem a por ou para em português, mas organizam causa, meio, percurso, troca, finalidade, destino e prazo de maneiras diferentes.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Por: causa, meio, duração aproximada, percurso e troca. Para: finalidade, destinatário, destino, opinião e prazo.', '[{"title_pt_br":"Causa e finalidade","explanation_pt_br":"Por explica o motivo; para apresenta o objetivo.","examples":[{"target":"Estudio por interés y para trabajar en España.","translation_pt_br":"Estudo por interesse e para trabalhar na Espanha."}]},{"title_pt_br":"Meio e destinatário","explanation_pt_br":"Por indica canal; para indica quem recebe.","examples":[{"target":"Te envié el documento por correo para tu jefe.","translation_pt_br":"Enviei o documento por e-mail para seu chefe."}]},{"title_pt_br":"Prazo","explanation_pt_br":"Para seguido de data marca limite.","examples":[{"target":"Necesito el informe para el viernes.","translation_pt_br":"Preciso do relatório para sexta-feira."}]}]'::jsonb, '[{"incorrect":"Trabajo por ganar dinero.","correct":"Trabajo para ganar dinero.","explanation_pt_br":"Uma finalidade usa para."},{"incorrect":"Este regalo es por ti.","correct":"Este regalo es para ti.","explanation_pt_br":"Destinatário usa para."}]'::jsonb, '["Gracias por e perdón por são combinações fixas.","Estar por + infinitivo pode indicar algo ainda não feito."]'::jsonb, 102),
  ('es-grammar-extra-03', 'es', 'A2', 'Conjunciones y conectores básicos', 'Conjunções unem palavras e orações; conectores mostram adição, contraste, causa, consequência, condição e sequência no discurso.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Y/e adicionam; o/u apresentam alternativa; pero e aunque contrastam; porque explica causa; por eso mostra consequência; si introduz condição.', '[{"title_pt_br":"Mudanças eufônicas","explanation_pt_br":"Y vira e antes de som /i/; o vira u antes de som /o/.","examples":[{"target":"Estudio español e italiano.","translation_pt_br":"Estudo espanhol e italiano."}]},{"title_pt_br":"Causa e resultado","explanation_pt_br":"Porque responde por quê; por eso apresenta efeito.","examples":[{"target":"Llovía, por eso tomé un taxi.","translation_pt_br":"Chovia, por isso peguei um táxi."}]},{"title_pt_br":"Concessão","explanation_pt_br":"Aunque reconhece uma dificuldade sem cancelar a ideia principal.","examples":[{"target":"Aunque estaba cansada, salió.","translation_pt_br":"Embora estivesse cansada, saiu."}]}]'::jsonb, '[{"incorrect":"No fui por qué estaba enfermo.","correct":"No fui porque estaba enfermo.","explanation_pt_br":"Porque causal é escrito junto e sem acento."},{"incorrect":"Aunque llovía, pero salimos.","correct":"Aunque llovía, salimos.","explanation_pt_br":"Embora já marca o contraste."}]'::jsonb, '["E e u dependem do som seguinte.","Sino corrige uma negação; pero apenas contrasta."]'::jsonb, 103),
  ('es-grammar-extra-04', 'es', 'B1', 'Perífrasis verbales', 'O espanhol usa combinações de verbo auxiliar e forma não pessoal para indicar início, continuidade, obrigação, hábito, repetição ou término de uma ação.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Ir a + infinitivo; tener que/deber + infinitivo; estar/seguir + gerúndio; acabar de + infinitivo; volver a + infinitivo; dejar de + infinitivo.', '[{"title_pt_br":"Fase da ação","explanation_pt_br":"Empezar a inicia, seguir + gerúndio continua e dejar de encerra.","examples":[{"target":"Empezó a llover y siguió lloviendo toda la tarde.","translation_pt_br":"Começou a chover e continuou chovendo toda a tarde."}]},{"title_pt_br":"Passado recente","explanation_pt_br":"Acabar de expressa algo recém-concluído.","examples":[{"target":"Acabo de terminar el informe.","translation_pt_br":"Acabei de terminar o relatório."}]},{"title_pt_br":"Repetição","explanation_pt_br":"Volver a + infinitivo indica fazer novamente.","examples":[{"target":"Volvió a llamar por la noche.","translation_pt_br":"Ligou novamente à noite."}]}]'::jsonb, '[{"incorrect":"Estoy estudiar.","correct":"Estoy estudiando.","explanation_pt_br":"Estar progressivo exige gerúndio."},{"incorrect":"Acabo terminar.","correct":"Acabo de terminar.","explanation_pt_br":"A perífrase exige de."}]'::jsonb, '["Deber de pode indicar probabilidade; deber indica obrigação.","Nem toda sequência de dois verbos é uma perífrase."]'::jsonb, 104),
  ('es-grammar-extra-05', 'es', 'B1', 'Usos de se', 'Se exerce várias funções em espanhol: reflexiva, recíproca, impessoal, passiva e substituição de le/les antes de lo/la/los/las.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Reflexivo: se lava. Recíproco: se ayudan. Impessoal: se vive bien. Passiva: se venden pisos. Le/les + lo vira se lo.', '[{"title_pt_br":"Impessoal e passiva","explanation_pt_br":"A impessoal não tem sujeito específico; a passiva concorda com o objeto.","examples":[{"target":"Se vive bien aquí. Se venden casas.","translation_pt_br":"Vive-se bem aqui. Vendem-se casas."}]},{"title_pt_br":"Pronomes combinados","explanation_pt_br":"Le/les tornam-se se diante de pronome acusativo.","examples":[{"target":"Se lo expliqué ayer.","translation_pt_br":"Expliquei isso a ele ontem."}]},{"title_pt_br":"Mudança lexical","explanation_pt_br":"Alguns verbos pronominais mudam de sentido.","examples":[{"target":"María acordó la fecha y se acordó de la cita.","translation_pt_br":"Maria combinou a data e se lembrou do compromisso."}]}]'::jsonb, '[{"incorrect":"Se vende casas.","correct":"Se venden casas.","explanation_pt_br":"Na passiva com nome plural, o verbo concorda."},{"incorrect":"Le lo dije.","correct":"Se lo dije.","explanation_pt_br":"Le muda para se antes de lo."}]'::jsonb, '["Identifique primeiro se existe sujeito gramatical.","Verbos pronominais devem ser aprendidos com a preposição."]'::jsonb, 105),
  ('es-grammar-extra-06', 'es', 'B1', 'Conectores discursivos', 'Conectores organizam argumentos e tornam relações explícitas. A escolha depende da função lógica e do grau de formalidade.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Adição: además, asimismo. Contraste: sin embargo, en cambio. Consequência: por lo tanto, así que. Exemplo: por ejemplo. Reformulação: es decir.', '[{"title_pt_br":"Contraste","explanation_pt_br":"Sin embargo contrapõe uma ideia anterior e costuma vir isolado.","examples":[{"target":"El plan es caro; sin embargo, es eficaz.","translation_pt_br":"O plano é caro; no entanto, é eficaz."}]},{"title_pt_br":"Reformulação","explanation_pt_br":"Es decir esclarece a mesma ideia.","examples":[{"target":"La medida es provisional, es decir, no será permanente.","translation_pt_br":"A medida é provisória, ou seja, não será permanente."}]},{"title_pt_br":"Conclusão","explanation_pt_br":"Por lo tanto apresenta inferência.","examples":[{"target":"No había pruebas; por lo tanto, cerraron el caso.","translation_pt_br":"Não havia provas; portanto, encerraram o caso."}]}]'::jsonb, '[{"incorrect":"Sin embargo de ser caro.","correct":"A pesar de ser caro.","explanation_pt_br":"Sin embargo conecta orações; a pesar de rege nome ou infinitivo."},{"incorrect":"Pienso de que vendrá.","correct":"Pienso que vendrá.","explanation_pt_br":"Pensar que não usa de; evite dequeísmo."}]'::jsonb, '["Pontue conectores parentéticos com vírgulas.","Não acumule vários conectores com a mesma função."]'::jsonb, 106),
  ('es-grammar-extra-07', 'es', 'B2', 'Subjuntivo e particularidades de uso', 'O subjuntivo espanhol apresenta fatos como desejados, avaliados, duvidosos ou ainda não realizados. Ele depende do sentido da oração principal e do referente.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Desejo/ordem: querer que. Avaliação: es importante que. Dúvida: dudar que. Futuro temporal: cuando + subjuntivo. Antecedente inexistente: busco alguien que sepa.', '[{"title_pt_br":"Desejo e avaliação","explanation_pt_br":"Sujeitos diferentes exigem que + subjuntivo.","examples":[{"target":"Quiero que vengas temprano.","translation_pt_br":"Quero que você venha cedo."}]},{"title_pt_br":"Referente desconhecido","explanation_pt_br":"O subjuntivo indica que a existência não é confirmada.","examples":[{"target":"Busco un hotel que tenga piscina.","translation_pt_br":"Procuro um hotel que tenha piscina."}]},{"title_pt_br":"Futuro","explanation_pt_br":"Depois de cuando, use subjuntivo para evento futuro.","examples":[{"target":"Cuando llegues, llámame.","translation_pt_br":"Quando você chegar, ligue para mim."}]}]'::jsonb, '[{"incorrect":"Quiero que vienes.","correct":"Quiero que vengas.","explanation_pt_br":"Desejo sobre outro sujeito pede subjuntivo."},{"incorrect":"Cuando llegarás, avísame.","correct":"Cuando llegues, avísame.","explanation_pt_br":"Evento futuro após cuando usa presente do subjuntivo."}]'::jsonb, '["O mesmo verbo pode alternar modo conforme certeza.","O pretérito imperfeito do subjuntivo tem formas -ra e -se."]'::jsonb, 107),
  ('es-grammar-extra-08', 'es', 'B2', 'Expresiones idiomáticas y colocaciones', 'Expressões fixas e colocações revelam naturalidade, mas não devem ser traduzidas literalmente. Elas também variam entre regiões hispânicas.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Darse cuenta de, echar de menos, tener en cuenta, llevar a cabo, tomar una decisión, estar de acuerdo. A regência faz parte da expressão.', '[{"title_pt_br":"Percepção e saudade","explanation_pt_br":"Darse cuenta de é perceber; echar de menos é sentir falta.","examples":[{"target":"Me di cuenta del error y eché de menos tu ayuda.","translation_pt_br":"Percebi o erro e senti falta da sua ajuda."}]},{"title_pt_br":"Planejamento","explanation_pt_br":"Tener en cuenta considera; llevar a cabo executa.","examples":[{"target":"Tuvimos en cuenta los riesgos antes de llevar a cabo el plan.","translation_pt_br":"Consideramos os riscos antes de executar o plano."}]},{"title_pt_br":"Acordo","explanation_pt_br":"Estar de acuerdo con expressa concordância.","examples":[{"target":"Estoy de acuerdo contigo.","translation_pt_br":"Concordo com você."}]}]'::jsonb, '[{"incorrect":"Realicé cuenta del error.","correct":"Me di cuenta del error.","explanation_pt_br":"A expressão fixa é darse cuenta de."},{"incorrect":"Estoy de acuerdo a ti.","correct":"Estoy de acuerdo contigo.","explanation_pt_br":"A expressão rege con."}]'::jsonb, '["Confira a região antes de usar gírias.","Aprenda a expressão com seus pronomes e preposições."]'::jsonb, 108),
  ('fr-grammar-extra-01', 'fr', 'A1', 'Prépositions de lieu et de temps', 'As preposições francesas variam conforme gênero, número, tipo de lugar e relação espacial. Países, cidades e meios de transporte exigem padrões específicos.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'À + cidade; en + país feminino ou iniciado por vogal; au + país masculino; aux + plural. Tempo: à + hora, en + mês/ano, le + dia habitual, depuis + duração em curso.', '[{"title_pt_br":"Destinos","explanation_pt_br":"Cidades usam à; países alternam en, au e aux.","examples":[{"target":"Je vais à Paris et au Canada.","translation_pt_br":"Vou a Paris e ao Canadá."}]},{"title_pt_br":"Localização","explanation_pt_br":"Dans indica interior; sur indica superfície; chez indica casa ou estabelecimento de alguém.","examples":[{"target":"Le livre est sur la table chez Marie.","translation_pt_br":"O livro está sobre a mesa na casa de Marie."}]},{"title_pt_br":"Tempo","explanation_pt_br":"Depuis liga uma duração ao presente.","examples":[{"target":"J''habite ici depuis deux ans.","translation_pt_br":"Moro aqui há dois anos."}]}]'::jsonb, '[{"incorrect":"Je vais en Canada.","correct":"Je vais au Canada.","explanation_pt_br":"País masculino usa au."},{"incorrect":"Je suis à la maison de Paul.","correct":"Je suis chez Paul.","explanation_pt_br":"Chez expressa casa ou estabelecimento de pessoa."}]'::jsonb, '["Aprenda o gênero junto com o nome do país.","En train, en voiture, mas à pied e à vélo."]'::jsonb, 101),
  ('fr-grammar-extra-02', 'fr', 'A2', 'Conjonctions essentielles', 'Conjunções francesas ligam ideias de adição, oposição, causa, consequência, condição, finalidade e tempo. Algumas exigem indicativo e outras subjuntivo.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Et, mais, ou, donc, car; parce que + causa; puisque + causa conhecida; si + condição; quand/lorsque + tempo; pour que + subjuntivo.', '[{"title_pt_br":"Causa","explanation_pt_br":"Parce que responde pourquoi; puisque retoma causa evidente.","examples":[{"target":"Je reste parce qu''il pleut.","translation_pt_br":"Fico porque está chovendo."}]},{"title_pt_br":"Condição","explanation_pt_br":"Si + presente combina com futuro na consequência.","examples":[{"target":"Si tu viens, nous dînerons ensemble.","translation_pt_br":"Se você vier, jantaremos juntos."}]},{"title_pt_br":"Finalidade","explanation_pt_br":"Pour + infinitivo com mesmo sujeito; pour que + subjuntivo com sujeitos diferentes.","examples":[{"target":"Je parle lentement pour que tu comprennes.","translation_pt_br":"Falo devagar para que você entenda."}]}]'::jsonb, '[{"incorrect":"Si j''aurai le temps, je viendrai.","correct":"Si j''ai le temps, je viendrai.","explanation_pt_br":"Depois de si condicional não se usa futuro."},{"incorrect":"Parce de il pleut.","correct":"Parce qu''il pleut.","explanation_pt_br":"A conjunção correta é parce que."}]'::jsonb, '["Car é mais escrito e não costuma responder diretamente pourquoi.","Embora quoique seja possível, bien que é mais frequente."]'::jsonb, 102),
  ('fr-grammar-extra-03', 'fr', 'A2', 'Articles partitifs et quantité', 'O francês usa artigos partitivos para quantidades não contáveis ou não especificadas. Depois de negação e expressões de quantidade, a forma geralmente muda para de.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Du, de la, de l'', des para quantidade indefinida. Depois de ne...pas: de/d''. Quantidade: beaucoup de, un peu de. Verbo aimer prefere artigo definido.', '[{"title_pt_br":"Alimentos e matérias","explanation_pt_br":"Use partitivo quando a quantidade não é contada.","examples":[{"target":"Je bois du café et je mange de la soupe.","translation_pt_br":"Bebo café e tomo sopa."}]},{"title_pt_br":"Negação","explanation_pt_br":"O partitivo vira de na negação.","examples":[{"target":"Je ne bois pas de café.","translation_pt_br":"Não bebo café."}]},{"title_pt_br":"Preferência","explanation_pt_br":"Aimer usa le/la/les para categoria geral.","examples":[{"target":"J''aime le fromage.","translation_pt_br":"Gosto de queijo."}]}]'::jsonb, '[{"incorrect":"Je veux de le pain.","correct":"Je veux du pain.","explanation_pt_br":"De + le contrai para du."},{"incorrect":"Je ne mange pas du sucre.","correct":"Je ne mange pas de sucre.","explanation_pt_br":"Na negação, use de."}]'::jsonb, '["Com être, o artigo costuma permanecer após negação.","Des pode ser partitivo plural ou artigo indefinido plural."]'::jsonb, 103),
  ('fr-grammar-extra-04', 'fr', 'B1', 'Pronoms y et en', 'Y e en substituem complementos e evitam repetições. A escolha depende da preposição e do tipo de referente, não apenas da tradução.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Y substitui lugar ou à + coisa. En substitui de + coisa, origem ou quantidade. Ficam antes do verbo conjugado; no imperativo afirmativo, depois.', '[{"title_pt_br":"Y","explanation_pt_br":"Substitui destino/local ou complemento com à.","examples":[{"target":"Tu vas à Lyon ? Oui, j''y vais.","translation_pt_br":"Você vai a Lyon? Sim, vou."}]},{"title_pt_br":"En","explanation_pt_br":"Substitui complemento com de ou quantidade.","examples":[{"target":"Tu veux du pain ? Oui, j''en veux deux morceaux.","translation_pt_br":"Quer pão? Sim, quero dois pedaços."}]},{"title_pt_br":"Imperativo","explanation_pt_br":"No afirmativo, use vas-y e prends-en.","examples":[{"target":"Vas-y et prends-en un.","translation_pt_br":"Vá e pegue um."}]}]'::jsonb, '[{"incorrect":"Je vais à Paris, j''en vais.","correct":"Je vais à Paris, j''y vais.","explanation_pt_br":"Destino usa y."},{"incorrect":"J''ai trois livres. J''en ai.","correct":"J''en ai trois.","explanation_pt_br":"A quantidade permanece depois do verbo."}]'::jsonb, '["Y e en normalmente não substituem pessoas.","A ordem com outros pronomes deve ser memorizada."]'::jsonb, 104),
  ('fr-grammar-extra-05', 'fr', 'B1', 'Connecteurs logiques', 'Conectores franceses estruturam explicações e argumentos. Eles sinalizam progressão, oposição, causa, consequência, exemplo, reformulação e conclusão.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'D''abord/ensuite/enfin; de plus; cependant/en revanche; en effet; par conséquent; par exemple; autrement dit; en conclusion.', '[{"title_pt_br":"Oposição","explanation_pt_br":"Cependant contrapõe; en revanche introduz compensação ou contraste.","examples":[{"target":"Le trajet est long ; cependant, il est agréable.","translation_pt_br":"O trajeto é longo; contudo, é agradável."}]},{"title_pt_br":"Explicação","explanation_pt_br":"En effet confirma ou explica a afirmação anterior.","examples":[{"target":"Il faut partir tôt. En effet, la route est chargée.","translation_pt_br":"É preciso sair cedo. De fato, a estrada está cheia."}]},{"title_pt_br":"Consequência","explanation_pt_br":"Par conséquent apresenta resultado lógico.","examples":[{"target":"Les coûts ont augmenté ; par conséquent, le projet a changé.","translation_pt_br":"Os custos aumentaram; consequentemente, o projeto mudou."}]}]'::jsonb, '[{"incorrect":"Malgré il pleut.","correct":"Bien qu''il pleuve.","explanation_pt_br":"Malgré rege nome; bien que introduz oração."},{"incorrect":"Cependant de ce problème.","correct":"Malgré ce problème.","explanation_pt_br":"Cependant é conector, não preposição."}]'::jsonb, '["Use pontuação para separar conectores parentéticos.","À l''oral, du coup é comum, mas menos formal."]'::jsonb, 105),
  ('fr-grammar-extra-06', 'fr', 'B1', 'Locutions verbales et expressions courantes', 'O francês cotidiano utiliza locuções que funcionam como uma unidade. Traduzir cada palavra separadamente produz construções artificiais.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Avoir besoin de, avoir envie de, faire attention à, se rendre compte de, être en train de, venir de + infinitif.', '[{"title_pt_br":"Necessidade e vontade","explanation_pt_br":"Avoir besoin de e avoir envie de são seguidos de nome ou infinitivo.","examples":[{"target":"J''ai besoin de partir, mais j''ai envie de rester.","translation_pt_br":"Preciso ir embora, mas quero ficar."}]},{"title_pt_br":"Ação em curso e recente","explanation_pt_br":"Être en train de enfatiza processo; venir de marca passado recente.","examples":[{"target":"Je viens de finir ce que j''étais en train de lire.","translation_pt_br":"Acabei de terminar o que estava lendo."}]},{"title_pt_br":"Percepção","explanation_pt_br":"Se rendre compte de significa perceber.","examples":[{"target":"Elle s''est rendu compte de son erreur.","translation_pt_br":"Ela percebeu seu erro."}]}]'::jsonb, '[{"incorrect":"Je suis besoin d''aide.","correct":"J''ai besoin d''aide.","explanation_pt_br":"A locução usa avoir."},{"incorrect":"Je réalise mon erreur.","correct":"Je me rends compte de mon erreur.","explanation_pt_br":"Para perceber, a expressão idiomática comum é se rendre compte de."}]'::jsonb, '["Rendu permanece invariável nessa construção tradicional.","Aprenda a preposição como parte da locução."]'::jsonb, 106),
  ('fr-grammar-extra-07', 'fr', 'B2', 'Subjonctif et particularités', 'O subjuntivo francês aparece após vontade, necessidade, emoção, dúvida, finalidade e várias conjunções. A alternância com indicativo depende de certeza e afirmação.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Il faut que, vouloir que, bien que, pour que, avant que + subjonctif. Je pense que + indicatif; je ne pense pas que + subjonctif frequente.', '[{"title_pt_br":"Necessidade","explanation_pt_br":"Il faut que exige subjuntivo.","examples":[{"target":"Il faut que vous soyez prêts.","translation_pt_br":"É preciso que vocês estejam prontos."}]},{"title_pt_br":"Concessão","explanation_pt_br":"Bien que apresenta fato reconhecido com subjuntivo.","examples":[{"target":"Bien qu''il soit tard, nous continuons.","translation_pt_br":"Embora seja tarde, continuamos."}]},{"title_pt_br":"Certeza e dúvida","explanation_pt_br":"A negação de opinião frequentemente abre espaço para subjuntivo.","examples":[{"target":"Je ne crois pas qu''il ait raison.","translation_pt_br":"Não acredito que ele tenha razão."}]}]'::jsonb, '[{"incorrect":"Il faut que tu es prêt.","correct":"Il faut que tu sois prêt.","explanation_pt_br":"Il faut que seleciona subjuntivo."},{"incorrect":"Après qu''il soit parti.","correct":"Après qu''il est parti.","explanation_pt_br":"Na norma-padrão, après que usa indicativo."}]'::jsonb, '["Ne explétif pode aparecer após avant que sem negar.","O subjuntivo imperfeito é literário; na fala usa-se o presente."]'::jsonb, 107),
  ('fr-grammar-extra-08', 'fr', 'B2', 'Registre, liaison et expressions idiomatiques', 'O francês muda bastante entre registro formal, neutro e familiar. Liaison, redução oral e expressões idiomáticas afetam compreensão e adequação social.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Formal: nous, ne...pas, cela. Informal: on, queda de ne, ça. Liaison obrigatória em les amis; proibida após et; opcional em muitos contextos.', '[{"title_pt_br":"Registro","explanation_pt_br":"On substitui nous na fala sem mudar necessariamente o sentido.","examples":[{"target":"On se retrouve vers huit heures ?","translation_pt_br":"A gente se encontra por volta das oito?"}]},{"title_pt_br":"Idioms","explanation_pt_br":"Avoir le cafard, coûter les yeux de la tête e poser un lapin são figurativos.","examples":[{"target":"Ce billet coûte les yeux de la tête.","translation_pt_br":"Esse bilhete custa os olhos da cara."}]},{"title_pt_br":"Liaison","explanation_pt_br":"Faça liaison em grupos fixos e evite após et.","examples":[{"target":"Les enfants ont un ami.","translation_pt_br":"As crianças têm um amigo."}]}]'::jsonb, '[{"incorrect":"Nous on allons partir.","correct":"On va partir.","explanation_pt_br":"Com on, o verbo fica na terceira pessoa singular."},{"incorrect":"Je suis chaud.","correct":"J''ai chaud.","explanation_pt_br":"Sensação de calor usa avoir chaud."}]'::jsonb, '["Evite gíria regional sem conhecer o contexto.","A queda de ne é comum na fala, mas não na escrita formal."]'::jsonb, 108),
  ('it-grammar-extra-01', 'it', 'A1', 'Preposizioni semplici e articolate', 'As preposições italianas combinam-se frequentemente com artigos. A escolha depende de lugar, origem, companhia, assunto, meio e finalidade.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Di, a, da, in, con, su, per, tra/fra. Com artigo: del, al, dal, nel, sul etc. Cidades usam a; muitos países usam in; pessoas e profissionais usam da.', '[{"title_pt_br":"Destino e localização","explanation_pt_br":"Use a com cidades e in com países ou certos lugares.","examples":[{"target":"Vado a Roma e vivo in Italia.","translation_pt_br":"Vou a Roma e moro na Itália."}]},{"title_pt_br":"Da","explanation_pt_br":"Da marca origem e também casa/consultório de alguém.","examples":[{"target":"Vengo dal Brasile e vado dal medico.","translation_pt_br":"Venho do Brasil e vou ao médico."}]},{"title_pt_br":"Preposição articulada","explanation_pt_br":"Preposição e artigo concordam com o nome.","examples":[{"target":"Il libro è sul tavolo.","translation_pt_br":"O livro está sobre a mesa."}]}]'::jsonb, '[{"incorrect":"Vado in Roma.","correct":"Vado a Roma.","explanation_pt_br":"Cidades normalmente usam a."},{"incorrect":"Sono a Italia.","correct":"Sono in Italia.","explanation_pt_br":"Países normalmente usam in."}]'::jsonb, '["Aprenda exceções como a casa e in ufficio.","Con il pode permanecer separado; col também existe."]'::jsonb, 101),
  ('it-grammar-extra-02', 'it', 'A2', 'Congiunzioni essenziali', 'Conjunções italianas conectam ideias de adição, alternativa, oposição, causa, consequência, condição, tempo e finalidade.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'E, o/oppure, ma/però; perché para causa ou finalidade; quindi/perciò para consequência; se para condição; quando/mentre para tempo.', '[{"title_pt_br":"Causa e consequência","explanation_pt_br":"Perché explica; quindi apresenta resultado.","examples":[{"target":"Sono stanco perché ho lavorato, quindi riposo.","translation_pt_br":"Estou cansado porque trabalhei, então descanso."}]},{"title_pt_br":"Contraste","explanation_pt_br":"Ma conecta diretamente; però pode mover-se na oração.","examples":[{"target":"È difficile, però è utile.","translation_pt_br":"É difícil, porém é útil."}]},{"title_pt_br":"Condição","explanation_pt_br":"Se + presente pode ter presente ou futuro na consequência.","examples":[{"target":"Se ho tempo, ti chiamerò.","translation_pt_br":"Se eu tiver tempo, ligarei para você."}]}]'::jsonb, '[{"incorrect":"Perché ero stanco, quindi sono uscito.","correct":"Poiché ero stanco, sono rimasto a casa.","explanation_pt_br":"Evite duplicar causa e consequência e preserve a lógica."},{"incorrect":"Anche se ma piove.","correct":"Anche se piove, usciamo.","explanation_pt_br":"Anche se já marca concessão."}]'::jsonb, '["Perché também significa para que com subjuntivo em registro cuidado.","Oppure é alternativa mais explícita que o."]'::jsonb, 102),
  ('it-grammar-extra-03', 'it', 'A2', 'Essere, avere e particularidades', 'Italiano usa essere ou avere em expressões que nem sempre coincidem com o português. A escolha também determina o auxiliar dos tempos compostos.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Avere fame/sete/caldo/freddo/paura e idade. Essere stanco/felice. Passato prossimo: muitos intransitivos de movimento usam essere e concordam.', '[{"title_pt_br":"Sensações","explanation_pt_br":"Fome, sede, calor e frio usam avere.","examples":[{"target":"Ho fame e ho freddo.","translation_pt_br":"Estou com fome e com frio."}]},{"title_pt_br":"Idade","explanation_pt_br":"Idade é expressa com avere.","examples":[{"target":"Mia sorella ha vent''anni.","translation_pt_br":"Minha irmã tem vinte anos."}]},{"title_pt_br":"Auxiliar","explanation_pt_br":"Com essere, o particípio concorda com sujeito.","examples":[{"target":"Maria è arrivata ieri.","translation_pt_br":"Maria chegou ontem."}]}]'::jsonb, '[{"incorrect":"Sono 30 anni.","correct":"Ho 30 anni.","explanation_pt_br":"Idade usa avere."},{"incorrect":"Ho arrivato tardi.","correct":"Sono arrivato tardi.","explanation_pt_br":"Arrivare forma passato prossimo com essere."}]'::jsonb, '["Verbos reflexivos sempre usam essere nos tempos compostos.","Alguns verbos mudam auxiliar conforme uso transitivo."]'::jsonb, 103),
  ('it-grammar-extra-04', 'it', 'B1', 'Ci e ne', 'Ci e ne substituem complementos e aparecem em muitos verbos pronominais. A interpretação depende da regência e do contexto.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Ci: lugar, a/su + coisa, companhia em algumas expressões. Ne: di + coisa, origem e quantidade. Antes do verbo; ligados ao infinitivo e imperativo.', '[{"title_pt_br":"Ci","explanation_pt_br":"Substitui lugar ou complemento com a.","examples":[{"target":"Vai a Milano? Sì, ci vado domani.","translation_pt_br":"Vai a Milão? Sim, vou amanhã."}]},{"title_pt_br":"Ne","explanation_pt_br":"Substitui di ou quantidade.","examples":[{"target":"Quanti libri hai? Ne ho tre.","translation_pt_br":"Quantos livros você tem? Tenho três."}]},{"title_pt_br":"Verbos pronominais","explanation_pt_br":"Farcela, andarsene e pensarci têm sentido próprio.","examples":[{"target":"Non ce la faccio; me ne vado.","translation_pt_br":"Não consigo; vou embora."}]}]'::jsonb, '[{"incorrect":"Vado a Roma e ne resto.","correct":"Vado a Roma e ci resto.","explanation_pt_br":"Lugar usa ci."},{"incorrect":"Ho tre libri. Ne ho.","correct":"Ne ho tre.","explanation_pt_br":"A quantidade permanece expressa."}]'::jsonb, '["Ci e ne normalmente não substituem pessoas.","Ce la e me ne mostram alteração dos pronomes combinados."]'::jsonb, 104),
  ('it-grammar-extra-05', 'it', 'B1', 'Connettivi per argomentare', 'Conectores italianos tornam explícita a estrutura de um argumento. Eles ajudam a ordenar, contrastar, explicar, exemplificar, concluir e reformular.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Innanzitutto, inoltre, tuttavia, invece, infatti, di conseguenza, per esempio, in altre parole, infine.', '[{"title_pt_br":"Contraste","explanation_pt_br":"Tuttavia introduz ressalva; invece opõe dois elementos.","examples":[{"target":"Il progetto è costoso; tuttavia, è efficace.","translation_pt_br":"O projeto é caro; contudo, é eficaz."}]},{"title_pt_br":"Explicação","explanation_pt_br":"Infatti confirma ou explica o que veio antes.","examples":[{"target":"Dobbiamo partire presto; infatti, ci sarà traffico.","translation_pt_br":"Precisamos sair cedo; de fato, haverá trânsito."}]},{"title_pt_br":"Consequência","explanation_pt_br":"Di conseguenza mostra resultado.","examples":[{"target":"I costi sono aumentati; di conseguenza, il piano è cambiato.","translation_pt_br":"Os custos aumentaram; consequentemente, o plano mudou."}]}]'::jsonb, '[{"incorrect":"Nonostante è caro.","correct":"Nonostante sia caro.","explanation_pt_br":"Nonostante + oração pede congiuntivo."},{"incorrect":"Tuttavia di questo problema.","correct":"Nonostante questo problema.","explanation_pt_br":"Tuttavia não funciona como preposição."}]'::jsonb, '["Comunque é versátil, mas pode soar vago se repetido.","Use pontuação ao deslocar conectores."]'::jsonb, 105),
  ('it-grammar-extra-06', 'it', 'B1', 'Verbi pronominali ed espressioni comuni', 'Verbos pronominais combinam verbo e partículas e adquirem significado idiomático. São o equivalente funcional mais próximo de muitos phrasal verbs.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Farcela = conseguir; cavarsela = se virar; andarsene = ir embora; metterci = levar tempo; volerci = ser necessário; prendersela = ficar ofendido.', '[{"title_pt_br":"Capacidade","explanation_pt_br":"Farcela e cavarsela avaliam capacidade ou desempenho.","examples":[{"target":"È difficile, ma ce la faccio.","translation_pt_br":"É difícil, mas eu consigo."}]},{"title_pt_br":"Tempo necessário","explanation_pt_br":"Metterci tem sujeito pessoal; volerci concorda com o que é necessário.","examples":[{"target":"Ci metto un''ora, ma ci vogliono due giorni per finire.","translation_pt_br":"Levo uma hora, mas são necessários dois dias para terminar."}]},{"title_pt_br":"Reação","explanation_pt_br":"Prendersela con alguém significa descontar ou ficar bravo.","examples":[{"target":"Non prendertela con me.","translation_pt_br":"Não fique bravo comigo."}]}]'::jsonb, '[{"incorrect":"Io faccio la.","correct":"Io ce la faccio.","explanation_pt_br":"Farcela exige as partículas ce e la."},{"incorrect":"Ci vuole due ore.","correct":"Ci vogliono due ore.","explanation_pt_br":"Volerci concorda com o elemento plural."}]'::jsonb, '["Conjugue o verbo e preserve as partículas.","No infinitivo, os pronomes ficam ligados: farcela."]'::jsonb, 106),
  ('it-grammar-extra-07', 'it', 'B2', 'Congiuntivo e periodo ipotetico', 'O congiuntivo italiano marca opinião subjetiva, dúvida, desejo, emoção e concessão. No período hipotético, tempos verbais distinguem possibilidade e irrealidade.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Penso che sia; dubito che venga; benché abbia. Hipótese real: se + indicativo. Possível: se + congiuntivo imperfetto, condizionale. Irreal passada: se + trapassato, condizionale passato.', '[{"title_pt_br":"Opinião e dúvida","explanation_pt_br":"Expressões não factuais selecionam congiuntivo.","examples":[{"target":"Penso che sia una buona idea.","translation_pt_br":"Acho que seja uma boa ideia."}]},{"title_pt_br":"Hipótese possível","explanation_pt_br":"Use imperfeito do subjuntivo e condicional.","examples":[{"target":"Se avessi tempo, viaggerei di più.","translation_pt_br":"Se tivesse tempo, viajaria mais."}]},{"title_pt_br":"Irreal passada","explanation_pt_br":"Use trapassato congiuntivo e condizionale passato.","examples":[{"target":"Se avessi studiato, avrei superato l''esame.","translation_pt_br":"Se tivesse estudado, teria passado na prova."}]}]'::jsonb, '[{"incorrect":"Penso che è giusto.","correct":"Penso che sia giusto.","explanation_pt_br":"Na norma cuidada, opinião subjetiva pede congiuntivo."},{"incorrect":"Se avrei tempo, viaggerei.","correct":"Se avessi tempo, viaggerei.","explanation_pt_br":"A oração com se não usa condicional."}]'::jsonb, '["Na fala informal, o indicativo cresce, mas o congiuntivo segue importante.","Depois de secondo me, o indicativo é comum."]'::jsonb, 107),
  ('it-grammar-extra-08', 'it', 'B2', 'Espressioni idiomatiche e collocazioni', 'Expressões idiomáticas e colocações tornam o italiano natural, mas carregam registro e contexto cultural. A tradução literal costuma falhar.

O módulo compara os contextos mais frequentes, a estrutura exigida e as diferenças que costumam causar interferência para falantes de português.', 'Prendere una decisione, fare attenzione, tenere conto di, rendersi conto di, dare una mano; idioms: essere al verde, in bocca al lupo, non vedere l''ora.', '[{"title_pt_br":"Colocações","explanation_pt_br":"Verbo e substantivo formam combinações convencionais.","examples":[{"target":"Dobbiamo prendere una decisione tenendo conto dei rischi.","translation_pt_br":"Precisamos tomar uma decisão considerando os riscos."}]},{"title_pt_br":"Ajuda e percepção","explanation_pt_br":"Dare una mano é ajudar; rendersi conto é perceber.","examples":[{"target":"Mi ha dato una mano e mi sono reso conto dell''errore.","translation_pt_br":"Ele me ajudou e percebi o erro."}]},{"title_pt_br":"Idioms","explanation_pt_br":"Non vedere l''ora expressa expectativa; essere al verde significa sem dinheiro.","examples":[{"target":"Non vedo l''ora di partire, ma sono al verde.","translation_pt_br":"Mal posso esperar para viajar, mas estou sem dinheiro."}]}]'::jsonb, '[{"incorrect":"Fare una decisione.","correct":"Prendere una decisione.","explanation_pt_br":"Decisione forma colocação com prendere."},{"incorrect":"Non vedo l''ora per partire.","correct":"Non vedo l''ora di partire.","explanation_pt_br":"A expressão rege di + infinitivo."}]'::jsonb, '["In bocca al lupo recebe tradicionalmente crepi il lupo.","Evite expressões muito regionais em contexto formal."]'::jsonb, 108);

insert into public.grammar_exercises (
  id, topic_id, language, level, title, explanation, example,
  question, options, answer_index, sort_order, is_published
) values
  ('en-grammar-extra-01-ex-1', 'en-grammar-extra-01', 'en', 'A1', 'Preposições de lugar, tempo e movimento · exercício 1', 'Dias da semana usam on.', 'I work on Monday.', 'Choose the correct sentence.', '["I work in Monday.","I work on Monday.","She arrived to the airport."]'::jsonb, 1, 1010, true),
  ('en-grammar-extra-01-ex-2', 'en-grammar-extra-01', 'en', 'A1', 'Preposições de lugar, tempo e movimento · exercício 2', 'Arrive usa at para pontos e in para cidades ou países.', 'She arrived at the airport.', 'Choose the correct sentence.', '["She arrived to the airport.","She arrived at the airport.","I work in Monday."]'::jsonb, 1, 1011, true),
  ('en-grammar-extra-02-ex-1', 'en-grammar-extra-02', 'en', 'A2', 'Conjunções coordenativas e subordinativas · exercício 1', 'Não combine because e so na mesma relação.', 'Because it rained, I stayed home.', 'Choose the correct sentence.', '["Because it rained, so I stayed home.","Because it rained, I stayed home.","Although she was tired, but she continued."]'::jsonb, 1, 1020, true),
  ('en-grammar-extra-02-ex-2', 'en-grammar-extra-02', 'en', 'A2', 'Conjunções coordenativas e subordinativas · exercício 2', 'Although já marca o contraste.', 'Although she was tired, she continued.', 'Choose the correct sentence.', '["Although she was tired, but she continued.","Although she was tired, she continued.","Because it rained, so I stayed home."]'::jsonb, 1, 1021, true),
  ('en-grammar-extra-03-ex-1', 'en-grammar-extra-03', 'en', 'A2', 'Phrasal verbs essenciais · exercício 1', 'Pronomes ficam entre verbo e partícula nos separáveis.', 'Turn it off.', 'Choose the correct sentence.', '["Turn off it.","Turn it off.","I am looking my keys."]'::jsonb, 1, 1030, true),
  ('en-grammar-extra-03-ex-2', 'en-grammar-extra-03', 'en', 'A2', 'Phrasal verbs essenciais · exercício 2', 'Look for significa procurar.', 'I am looking for my keys.', 'Choose the correct sentence.', '["I am looking my keys.","I am looking for my keys.","Turn off it."]'::jsonb, 1, 1031, true),
  ('en-grammar-extra-04-ex-1', 'en-grammar-extra-04', 'en', 'B1', 'Conectores para organizar ideias · exercício 1', 'Como advérbio conector inicial, however pede vírgula.', 'However, the plan is useful.', 'Choose the correct sentence.', '["However the plan is useful.","However, the plan is useful.","Because demand rose. Therefore we hired."]'::jsonb, 1, 1040, true),
  ('en-grammar-extra-04-ex-2', 'en-grammar-extra-04', 'en', 'B1', 'Conectores para organizar ideias · exercício 2', 'Evite fragmentos e pontue a relação entre orações.', 'Demand rose; therefore, we hired.', 'Choose the correct sentence.', '["Because demand rose. Therefore we hired.","Demand rose; therefore, we hired.","However the plan is useful."]'::jsonb, 1, 1041, true),
  ('en-grammar-extra-05-ex-1', 'en-grammar-extra-05', 'en', 'B1', 'Gerúndio e infinitivo · exercício 1', 'Enjoy é seguido de gerúndio.', 'I enjoy traveling.', 'Choose the correct sentence.', '["I enjoy to travel.","I enjoy traveling.","She suggested to leave."]'::jsonb, 1, 1050, true),
  ('en-grammar-extra-05-ex-2', 'en-grammar-extra-05', 'en', 'B1', 'Gerúndio e infinitivo · exercício 2', 'Suggest seleciona forma em -ing.', 'She suggested leaving.', 'Choose the correct sentence.', '["She suggested to leave.","She suggested leaving.","I enjoy to travel."]'::jsonb, 1, 1051, true),
  ('en-grammar-extra-06-ex-1', 'en-grammar-extra-06', 'en', 'B1', 'Collocations e expressões frequentes · exercício 1', 'Decision forma collocation com make.', 'Make a decision.', 'Choose the correct sentence.', '["Do a decision.","Make a decision.","A powerful rain."]'::jsonb, 1, 1060, true),
  ('en-grammar-extra-06-ex-2', 'en-grammar-extra-06', 'en', 'B1', 'Collocations e expressões frequentes · exercício 2', 'Heavy é a combinação convencional com rain.', 'Heavy rain.', 'Choose the correct sentence.', '["A powerful rain.","Heavy rain.","Do a decision."]'::jsonb, 1, 1061, true),
  ('en-grammar-extra-07-ex-1', 'en-grammar-extra-07', 'en', 'B2', 'Phrasal verbs avançados e registro · exercício 1', 'Carry out significa realizar uma atividade planejada.', 'We carried out the research.', 'Choose the correct sentence.', '["We carried the research.","We carried out the research.","She brought the issue up it."]'::jsonb, 1, 1070, true),
  ('en-grammar-extra-07-ex-2', 'en-grammar-extra-07', 'en', 'B2', 'Phrasal verbs avançados e registro · exercício 2', 'Não repita o objeto após um phrasal verb separável.', 'She brought the issue up.', 'Choose the correct sentence.', '["She brought the issue up it.","She brought the issue up.","We carried the research."]'::jsonb, 1, 1071, true),
  ('en-grammar-extra-08-ex-1', 'en-grammar-extra-08', 'en', 'B2', 'Idioms, nuance e linguagem figurada · exercício 1', 'A expressão fixa usa on.', 'We are on the same page.', 'Choose the correct sentence.', '["We are in the same page.","We are on the same page.","Let''s start the ball rolling it."]'::jsonb, 1, 1080, true),
  ('en-grammar-extra-08-ex-2', 'en-grammar-extra-08', 'en', 'B2', 'Idioms, nuance e linguagem figurada · exercício 2', 'Não altere livremente uma expressão cristalizada.', 'Let''s get the ball rolling.', 'Choose the correct sentence.', '["Let''s start the ball rolling it.","Let''s get the ball rolling.","We are in the same page."]'::jsonb, 1, 1081, true),
  ('es-grammar-extra-01-ex-1', 'es-grammar-extra-01', 'es', 'A1', 'Preposiciones básicas: a, de, en, con · exercício 1', 'Destinos usam a.', 'Voy a Madrid.', 'Elige la frase correcta.', '["Voy en Madrid.","Voy a Madrid.","Vengo a Brasil."]'::jsonb, 1, 1010, true),
  ('es-grammar-extra-01-ex-2', 'es-grammar-extra-01', 'es', 'A1', 'Preposiciones básicas: a, de, en, con · exercício 2', 'Origem usa de.', 'Vengo de Brasil.', 'Elige la frase correcta.', '["Vengo a Brasil.","Vengo de Brasil.","Voy en Madrid."]'::jsonb, 1, 1011, true),
  ('es-grammar-extra-02-ex-1', 'es-grammar-extra-02', 'es', 'A2', 'Por e para · exercício 1', 'Uma finalidade usa para.', 'Trabajo para ganar dinero.', 'Elige la frase correcta.', '["Trabajo por ganar dinero.","Trabajo para ganar dinero.","Este regalo es por ti."]'::jsonb, 1, 1020, true),
  ('es-grammar-extra-02-ex-2', 'es-grammar-extra-02', 'es', 'A2', 'Por e para · exercício 2', 'Destinatário usa para.', 'Este regalo es para ti.', 'Elige la frase correcta.', '["Este regalo es por ti.","Este regalo es para ti.","Trabajo por ganar dinero."]'::jsonb, 1, 1021, true),
  ('es-grammar-extra-03-ex-1', 'es-grammar-extra-03', 'es', 'A2', 'Conjunciones y conectores básicos · exercício 1', 'Porque causal é escrito junto e sem acento.', 'No fui porque estaba enfermo.', 'Elige la frase correcta.', '["No fui por qué estaba enfermo.","No fui porque estaba enfermo.","Aunque llovía, pero salimos."]'::jsonb, 1, 1030, true),
  ('es-grammar-extra-03-ex-2', 'es-grammar-extra-03', 'es', 'A2', 'Conjunciones y conectores básicos · exercício 2', 'Embora já marca o contraste.', 'Aunque llovía, salimos.', 'Elige la frase correcta.', '["Aunque llovía, pero salimos.","Aunque llovía, salimos.","No fui por qué estaba enfermo."]'::jsonb, 1, 1031, true),
  ('es-grammar-extra-04-ex-1', 'es-grammar-extra-04', 'es', 'B1', 'Perífrasis verbales · exercício 1', 'Estar progressivo exige gerúndio.', 'Estoy estudiando.', 'Elige la frase correcta.', '["Estoy estudiar.","Estoy estudiando.","Acabo terminar."]'::jsonb, 1, 1040, true),
  ('es-grammar-extra-04-ex-2', 'es-grammar-extra-04', 'es', 'B1', 'Perífrasis verbales · exercício 2', 'A perífrase exige de.', 'Acabo de terminar.', 'Elige la frase correcta.', '["Acabo terminar.","Acabo de terminar.","Estoy estudiar."]'::jsonb, 1, 1041, true),
  ('es-grammar-extra-05-ex-1', 'es-grammar-extra-05', 'es', 'B1', 'Usos de se · exercício 1', 'Na passiva com nome plural, o verbo concorda.', 'Se venden casas.', 'Elige la frase correcta.', '["Se vende casas.","Se venden casas.","Le lo dije."]'::jsonb, 1, 1050, true),
  ('es-grammar-extra-05-ex-2', 'es-grammar-extra-05', 'es', 'B1', 'Usos de se · exercício 2', 'Le muda para se antes de lo.', 'Se lo dije.', 'Elige la frase correcta.', '["Le lo dije.","Se lo dije.","Se vende casas."]'::jsonb, 1, 1051, true),
  ('es-grammar-extra-06-ex-1', 'es-grammar-extra-06', 'es', 'B1', 'Conectores discursivos · exercício 1', 'Sin embargo conecta orações; a pesar de rege nome ou infinitivo.', 'A pesar de ser caro.', 'Elige la frase correcta.', '["Sin embargo de ser caro.","A pesar de ser caro.","Pienso de que vendrá."]'::jsonb, 1, 1060, true),
  ('es-grammar-extra-06-ex-2', 'es-grammar-extra-06', 'es', 'B1', 'Conectores discursivos · exercício 2', 'Pensar que não usa de; evite dequeísmo.', 'Pienso que vendrá.', 'Elige la frase correcta.', '["Pienso de que vendrá.","Pienso que vendrá.","Sin embargo de ser caro."]'::jsonb, 1, 1061, true),
  ('es-grammar-extra-07-ex-1', 'es-grammar-extra-07', 'es', 'B2', 'Subjuntivo e particularidades de uso · exercício 1', 'Desejo sobre outro sujeito pede subjuntivo.', 'Quiero que vengas.', 'Elige la frase correcta.', '["Quiero que vienes.","Quiero que vengas.","Cuando llegarás, avísame."]'::jsonb, 1, 1070, true),
  ('es-grammar-extra-07-ex-2', 'es-grammar-extra-07', 'es', 'B2', 'Subjuntivo e particularidades de uso · exercício 2', 'Evento futuro após cuando usa presente do subjuntivo.', 'Cuando llegues, avísame.', 'Elige la frase correcta.', '["Cuando llegarás, avísame.","Cuando llegues, avísame.","Quiero que vienes."]'::jsonb, 1, 1071, true),
  ('es-grammar-extra-08-ex-1', 'es-grammar-extra-08', 'es', 'B2', 'Expresiones idiomáticas y colocaciones · exercício 1', 'A expressão fixa é darse cuenta de.', 'Me di cuenta del error.', 'Elige la frase correcta.', '["Realicé cuenta del error.","Me di cuenta del error.","Estoy de acuerdo a ti."]'::jsonb, 1, 1080, true),
  ('es-grammar-extra-08-ex-2', 'es-grammar-extra-08', 'es', 'B2', 'Expresiones idiomáticas y colocaciones · exercício 2', 'A expressão rege con.', 'Estoy de acuerdo contigo.', 'Elige la frase correcta.', '["Estoy de acuerdo a ti.","Estoy de acuerdo contigo.","Realicé cuenta del error."]'::jsonb, 1, 1081, true),
  ('fr-grammar-extra-01-ex-1', 'fr-grammar-extra-01', 'fr', 'A1', 'Prépositions de lieu et de temps · exercício 1', 'País masculino usa au.', 'Je vais au Canada.', 'Choisissez la phrase correcte.', '["Je vais en Canada.","Je vais au Canada.","Je suis à la maison de Paul."]'::jsonb, 1, 1010, true),
  ('fr-grammar-extra-01-ex-2', 'fr-grammar-extra-01', 'fr', 'A1', 'Prépositions de lieu et de temps · exercício 2', 'Chez expressa casa ou estabelecimento de pessoa.', 'Je suis chez Paul.', 'Choisissez la phrase correcte.', '["Je suis à la maison de Paul.","Je suis chez Paul.","Je vais en Canada."]'::jsonb, 1, 1011, true),
  ('fr-grammar-extra-02-ex-1', 'fr-grammar-extra-02', 'fr', 'A2', 'Conjonctions essentielles · exercício 1', 'Depois de si condicional não se usa futuro.', 'Si j''ai le temps, je viendrai.', 'Choisissez la phrase correcte.', '["Si j''aurai le temps, je viendrai.","Si j''ai le temps, je viendrai.","Parce de il pleut."]'::jsonb, 1, 1020, true),
  ('fr-grammar-extra-02-ex-2', 'fr-grammar-extra-02', 'fr', 'A2', 'Conjonctions essentielles · exercício 2', 'A conjunção correta é parce que.', 'Parce qu''il pleut.', 'Choisissez la phrase correcte.', '["Parce de il pleut.","Parce qu''il pleut.","Si j''aurai le temps, je viendrai."]'::jsonb, 1, 1021, true),
  ('fr-grammar-extra-03-ex-1', 'fr-grammar-extra-03', 'fr', 'A2', 'Articles partitifs et quantité · exercício 1', 'De + le contrai para du.', 'Je veux du pain.', 'Choisissez la phrase correcte.', '["Je veux de le pain.","Je veux du pain.","Je ne mange pas du sucre."]'::jsonb, 1, 1030, true),
  ('fr-grammar-extra-03-ex-2', 'fr-grammar-extra-03', 'fr', 'A2', 'Articles partitifs et quantité · exercício 2', 'Na negação, use de.', 'Je ne mange pas de sucre.', 'Choisissez la phrase correcte.', '["Je ne mange pas du sucre.","Je ne mange pas de sucre.","Je veux de le pain."]'::jsonb, 1, 1031, true),
  ('fr-grammar-extra-04-ex-1', 'fr-grammar-extra-04', 'fr', 'B1', 'Pronoms y et en · exercício 1', 'Destino usa y.', 'Je vais à Paris, j''y vais.', 'Choisissez la phrase correcte.', '["Je vais à Paris, j''en vais.","Je vais à Paris, j''y vais.","J''ai trois livres. J''en ai."]'::jsonb, 1, 1040, true),
  ('fr-grammar-extra-04-ex-2', 'fr-grammar-extra-04', 'fr', 'B1', 'Pronoms y et en · exercício 2', 'A quantidade permanece depois do verbo.', 'J''en ai trois.', 'Choisissez la phrase correcte.', '["J''ai trois livres. J''en ai.","J''en ai trois.","Je vais à Paris, j''en vais."]'::jsonb, 1, 1041, true),
  ('fr-grammar-extra-05-ex-1', 'fr-grammar-extra-05', 'fr', 'B1', 'Connecteurs logiques · exercício 1', 'Malgré rege nome; bien que introduz oração.', 'Bien qu''il pleuve.', 'Choisissez la phrase correcte.', '["Malgré il pleut.","Bien qu''il pleuve.","Cependant de ce problème."]'::jsonb, 1, 1050, true),
  ('fr-grammar-extra-05-ex-2', 'fr-grammar-extra-05', 'fr', 'B1', 'Connecteurs logiques · exercício 2', 'Cependant é conector, não preposição.', 'Malgré ce problème.', 'Choisissez la phrase correcte.', '["Cependant de ce problème.","Malgré ce problème.","Malgré il pleut."]'::jsonb, 1, 1051, true),
  ('fr-grammar-extra-06-ex-1', 'fr-grammar-extra-06', 'fr', 'B1', 'Locutions verbales et expressions courantes · exercício 1', 'A locução usa avoir.', 'J''ai besoin d''aide.', 'Choisissez la phrase correcte.', '["Je suis besoin d''aide.","J''ai besoin d''aide.","Je réalise mon erreur."]'::jsonb, 1, 1060, true),
  ('fr-grammar-extra-06-ex-2', 'fr-grammar-extra-06', 'fr', 'B1', 'Locutions verbales et expressions courantes · exercício 2', 'Para perceber, a expressão idiomática comum é se rendre compte de.', 'Je me rends compte de mon erreur.', 'Choisissez la phrase correcte.', '["Je réalise mon erreur.","Je me rends compte de mon erreur.","Je suis besoin d''aide."]'::jsonb, 1, 1061, true),
  ('fr-grammar-extra-07-ex-1', 'fr-grammar-extra-07', 'fr', 'B2', 'Subjonctif et particularités · exercício 1', 'Il faut que seleciona subjuntivo.', 'Il faut que tu sois prêt.', 'Choisissez la phrase correcte.', '["Il faut que tu es prêt.","Il faut que tu sois prêt.","Après qu''il soit parti."]'::jsonb, 1, 1070, true),
  ('fr-grammar-extra-07-ex-2', 'fr-grammar-extra-07', 'fr', 'B2', 'Subjonctif et particularités · exercício 2', 'Na norma-padrão, après que usa indicativo.', 'Après qu''il est parti.', 'Choisissez la phrase correcte.', '["Après qu''il soit parti.","Après qu''il est parti.","Il faut que tu es prêt."]'::jsonb, 1, 1071, true),
  ('fr-grammar-extra-08-ex-1', 'fr-grammar-extra-08', 'fr', 'B2', 'Registre, liaison et expressions idiomatiques · exercício 1', 'Com on, o verbo fica na terceira pessoa singular.', 'On va partir.', 'Choisissez la phrase correcte.', '["Nous on allons partir.","On va partir.","Je suis chaud."]'::jsonb, 1, 1080, true),
  ('fr-grammar-extra-08-ex-2', 'fr-grammar-extra-08', 'fr', 'B2', 'Registre, liaison et expressions idiomatiques · exercício 2', 'Sensação de calor usa avoir chaud.', 'J''ai chaud.', 'Choisissez la phrase correcte.', '["Je suis chaud.","J''ai chaud.","Nous on allons partir."]'::jsonb, 1, 1081, true),
  ('it-grammar-extra-01-ex-1', 'it-grammar-extra-01', 'it', 'A1', 'Preposizioni semplici e articolate · exercício 1', 'Cidades normalmente usam a.', 'Vado a Roma.', 'Scegli la frase corretta.', '["Vado in Roma.","Vado a Roma.","Sono a Italia."]'::jsonb, 1, 1010, true),
  ('it-grammar-extra-01-ex-2', 'it-grammar-extra-01', 'it', 'A1', 'Preposizioni semplici e articolate · exercício 2', 'Países normalmente usam in.', 'Sono in Italia.', 'Scegli la frase corretta.', '["Sono a Italia.","Sono in Italia.","Vado in Roma."]'::jsonb, 1, 1011, true),
  ('it-grammar-extra-02-ex-1', 'it-grammar-extra-02', 'it', 'A2', 'Congiunzioni essenziali · exercício 1', 'Evite duplicar causa e consequência e preserve a lógica.', 'Poiché ero stanco, sono rimasto a casa.', 'Scegli la frase corretta.', '["Perché ero stanco, quindi sono uscito.","Poiché ero stanco, sono rimasto a casa.","Anche se ma piove."]'::jsonb, 1, 1020, true),
  ('it-grammar-extra-02-ex-2', 'it-grammar-extra-02', 'it', 'A2', 'Congiunzioni essenziali · exercício 2', 'Anche se já marca concessão.', 'Anche se piove, usciamo.', 'Scegli la frase corretta.', '["Anche se ma piove.","Anche se piove, usciamo.","Perché ero stanco, quindi sono uscito."]'::jsonb, 1, 1021, true),
  ('it-grammar-extra-03-ex-1', 'it-grammar-extra-03', 'it', 'A2', 'Essere, avere e particularidades · exercício 1', 'Idade usa avere.', 'Ho 30 anni.', 'Scegli la frase corretta.', '["Sono 30 anni.","Ho 30 anni.","Ho arrivato tardi."]'::jsonb, 1, 1030, true),
  ('it-grammar-extra-03-ex-2', 'it-grammar-extra-03', 'it', 'A2', 'Essere, avere e particularidades · exercício 2', 'Arrivare forma passato prossimo com essere.', 'Sono arrivato tardi.', 'Scegli la frase corretta.', '["Ho arrivato tardi.","Sono arrivato tardi.","Sono 30 anni."]'::jsonb, 1, 1031, true),
  ('it-grammar-extra-04-ex-1', 'it-grammar-extra-04', 'it', 'B1', 'Ci e ne · exercício 1', 'Lugar usa ci.', 'Vado a Roma e ci resto.', 'Scegli la frase corretta.', '["Vado a Roma e ne resto.","Vado a Roma e ci resto.","Ho tre libri. Ne ho."]'::jsonb, 1, 1040, true),
  ('it-grammar-extra-04-ex-2', 'it-grammar-extra-04', 'it', 'B1', 'Ci e ne · exercício 2', 'A quantidade permanece expressa.', 'Ne ho tre.', 'Scegli la frase corretta.', '["Ho tre libri. Ne ho.","Ne ho tre.","Vado a Roma e ne resto."]'::jsonb, 1, 1041, true),
  ('it-grammar-extra-05-ex-1', 'it-grammar-extra-05', 'it', 'B1', 'Connettivi per argomentare · exercício 1', 'Nonostante + oração pede congiuntivo.', 'Nonostante sia caro.', 'Scegli la frase corretta.', '["Nonostante è caro.","Nonostante sia caro.","Tuttavia di questo problema."]'::jsonb, 1, 1050, true),
  ('it-grammar-extra-05-ex-2', 'it-grammar-extra-05', 'it', 'B1', 'Connettivi per argomentare · exercício 2', 'Tuttavia não funciona como preposição.', 'Nonostante questo problema.', 'Scegli la frase corretta.', '["Tuttavia di questo problema.","Nonostante questo problema.","Nonostante è caro."]'::jsonb, 1, 1051, true),
  ('it-grammar-extra-06-ex-1', 'it-grammar-extra-06', 'it', 'B1', 'Verbi pronominali ed espressioni comuni · exercício 1', 'Farcela exige as partículas ce e la.', 'Io ce la faccio.', 'Scegli la frase corretta.', '["Io faccio la.","Io ce la faccio.","Ci vuole due ore."]'::jsonb, 1, 1060, true),
  ('it-grammar-extra-06-ex-2', 'it-grammar-extra-06', 'it', 'B1', 'Verbi pronominali ed espressioni comuni · exercício 2', 'Volerci concorda com o elemento plural.', 'Ci vogliono due ore.', 'Scegli la frase corretta.', '["Ci vuole due ore.","Ci vogliono due ore.","Io faccio la."]'::jsonb, 1, 1061, true),
  ('it-grammar-extra-07-ex-1', 'it-grammar-extra-07', 'it', 'B2', 'Congiuntivo e periodo ipotetico · exercício 1', 'Na norma cuidada, opinião subjetiva pede congiuntivo.', 'Penso che sia giusto.', 'Scegli la frase corretta.', '["Penso che è giusto.","Penso che sia giusto.","Se avrei tempo, viaggerei."]'::jsonb, 1, 1070, true),
  ('it-grammar-extra-07-ex-2', 'it-grammar-extra-07', 'it', 'B2', 'Congiuntivo e periodo ipotetico · exercício 2', 'A oração com se não usa condicional.', 'Se avessi tempo, viaggerei.', 'Scegli la frase corretta.', '["Se avrei tempo, viaggerei.","Se avessi tempo, viaggerei.","Penso che è giusto."]'::jsonb, 1, 1071, true),
  ('it-grammar-extra-08-ex-1', 'it-grammar-extra-08', 'it', 'B2', 'Espressioni idiomatiche e collocazioni · exercício 1', 'Decisione forma colocação com prendere.', 'Prendere una decisione.', 'Scegli la frase corretta.', '["Fare una decisione.","Prendere una decisione.","Non vedo l''ora per partire."]'::jsonb, 1, 1080, true),
  ('it-grammar-extra-08-ex-2', 'it-grammar-extra-08', 'it', 'B2', 'Espressioni idiomatiche e collocazioni · exercício 2', 'A expressão rege di + infinitivo.', 'Non vedo l''ora di partire.', 'Scegli la frase corretta.', '["Non vedo l''ora per partire.","Non vedo l''ora di partire.","Fare una decisione."]'::jsonb, 1, 1081, true);
